import type { ImageModelSpec } from "./types";

export const imageModelRegistry: ImageModelSpec[] = [
  {
    id: "IMG-FLUX-SCHNELL",
    displayName: "FLUX.1-schnell",
    kind: "text_to_image",
    tier: "starter",
    repoId: "black-forest-labs/FLUX.1-schnell",
    runtime: "diffusers",
    license: "Apache-2.0",
    enabledByDefault: true,
    recommendedFor: [
      "fast concept art",
      "draft frames",
      "prompt iteration",
      "preview generation",
    ],
    personaUse: ["rough identity exploration", "scene drafts"],
    notes: ["Fast default preview generator.", "Keep higher-quality production generation separate."],
  },
  {
    id: "IMG-SDXL-BASE",
    displayName: "Stable Diffusion XL 1.0",
    kind: "text_to_image",
    tier: "starter",
    repoId: "stabilityai/stable-diffusion-xl-base-1.0",
    runtime: "comfyui",
    license: "OpenRAIL++",
    enabledByDefault: true,
    recommendedFor: [
      "ComfyUI workflows",
      "LoRA",
      "ControlNet",
      "IP-Adapter",
      "custom styles",
    ],
    personaUse: ["character consistency", "wardrobe variants", "pose and scene control"],
    notes: ["Primary ecosystem model.", "Best starting point for Persona/Scene pipelines."],
  },
  {
    id: "IMG-IP-ADAPTER-SDXL",
    displayName: "IP-Adapter SDXL",
    kind: "identity_adapter",
    tier: "standard",
    repoId: "h94/IP-Adapter",
    runtime: "comfyui",
    license: "Apache-2.0",
    enabledByDefault: true,
    recommendedFor: [
      "reference-image conditioning",
      "character look consistency",
      "style reference",
    ],
    personaUse: ["F-01 identity reference", "M-01 identity reference", "same character across scenes"],
    notes: [
      "Use the regular IP-Adapter SDXL path as the default identity adapter.",
      "Do not make the FaceID variant the commercial default without a separate license review.",
    ],
  },
  {
    id: "IMG-QWEN-2512",
    displayName: "Qwen-Image-2512",
    kind: "text_to_image",
    tier: "heavy",
    repoId: "Qwen/Qwen-Image-2512",
    runtime: "diffusers",
    license: "Apache-2.0",
    enabledByDefault: false,
    recommendedFor: [
      "high-quality final art",
      "complex composition",
      "text rendering in images",
      "hero images",
    ],
    personaUse: ["final character scenes", "covers", "posters"],
    notes: ["20B class model.", "Large download; keep optional until benchmarked on local hardware."],
  },
  {
    id: "IMG-QWEN-EDIT-2511",
    displayName: "Qwen-Image-Edit-2511",
    kind: "image_edit",
    tier: "heavy",
    repoId: "Qwen/Qwen-Image-Edit-2511",
    runtime: "diffusers",
    license: "Apache-2.0",
    enabledByDefault: false,
    recommendedFor: [
      "natural-language image editing",
      "wardrobe changes",
      "background replacement",
      "object replacement",
      "scene corrections",
    ],
    personaUse: [
      "keep base character and change context",
      "edit clothing and props",
      "repair generated frames",
    ],
    notes: ["Preferred heavy image-edit model."],
  },
  {
    id: "IMG-QWEN-LAYERED",
    displayName: "Qwen-Image-Layered",
    kind: "layered_edit",
    tier: "heavy",
    repoId: "Qwen/Qwen-Image-Layered",
    runtime: "diffusers",
    license: "Apache-2.0",
    enabledByDefault: false,
    recommendedFor: [
      "layer decomposition",
      "editable design assets",
      "comic panels",
      "banners",
      "marketing compositions",
    ],
    personaUse: ["separate character/background/props for downstream editing"],
    notes: ["Useful for design-oriented pipelines rather than raw generation only."],
  },
];

export function imageModelsForTier(tier: ImageModelTier) {
  const order = { starter: 0, standard: 1, heavy: 2 } as const;
  return imageModelRegistry.filter((model) => order[model.tier] <= order[tier]);
}
