import type { ImageModelSpec } from "./types";

export const imageModelRegistry: ImageModelSpec[] = [
  {
    id: "IMG-JUGGERNAUT-XL-V8",
    capabilities: ["portrait", "full_body", "fashion", "swimwear", "adult_artistic_nude", "anatomy_reference", "identity_consistency"],
    displayName: "JuggernautXL v8 Rundiffusion",
    kind: "text_to_image",
    tier: "standard",
    source: "local",
    localFilename: "juggernautXL_v8Rundiffusion.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: true,
    recommendedFor: [
      "primary SDXL generation",
      "photorealistic scenes",
      "character scenes",
      "storyboard finals",
    ],
    personaUse: [
      "main realistic character generator",
      "paired with IP-Adapter for identity consistency",
    ],
    notes: ["Present in local inventory.", "Treat as the current primary image generator until benchmarked."],
  },
  {
    id: "IMG-REALVIS-XL-50",
    capabilities: ["portrait", "full_body", "fashion", "swimwear", "adult_artistic_nude", "anatomy_reference"],
    displayName: "RealVisXL V5.0 Lightning",
    kind: "text_to_image",
    tier: "standard",
    source: "local",
    localFilename: "realvisxlV50_v50LightningBakedvae.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: true,
    recommendedFor: [
      "fast realistic generation",
      "portraits",
      "photo-like scenes",
    ],
    personaUse: ["fast persona previews", "realistic reference frames"],
    notes: ["Present in local inventory.", "Useful as a faster alternative to the main SDXL checkpoint."],
  },
  {
    id: "IMG-DREAMSHAPER-XL-LIGHTNING",
    capabilities: ["portrait", "full_body", "fashion", "comic", "poster"],
    displayName: "DreamShaperXL Lightning",
    kind: "text_to_image",
    tier: "standard",
    source: "local",
    localFilename: "dreamshaperXL_lightningDPMSDE.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: false,
    recommendedFor: [
      "stylized scenes",
      "creative concepts",
      "fast visual exploration",
    ],
    personaUse: ["alternative style rendering"],
    notes: ["Present in local inventory.", "Keep as style/creative alternative rather than duplicate default."],
  },
  {
    id: "IMG-SDXL-BASE",
    capabilities: ["portrait", "full_body", "fashion", "swimwear", "adult_artistic_nude", "anatomy_reference", "pose_control", "inpainting"],
    displayName: "Stable Diffusion XL Base 1.0",
    kind: "text_to_image",
    tier: "starter",
    source: "local",
    localFilename: "sd_xl_base_1.0.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: true,
    recommendedFor: [
      "baseline SDXL workflows",
      "LoRA compatibility",
      "ControlNet workflows",
      "IP-Adapter workflows",
    ],
    personaUse: ["neutral baseline for persona and control experiments"],
    notes: ["Present in local inventory.", "Keep as stable baseline even if specialized checkpoints look better."],
  },
  {
    id: "IMG-SDXL-MSPAINT-PORTRAIT",
    capabilities: ["portrait", "expression_sheet"],
    displayName: "SDXL MSPaint Portrait",
    kind: "text_to_image",
    tier: "standard",
    source: "local",
    localFilename: "SDXL_MSPaint_Portrait.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: false,
    recommendedFor: ["portrait specialization"],
    personaUse: ["portrait studies", "head and face framing"],
    notes: ["Present in local inventory.", "Specialist model; not a default general generator."],
  },
  {
    id: "IMG-IP-ADAPTER-PLUS-FACE-SDXL",
    capabilities: ["identity_consistency", "portrait", "expression_sheet"],
    displayName: "IP-Adapter Plus Face SDXL ViT-H",
    kind: "identity_adapter",
    tier: "standard",
    source: "local",
    localFilename: "ip-adapter-plus-face_sdxl_vit-h.bin",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: true,
    recommendedFor: [
      "reference-image conditioning",
      "face consistency",
      "character continuity",
    ],
    personaUse: [
      "F-01 identity reference",
      "M-01 identity reference",
      "same recognizable character across scenes",
    ],
    notes: ["Present in local inventory.", "Core component for Persona consistency."],
  },
  {
    id: "IMG-SD15-INPAINT-GGUF",
    capabilities: ["inpainting"],
    displayName: "Stable Diffusion 1.5 Inpainting Q8",
    kind: "inpainting",
    tier: "starter",
    source: "local",
    localFilename: "stable-diffusion-v1-5-inpainting-Q8_0.gguf",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: true,
    recommendedFor: [
      "local repairs",
      "mask-based replacement",
      "small scene corrections",
    ],
    personaUse: ["repair details without regenerating the whole frame"],
    notes: ["Present in local inventory.", "Use for targeted editing rather than full generation."],
  },
  {
    id: "IMG-ICLIGHT-SD15",
    capabilities: ["relighting"],
    displayName: "IC-Light SD1.5",
    kind: "lighting",
    tier: "standard",
    source: "local",
    localFilename: "iclight_sd15_fc.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: true,
    recommendedFor: [
      "relighting",
      "lighting consistency",
      "scene mood correction",
    ],
    personaUse: ["keep character while changing light and mood"],
    notes: ["Present in local inventory."],
  },
  {
    id: "IMG-BODY-POSE-CONTROL",
    capabilities: ["pose_control", "full_body"],
    displayName: "Body Pose Model",
    kind: "control_adapter",
    tier: "starter",
    source: "local",
    localFilename: "body_pose_model.pth",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: true,
    recommendedFor: ["pose extraction", "pose-guided generation"],
    personaUse: ["repeatable character poses", "storyboard blocking"],
    notes: ["Present in local inventory.", "Exact upstream package should be identified before distribution."],
  },
  {
    id: "IMG-SAM-VIT-H",
    displayName: "SAM ViT-H",
    kind: "segmentation",
    tier: "standard",
    source: "local",
    localFilename: "sam_vit_h_4b8939.pth",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: true,
    recommendedFor: ["segmentation", "mask generation", "object isolation"],
    personaUse: ["separate character, clothes, props or background before editing"],
    notes: ["Present in local inventory."],
  },
  {
    id: "IMG-LORA-HEADSHOT",
    displayName: "Headshot LoRA",
    kind: "lora",
    tier: "starter",
    source: "local",
    localFilename: "Headshot.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: false,
    recommendedFor: ["headshot specialization"],
    personaUse: ["portrait/headshot variants"],
    notes: ["Multiple copies are visible in inventory; deduplicate paths before packaging."],
  },
  {
    id: "IMG-LORA-CINEMATIC-LIGHTING",
    displayName: "Cinematic Lighting LoRA",
    kind: "lora",
    tier: "starter",
    source: "local",
    localFilename: "cinematic%20lighting.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: false,
    recommendedFor: ["cinematic lighting style"],
    personaUse: ["scene mood variants"],
    notes: ["Multiple copies are visible in inventory; deduplicate paths before packaging."],
  },
  {
    id: "IMG-LORA-FLUX-SKIN-PORTRAITS",
    displayName: "FLUX Detailed Skin Portraits LoRA",
    kind: "lora",
    tier: "standard",
    source: "local",
    localFilename: "flux-detailed_skin_portraits-000005.safetensors",
    runtime: "comfyui",
    license: "VERIFY_SOURCE_LICENSE",
    installed: true,
    enabledByDefault: false,
    recommendedFor: ["portrait skin detail"],
    personaUse: ["high-detail portrait experiments"],
    notes: [
      "The LoRA is present.",
      "No FLUX base checkpoint was confirmed by the supplied inventory, so this LoRA is not currently considered runnable.",
    ],
  },
];

export function installedImageModels() {
  return imageModelRegistry.filter((model) => model.installed);
}

export function enabledImageModels() {
  return imageModelRegistry.filter((model) => model.installed && model.enabledByDefault);
}
