import {
  audioBufferToWavBlob,
  cloneAudioBuffer,
  cutSelection,
  drawWaveform,
  formatBytes,
  formatClock,
  preferredMime,
  trimToSelection,
} from "./recorder-audio.js";
import { createRecorderTrace } from "./recorder-trace.js";

const PAGE_ID = "bookcraft-recorder-page-v3";
const STYLE_ID = "bookcraft-recorder-page-v3-style";

function injectStyles() {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement("style");
  style.id = STYLE_ID;
  style.textContent = `
    .br-launch{position:fixed;right:20px;bottom:20px;z-index:11990;border:1px solid rgba(255,255,255,.14);border-radius:14px;padding:11px 15px;background:linear-gradient(145deg,rgba(18,29,46,.98),rgba(8,14,25,.98));color:#eef5ff;box-shadow:0 18px 55px rgba(0,0,0,.46);font:650 12px Inter,system-ui,sans-serif;cursor:pointer}
    .br-page{position:fixed;inset:0;z-index:12000;display:none;overflow:auto;background:radial-gradient(circle at 20% -10%,rgba(60,120,200,.18),transparent 36%),linear-gradient(180deg,#07101a,#050a12 70%);color:#eef5ff;font-family:Inter,system-ui,sans-serif}.br-page.open{display:block}
    .br-top{position:sticky;top:0;z-index:20;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:12px 18px;border-bottom:1px solid rgba(255,255,255,.07);background:rgba(7,13,23,.92);backdrop-filter:blur(18px)}
    .br-left,.br-right,.br-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.br-right{justify-content:flex-end}.br-title{text-align:center}.br-title strong{display:block;font-size:13px;letter-spacing:.14em}.br-title span{font-size:9px;color:#72859b}
    .br-btn{border:1px solid rgba(255,255,255,.11);border-radius:10px;padding:8px 10px;background:rgba(255,255,255,.045);color:#dae5f3;font-size:10px;cursor:pointer}.br-btn:hover{border-color:rgba(105,175,255,.32);background:rgba(72,128,205,.1)}.br-btn:disabled{opacity:.34;cursor:not-allowed}.br-btn.danger{border-color:rgba(255,102,116,.24);color:#ffb5bd}.br-btn.primary{border-color:rgba(97,177,255,.31);background:rgba(72,129,205,.12)}
    .br-state{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;border-radius:999px;border:1px solid rgba(96,193,143,.18);background:rgba(56,154,105,.07);color:#9edeb9;font-size:9px}.br-state i{width:6px;height:6px;border-radius:50%;background:currentColor;box-shadow:0 0 10px currentColor}
    .br-shell{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:16px;max-width:1620px;margin:0 auto;padding:18px 20px 34px}.br-main{min-width:0}.br-card{border:1px solid rgba(255,255,255,.075);border-radius:19px;background:linear-gradient(165deg,rgba(16,26,42,.88),rgba(8,14,25,.88));box-shadow:0 18px 60px rgba(0,0,0,.24)}
    .br-wave-card{padding:16px}.br-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:12px}.br-kicker{font-size:9px;color:#7697c1;letter-spacing:.16em}.br-head h1{margin:4px 0;font-size:23px}.br-head p{margin:0;color:#71849b;font-size:10px}.br-file{text-align:right}.br-file strong{display:block;max-width:360px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:10px}.br-file span{display:block;margin-top:4px;color:#6e8198;font-size:9px}
    .br-wave-wrap{position:relative;height:320px;overflow:hidden;border:1px solid rgba(255,255,255,.08);border-radius:17px;background:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px),radial-gradient(circle at 50% 115%,rgba(70,145,225,.12),transparent 50%),#07111c;background-size:100% 52px,72px 100%,auto,auto;user-select:none}.br-wave-wrap canvas{position:absolute;inset:0;width:100%;height:100%;cursor:crosshair}.br-empty{position:absolute;inset:0;display:grid;place-items:center;color:#53677f;text-align:center;font-size:11px;pointer-events:none}.br-time{position:absolute;left:14px;top:13px;padding:7px 10px;border-radius:9px;background:rgba(3,8,15,.66);font:700 23px ui-monospace,Consolas,monospace}.br-time small{display:block;margin-top:4px;font:9px Inter,system-ui,sans-serif;color:#70839a;text-transform:uppercase}.br-selection{position:absolute;right:14px;bottom:13px;padding:7px 9px;border-radius:9px;background:rgba(3,8,15,.66);font:9px ui-monospace,Consolas,monospace;color:#91a8c3}
    .br-level{display:grid;grid-template-columns:105px 1fr 50px;gap:10px;align-items:center;margin-top:11px}.br-level label{font-size:9px;color:#74869c;text-transform:uppercase;letter-spacing:.12em}.br-bars{display:grid;grid-template-columns:repeat(30,1fr);gap:3px}.br-bars i{height:8px;border-radius:3px;background:rgba(255,255,255,.055)}.br-bars i.on{background:linear-gradient(90deg,#62c58d,#b6d765)}.br-bars i.hot{background:linear-gradient(90deg,#e7c451,#ef7a50)}.br-level output{text-align:right;color:#8da1b8;font:10px ui-monospace,Consolas,monospace}
    .br-transport{display:grid;grid-template-columns:1fr auto 1fr;gap:18px;align-items:center;padding:16px 8px 3px}.br-side{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.br-side.right{justify-content:flex-end}.br-record-wrap{text-align:center}.br-record{width:94px;height:94px;border-radius:50%;border:1px solid rgba(255,255,255,.15);background:radial-gradient(circle at 35% 30%,#ff767a,#dd3341 66%,#951b29);box-shadow:0 0 0 10px rgba(255,255,255,.035),0 14px 42px rgba(215,45,60,.35),inset 0 1px 2px rgba(255,255,255,.38);cursor:pointer;display:grid;place-items:center}.br-record:before{content:"";width:30px;height:30px;border-radius:50%;background:#fff}.br-record.recording:before{width:26px;height:26px;border-radius:6px}.br-record:disabled{opacity:.4}.br-caption{margin-top:10px;color:#8497ad;font-size:9px;letter-spacing:.09em;text-transform:uppercase}
    .br-sub{margin-top:14px;padding:14px 16px}.br-sub-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px}.br-sub h3{margin:0;font-size:11px;letter-spacing:.05em}.br-sub small{color:#71849a;font-size:9px}.br-sub audio{width:100%;height:38px;margin-top:8px}.br-meta{display:flex;justify-content:space-between;gap:12px;margin-top:8px;color:#71849b;font-size:9px}
    .br-stt{margin-top:14px;padding:14px 16px;display:flex;justify-content:space-between;gap:12px;align-items:center}.br-stt strong{font-size:11px}.br-stt span{display:block;margin-top:4px;color:#71849a;font-size:9px}
    .br-trace{position:sticky;top:70px;align-self:start;max-height:calc(100vh - 90px);overflow:hidden;display:flex;flex-direction:column}.br-trace-head{padding:13px 14px 10px;border-bottom:1px solid rgba(255,255,255,.06)}.br-trace-head h3{margin:0;font-size:11px}.br-trace-head p{margin:5px 0 0;color:#71849a;font-size:9px}.br-diag{display:grid;grid-template-columns:1fr 1fr;gap:6px;padding:10px 12px;border-bottom:1px solid rgba(255,255,255,.055)}.br-diag div{padding:7px;border-radius:9px;background:rgba(255,255,255,.026)}.br-diag span{display:block;color:#687d96;font-size:8px;text-transform:uppercase}.br-diag strong{display:block;margin-top:3px;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.br-trace-actions{display:flex;gap:6px;padding:9px 12px;border-bottom:1px solid rgba(255,255,255,.055)}.br-trace-actions button{flex:1}.br-events{overflow:auto;padding:6px 9px 12px}.br-event{padding:8px 7px;border-bottom:1px solid rgba(255,255,255,.045);font:9px/1.45 ui-monospace,Consolas,monospace;color:#9eafc4}.br-event b{color:#d6e2f1}.br-event small{display:block;color:#61758d;margin-top:2px;word-break:break-word}.br-event.error b{color:#ffadb5}.br-event.ready b{color:#9de0ba}.br-event.warn b{color:#dbc67e}
    .br-toast{position:fixed;right:24px;top:74px;z-index:12030;display:none;max-width:430px;padding:10px 12px;border:1px solid rgba(255,255,255,.1);border-radius:11px;background:rgba(8,15,26,.97);box-shadow:0 18px 55px rgba(0,0,0,.45);font-size:10px}.br-toast.show{display:block}
    @media(max-width:1060px){.br-shell{grid-template-columns:1fr}.br-trace{position:relative;top:auto;max-height:420px}.br-wave-wrap{height:260px}}@media(max-width:760px){.br-top{grid-template-columns:1fr auto}.br-title{display:none}.br-shell{padding:10px}.br-transport{grid-template-columns:1fr}.br-record-wrap{grid-row:1}.br-side,.br-side.right{justify-content:center}.br-wave-wrap{height:220px}.br-level{grid-template-columns:85px 1fr 42px}}
  `;
  document.head.appendChild(style);
}

function buildPage() {
  let page = document.getElementById(PAGE_ID);
  if (page) return page;
  const launcher = document.createElement("button");
  launcher.className = "br-launch";
  launcher.type = "button";
  launcher.textContent = "🎙 Диктофон";
  page = document.createElement("section");
  page.id = PAGE_ID;
  page.className = "br-page";
  page.innerHTML = `
    <header class="br-top">
      <div class="br-left"><button class="br-btn" data-action="close">← BOOK.CRAFT</button><span class="br-state"><i></i><b data-r="state-badge">EMPTY</b></span></div>
      <div class="br-title"><strong>BOOK·CRAFT RECORDER</strong><span>запись · монтаж · прослушивание</span></div>
      <div class="br-right"><span data-r="clock" style="font:10px ui-monospace,Consolas,monospace;color:#8ca0b8">00:00</span><button class="br-btn" data-action="copy-report">Копировать отчёт</button></div>
    </header>
    <div class="br-shell">
      <main class="br-main">
        <section class="br-card br-wave-card">
          <div class="br-head"><div><span class="br-kicker">VOICE RECORDER · LOCAL</span><h1>Диктофон</h1><p>Старт · пауза · стоп · прослушивание · выделение и удаление фрагмента.</p></div><div class="br-file"><strong data-r="file-name">Новая запись</strong><span data-r="file-meta">микрофон · локально</span></div></div>
          <div class="br-wave-wrap"><canvas data-r="wave"></canvas><div class="br-empty" data-r="empty">Нажмите «Запись» — здесь появится живая волна.<br>После остановки выделяйте куски мышкой.</div><div class="br-time"><span data-r="timer">00:00</span><small data-r="state">готов к записи</small></div><div class="br-selection" data-r="selection">Выделение: —</div></div>
          <div class="br-level"><label>Уровень голоса</label><div class="br-bars">${Array.from({ length: 30 }, () => "<i></i>").join("")}</div><output data-r="level">0%</output></div>
          <div class="br-transport">
            <div class="br-side"><button class="br-btn" data-action="play" disabled>▶ Прослушать</button><button class="br-btn" data-action="pause-record" disabled>Ⅱ Пауза</button></div>
            <div class="br-record-wrap"><button class="br-record" data-action="record" aria-label="Начать запись"></button><div class="br-caption" data-r="caption">Начать запись</div></div>
            <div class="br-side right"><button class="br-btn" data-action="stop" disabled>■ Стоп</button><button class="br-btn" data-action="new">Новая</button></div>
          </div>
        </section>
        <section class="br-card br-sub"><div class="br-sub-head"><div><h3>РЕДАКТИРОВАНИЕ</h3><small>Выделите фрагмент на волне. Изменения можно отменять и возвращать.</small></div><span data-r="edit-state" style="color:#70839a;font-size:9px">нет выделения</span></div><div class="br-row"><button class="br-btn danger" data-action="delete-selection" disabled>✂ Удалить выделенное</button><button class="br-btn" data-action="trim-selection" disabled>Обрезать до выделенного</button><button class="br-btn" data-action="undo" disabled>↶ Отмена</button><button class="br-btn" data-action="redo" disabled>↷ Вернуть</button><button class="br-btn" data-action="clear-selection" disabled>Снять выделение</button></div></section>
        <section class="br-card br-sub"><h3>ПРОСЛУШИВАНИЕ И ФАЙЛ</h3><audio data-r="preview" controls preload="metadata"></audio><div class="br-row" style="margin-top:10px"><button class="br-btn primary" data-action="download" disabled>↓ Сохранить запись</button><button class="br-btn" data-action="import">↑ Импорт MP3 / WAV / WebM</button><input data-r="file-input" type="file" accept="audio/*,.mp3,.wav,.m4a,.ogg,.webm" hidden><button class="br-btn danger" data-action="clear" disabled>Удалить запись</button></div><div class="br-meta"><span data-r="duration">Длительность: —</span><span data-r="format">Формат: —</span></div></section>
        <section class="br-card br-stt"><div><strong>РАСПОЗНАВАНИЕ</strong><span>Этап 2. Здесь появится реальный прогресс Whisper, сегменты и ETA.</span></div><button class="br-btn" data-action="recognize" disabled>✦ Распознать · этап 2</button></section>
      </main>
      <aside class="br-card br-trace"><div class="br-trace-head"><h3>ТРАССИРОВКА / ОТЧЁТ</h3><p>Копируйте отчёт и присылайте мне. Аудио и будущий текст в трассу не попадают.</p></div><div class="br-diag"><div><span>Session</span><strong data-r="diag-session">—</strong></div><div><span>State</span><strong data-r="diag-state">EMPTY</strong></div><div><span>MediaRecorder</span><strong data-r="diag-media">—</strong></div><div><span>AudioContext</span><strong data-r="diag-audio">—</strong></div><div><span>MIME</span><strong data-r="diag-mime">—</strong></div><div><span>Events</span><strong data-r="diag-events">0</strong></div></div><div class="br-trace-actions"><button class="br-btn" data-action="copy-report">Копировать</button><button class="br-btn" data-action="clear-trace">Очистить</button></div><div class="br-events" data-r="events"></div></aside>
    </div><div class="br-toast" data-r="toast"></div>`;
  document.body.append(launcher, page);
  launcher.addEventListener("click", () => { page.classList.add("open"); page._recorder?.trace("ui.open", {}, "ready"); });
  return page;
}

function makeController(page) {
  const q = (selector) => page.querySelector(selector);
  const qa = (selector) => Array.from(page.querySelectorAll(selector));
  const AudioContextCtor = window.AudioContext || window.webkitAudioContext;
  const audioContext = AudioContextCtor ? new AudioContextCtor() : null;
  const state = { phase:"EMPTY", recorder:null, stream:null, chunks:[], recordStartedAt:0, elapsedBeforePause:0, timer:null, analyser:null, sourceNode:null, raf:null, buffer:null, blob:null, fileName:"", mime:"", recordMime:"", objectUrl:"", duration:0, playhead:0, selectionStart:null, selectionEnd:null, selecting:false, undo:[], redo:[] };
  let tracer;

  const toast = (message) => { const node=q('[data-r="toast"]'); node.textContent=message; node.classList.add("show"); clearTimeout(node._t); node._t=setTimeout(()=>node.classList.remove("show"),2400); };
  const traceRender = () => {
    if (!tracer) return;
    q('[data-r="diag-session"]').textContent = tracer.state.sessionId.slice(0,8);
    q('[data-r="diag-state"]').textContent = state.phase;
    q('[data-r="diag-media"]').textContent = typeof MediaRecorder === "undefined" ? "NO" : "YES";
    q('[data-r="diag-audio"]').textContent = audioContext ? "YES" : "NO";
    q('[data-r="diag-mime"]').textContent = state.recordMime || state.mime || "—";
    q('[data-r="diag-events"]').textContent = String(tracer.state.events.length);
    q('[data-r="events"]').innerHTML = tracer.state.events.slice(-70).reverse().map((event)=>{ const meta=Object.entries(event.meta||{}).map(([k,v])=>`${k}=${v}`).join(" · "); return `<div class="br-event ${event.kind||""}"><b>#${event.seq} ${event.event}</b><small>${event.time.slice(11,23)} · ${event.state}${meta?` · ${meta}`:""}</small></div>`; }).join("");
  };
  tracer = createRecorderTrace(traceRender);
  const trace = (event,meta={},kind="") => tracer.trace(event,state.phase,meta,kind);

  const setPhase = (phase,reason="") => { const before=state.phase; state.phase=phase; q('[data-r="state-badge"]').textContent=phase; q('[data-r="state"]').textContent={EMPTY:"готов к записи",RECORDING:"идёт запись",PAUSED:"пауза",RECORDED:"запись готова",EDITING:"редактирование",PLAYING:"прослушивание"}[phase]||phase.toLowerCase(); trace("state.change",{from:before,to:phase,reason},phase==="RECORDED"?"ready":""); refreshControls(); traceRender(); };
  const recordElapsed = () => state.elapsedBeforePause + (state.recordStartedAt ? Date.now()-state.recordStartedAt : 0);
  const updateClock = () => { const ms=(state.phase==="RECORDING"||state.phase==="PAUSED")?recordElapsed():state.playhead*1000; q('[data-r="timer"]').textContent=formatClock(ms); q('[data-r="clock"]').textContent=formatClock(ms); };
  const startClock = () => { clearInterval(state.timer); updateClock(); state.timer=setInterval(updateClock,200); };
  const stopClock = () => { clearInterval(state.timer); state.timer=null; updateClock(); };
  const selection = () => { if(state.selectionStart==null||state.selectionEnd==null) return null; const start=Math.max(0,Math.min(state.selectionStart,state.selectionEnd)); const end=Math.min(state.duration,Math.max(state.selectionStart,state.selectionEnd)); return end-start>=0.025?{start,end}:null; };
  const renderSelection = () => { const range=selection(); q('[data-r="selection"]').textContent=range?`${formatClock(range.start*1000)} → ${formatClock(range.end*1000)} · ${(range.end-range.start).toFixed(3)} сек`:"Выделение: —"; q('[data-r="edit-state"]').textContent=range?`${(range.end-range.start).toFixed(2)} сек выделено`:"нет выделения"; refreshControls(); };
  const redraw = () => drawWaveform({canvas:q('[data-r="wave"]'),buffer:state.buffer,selection:selection(),playhead:state.playhead});
  const showEmpty = (yes) => { q('[data-r="empty"]').style.display=yes?"grid":"none"; };
  const updateLevel = (level) => { const bars=qa('.br-bars i'); const active=Math.round(Math.max(0,Math.min(1,level))*bars.length); bars.forEach((bar,index)=>{bar.classList.toggle("on",index<active);bar.classList.toggle("hot",index<active&&index>bars.length*.78);}); q('[data-r="level"]').textContent=`${Math.round(level*100)}%`; };
  const stopVisualizer = () => { if(state.raf)cancelAnimationFrame(state.raf); state.raf=null; try{state.sourceNode?.disconnect?.();}catch{} state.sourceNode=null; state.analyser=null; updateLevel(0); };
  const startVisualizer = (stream) => { if(!audioContext){trace("visualizer.unavailable",{},"warn");return;} try{audioContext.resume?.(); const analyser=audioContext.createAnalyser(); analyser.fftSize=2048; analyser.smoothingTimeConstant=.72; const source=audioContext.createMediaStreamSource(stream); source.connect(analyser); state.analyser=analyser; state.sourceNode=source; const data=new Uint8Array(analyser.fftSize); const draw=()=>{ if(!state.analyser)return; analyser.getByteTimeDomainData(data); const canvas=q('[data-r="wave"]'); const rect=canvas.getBoundingClientRect(); const ratio=Math.max(1,window.devicePixelRatio||1); canvas.width=Math.max(1,Math.floor(rect.width*ratio)); canvas.height=Math.max(1,Math.floor(rect.height*ratio)); const ctx=canvas.getContext("2d"); ctx.setTransform(ratio,0,0,ratio,0,0); ctx.clearRect(0,0,rect.width,rect.height); let power=0; ctx.beginPath(); data.forEach((value,index)=>{const n=(value-128)/128;power+=n*n;const x=index/(data.length-1)*rect.width;const y=rect.height/2+n*rect.height*.42;if(index===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});const rms=Math.sqrt(power/data.length);const level=Math.min(1,rms*5.4);ctx.strokeStyle=level>.78?"rgba(242,121,86,.95)":"rgba(85,229,178,.95)";ctx.lineWidth=2;ctx.stroke();updateLevel(level);state.raf=requestAnimationFrame(draw);}; draw();trace("visualizer.ready",{fft_size:analyser.fftSize},"ready");}catch(error){trace("visualizer.error",{error:error?.message||String(error)},"error");} };
  const revokeUrl = () => { if(state.objectUrl)URL.revokeObjectURL(state.objectUrl); state.objectUrl=""; };
  const setBlob = (blob,name,mime=blob?.type||"audio/wav") => { revokeUrl(); state.blob=blob; state.fileName=name||`bookcraft-${Date.now()}.wav`; state.mime=mime; state.objectUrl=URL.createObjectURL(blob); const audio=q('[data-r="preview"]'); audio.src=state.objectUrl; audio.load(); q('[data-r="file-name"]').textContent=state.fileName; q('[data-r="file-meta"]').textContent=`${state.mime||"audio"} · ${formatBytes(blob.size)}`; q('[data-r="format"]').textContent=`Формат: ${state.mime||"unknown"} · ${formatBytes(blob.size)}`; };
  const decodeBlob = async (blob,source) => { if(!audioContext)throw new Error("AudioContext недоступен"); trace("audio.decode.start",{source,size_bytes:blob.size,content_type:blob.type||"unknown"}); const bytes=await blob.arrayBuffer(); const decoded=await audioContext.decodeAudioData(bytes.slice(0)); state.buffer=decoded; state.duration=decoded.duration; state.playhead=0; state.selectionStart=null; state.selectionEnd=null; q('[data-r="duration"]').textContent=`Длительность: ${formatClock(decoded.duration*1000)}`; showEmpty(false); renderSelection(); redraw(); trace("audio.decode.ready",{duration_ms:Math.round(decoded.duration*1000),channels:decoded.numberOfChannels,sample_rate:decoded.sampleRate},"ready"); };
  const applyBuffer = (buffer,reason) => { state.buffer=buffer; state.duration=buffer.duration; state.playhead=Math.min(state.playhead,state.duration); const blob=audioBufferToWavBlob(buffer); const base=(state.fileName||`bookcraft-${Date.now()}`).replace(/\.[^.]+$/,""); setBlob(blob,`${base}-edited.wav`,"audio/wav"); q('[data-r="duration"]').textContent=`Длительность: ${formatClock(buffer.duration*1000)}`; state.selectionStart=null;state.selectionEnd=null;renderSelection();redraw();setPhase("EDITING",reason); };
  const refreshControls = () => { const recording=state.phase==="RECORDING"; const paused=state.phase==="PAUSED"; const hasAudio=Boolean(state.blob&&state.buffer); const hasSelection=Boolean(selection()); q('[data-action="record"]').disabled=recording||paused; q('[data-action="pause-record"]').disabled=!(recording||paused); q('[data-action="pause-record"]').textContent=paused?"▶ Продолжить":"Ⅱ Пауза"; q('[data-action="stop"]').disabled=!(recording||paused); q('[data-action="play"]').disabled=!hasAudio||recording||paused; q('[data-action="delete-selection"]').disabled=!hasAudio||!hasSelection||recording||paused; q('[data-action="trim-selection"]').disabled=!hasAudio||!hasSelection||recording||paused; q('[data-action="clear-selection"]').disabled=!hasSelection; q('[data-action="undo"]').disabled=!state.undo.length||recording||paused; q('[data-action="redo"]').disabled=!state.redo.length||recording||paused; q('[data-action="download"]').disabled=!state.blob; q('[data-action="clear"]').disabled=!state.blob&&!(recording||paused); q('[data-action="import"]').disabled=recording||paused; q('[data-r="caption"]').textContent=recording?"Идёт запись":paused?"Пауза":hasAudio?"Новая запись":"Начать запись"; q('[data-action="record"]').classList.toggle("recording",recording); };
  const clearAudio = (reason) => { try{if(state.recorder&&state.recorder.state!=="inactive")state.recorder.stop();}catch{} state.stream?.getTracks?.().forEach((track)=>track.stop()); state.stream=null;state.recorder=null;state.chunks=[];state.recordStartedAt=0;state.elapsedBeforePause=0;stopClock();stopVisualizer();revokeUrl();state.buffer=null;state.blob=null;state.fileName="";state.mime="";state.duration=0;state.playhead=0;state.selectionStart=null;state.selectionEnd=null;state.undo=[];state.redo=[];const audio=q('[data-r="preview"]');audio.removeAttribute("src");audio.load();q('[data-r="file-name"]').textContent="Новая запись";q('[data-r="file-meta"]').textContent="микрофон · локально";q('[data-r="duration"]').textContent="Длительность: —";q('[data-r="format"]').textContent="Формат: —";showEmpty(true);renderSelection();redraw();setPhase("EMPTY",reason);trace("audio.clear",{reason},"warn"); };

  const startRecording = async () => { if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){trace("record.error",{code:"api-unavailable"},"error");toast("MediaRecorder / микрофон недоступен.");return;} trace("microphone.request",{}); try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});state.stream=stream;const mime=preferredMime();state.recordMime=mime||"browser-default";const recorder=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream);state.recorder=recorder;state.chunks=[];state.recordStartedAt=Date.now();state.elapsedBeforePause=0;state.undo=[];state.redo=[];state.selectionStart=null;state.selectionEnd=null;showEmpty(false);recorder.ondataavailable=(event)=>{if(event.data?.size)state.chunks.push(event.data);};recorder.onerror=(event)=>trace("record.media-error",{error:event?.error?.message||"MediaRecorder error"},"error");recorder.onstop=async()=>{const elapsed=recordElapsed();stopClock();stopVisualizer();stream.getTracks().forEach((track)=>track.stop());state.stream=null;const finalMime=recorder.mimeType||mime||"audio/webm";const blob=new Blob(state.chunks,{type:finalMime});state.chunks=[];state.recorder=null;state.recordStartedAt=0;state.elapsedBeforePause=elapsed;const ext=finalMime.includes("ogg")?"ogg":finalMime.includes("wav")?"wav":"webm";const name=`bookcraft-${new Date().toISOString().replace(/[:.]/g,"-")}.${ext}`;setBlob(blob,name,finalMime);trace("record.finish",{size_bytes:blob.size,content_type:finalMime,elapsed_ms:elapsed},"ready");try{await decodeBlob(blob,"microphone");setPhase("RECORDED","record-stop");toast("Запись готова. Можно слушать и редактировать.");}catch(error){setPhase("RECORDED","decode-failed");trace("audio.decode.error",{error:error?.message||String(error),content_type:finalMime},"error");toast("Запись сохранена, но браузер не построил редактируемую волну.");}};recorder.start(500);startVisualizer(stream);startClock();setPhase("RECORDING","record-start");trace("microphone.ready",{tracks:stream.getAudioTracks().length,content_type:recorder.mimeType||mime||"unknown"},"ready");}catch(error){trace("microphone.error",{name:error?.name||"Error",error:error?.message||String(error)},"error");toast("Не удалось включить микрофон. Проверьте разрешение браузера.");setPhase(state.blob?"RECORDED":"EMPTY","microphone-error");} };
  const togglePause = () => { const recorder=state.recorder;if(!recorder)return;if(recorder.state==="recording"){state.elapsedBeforePause+=Date.now()-state.recordStartedAt;state.recordStartedAt=0;recorder.pause();stopClock();setPhase("PAUSED","record-pause");trace("record.pause",{elapsed_ms:state.elapsedBeforePause});}else if(recorder.state==="paused"){recorder.resume();state.recordStartedAt=Date.now();startClock();setPhase("RECORDING","record-resume");trace("record.resume",{elapsed_ms:state.elapsedBeforePause});} };
  const stopRecording = () => { if(!state.recorder||state.recorder.state==="inactive")return;if(state.recordStartedAt){state.elapsedBeforePause+=Date.now()-state.recordStartedAt;state.recordStartedAt=0;}trace("record.stop.request",{elapsed_ms:state.elapsedBeforePause});state.recorder.stop(); };
  const pushUndo = () => { if(!audioContext||!state.buffer)return;state.undo.push(cloneAudioBuffer(audioContext,state.buffer));if(state.undo.length>20)state.undo.shift();state.redo=[]; };
  const deleteRange = () => { const range=selection();if(!range||!audioContext||!state.buffer)return;pushUndo();const before=state.duration;const next=cutSelection(audioContext,state.buffer,range.start,range.end);applyBuffer(next,"delete-selection");trace("edit.delete-selection",{start_ms:Math.round(range.start*1000),end_ms:Math.round(range.end*1000),removed_ms:Math.round((range.end-range.start)*1000),duration_before_ms:Math.round(before*1000),duration_after_ms:Math.round(next.duration*1000)},"ready"); };
  const trimRange = () => { const range=selection();if(!range||!audioContext||!state.buffer)return;pushUndo();const before=state.duration;const next=trimToSelection(audioContext,state.buffer,range.start,range.end);applyBuffer(next,"trim-selection");trace("edit.trim-selection",{start_ms:Math.round(range.start*1000),end_ms:Math.round(range.end*1000),duration_before_ms:Math.round(before*1000),duration_after_ms:Math.round(next.duration*1000)},"ready"); };
  const undo = () => { if(!state.undo.length||!audioContext||!state.buffer)return;state.redo.push(cloneAudioBuffer(audioContext,state.buffer));const previous=state.undo.pop();applyBuffer(previous,"undo");trace("edit.undo",{undo_left:state.undo.length,redo_count:state.redo.length},"ready"); };
  const redo = () => { if(!state.redo.length||!audioContext||!state.buffer)return;state.undo.push(cloneAudioBuffer(audioContext,state.buffer));const next=state.redo.pop();applyBuffer(next,"redo");trace("edit.redo",{undo_count:state.undo.length,redo_left:state.redo.length},"ready"); };
  const importAudio = async (file) => { if(!file)return;trace("import.start",{name:file.name,size_bytes:file.size,content_type:file.type||"unknown"});try{setBlob(file,file.name||`import-${Date.now()}`,file.type||"audio");await decodeBlob(file,"import");state.undo=[];state.redo=[];setPhase("RECORDED","import-ready");trace("import.ready",{name:file.name,duration_ms:Math.round(state.duration*1000),size_bytes:file.size},"ready");toast("Аудиофайл загружен.");}catch(error){trace("import.error",{name:file.name,error:error?.message||String(error)},"error");toast("Не удалось декодировать этот аудиофайл.");} };
  const play = async () => { const audio=q('[data-r="preview"]');if(!audio.src)return;if(audio.paused){const range=selection();if(range&&(state.playhead<range.start||state.playhead>range.end))audio.currentTime=range.start;else if(state.playhead>0)audio.currentTime=state.playhead;try{await audio.play();setPhase("PLAYING","preview-play");trace("preview.play",{from_ms:Math.round(audio.currentTime*1000),selection:Boolean(range)});}catch(error){trace("preview.play.error",{error:error?.message||String(error)},"error");}}else audio.pause(); };
  const report = () => { const range=selection();return tracer.buildReport({recorderState:state.phase,runtime:{user_agent:navigator.userAgent,media_recorder:typeof MediaRecorder!=="undefined",audio_context:Boolean(audioContext),get_user_media:Boolean(navigator.mediaDevices?.getUserMedia),record_mime:state.recordMime||null},audio:state.blob?{name:state.fileName,content_type:state.mime,size_bytes:state.blob.size,duration_ms:Math.round(state.duration*1000),channels:state.buffer?.numberOfChannels||null,sample_rate:state.buffer?.sampleRate||null}:null,selection:range?{start_ms:Math.round(range.start*1000),end_ms:Math.round(range.end*1000)}:null}); };
  const copyReport = async () => { const text=JSON.stringify(report(),null,2);try{await navigator.clipboard.writeText(text);trace("report.copy",{characters:text.length},"ready");toast("Отчёт трассировки скопирован. Пришлите его мне.");}catch{const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand?.("copy");area.remove();trace("report.copy.fallback",{characters:text.length},"warn");toast("Отчёт скопирован резервным способом.");} };

  const canvas=q('[data-r="wave"]'); const eventTime=(event)=>{if(!state.duration)return 0;const rect=canvas.getBoundingClientRect();const x=Math.max(0,Math.min(rect.width,event.clientX-rect.left));return x/Math.max(1,rect.width)*state.duration;};
  canvas.addEventListener("pointerdown",(event)=>{if(!state.buffer||state.phase==="RECORDING"||state.phase==="PAUSED")return;canvas.setPointerCapture?.(event.pointerId);state.selecting=true;state.selectionStart=eventTime(event);state.selectionEnd=state.selectionStart;redraw();});
  canvas.addEventListener("pointermove",(event)=>{if(!state.selecting)return;state.selectionEnd=eventTime(event);renderSelection();redraw();});
  canvas.addEventListener("pointerup",(event)=>{if(!state.selecting)return;state.selecting=false;state.selectionEnd=eventTime(event);const range=selection();if(!range){state.playhead=state.selectionEnd||0;const audio=q('[data-r="preview"]');if(Number.isFinite(audio.duration))audio.currentTime=state.playhead;state.selectionStart=null;state.selectionEnd=null;trace("wave.seek",{position_ms:Math.round(state.playhead*1000)});}else trace("wave.selection",{start_ms:Math.round(range.start*1000),end_ms:Math.round(range.end*1000),duration_ms:Math.round((range.end-range.start)*1000)},"ready");renderSelection();redraw();});

  q('[data-action="close"]').addEventListener("click",()=>{if(state.phase==="RECORDING"||state.phase==="PAUSED"){trace("ui.close.blocked",{reason:"recording-active"},"warn");toast("Сначала остановите запись.");return;}page.classList.remove("open");trace("ui.close",{});});
  q('[data-action="record"]').addEventListener("click",startRecording); q('[data-action="pause-record"]').addEventListener("click",togglePause); q('[data-action="stop"]').addEventListener("click",stopRecording); q('[data-action="new"]').addEventListener("click",()=>clearAudio("new-recording")); q('[data-action="play"]').addEventListener("click",play); q('[data-action="delete-selection"]').addEventListener("click",deleteRange); q('[data-action="trim-selection"]').addEventListener("click",trimRange); q('[data-action="undo"]').addEventListener("click",undo); q('[data-action="redo"]').addEventListener("click",redo);
  q('[data-action="clear-selection"]').addEventListener("click",()=>{state.selectionStart=null;state.selectionEnd=null;renderSelection();redraw();trace("wave.selection.clear",{});});
  q('[data-action="import"]').addEventListener("click",()=>{trace("import.dialog.open",{});q('[data-r="file-input"]').click();}); q('[data-r="file-input"]').addEventListener("change",async(event)=>{const file=event.target.files?.[0];event.target.value="";await importAudio(file);});
  q('[data-action="download"]').addEventListener("click",()=>{if(!state.blob||!state.objectUrl)return;const a=document.createElement("a");a.href=state.objectUrl;a.download=state.fileName||`bookcraft-${Date.now()}.wav`;document.body.append(a);a.click();a.remove();trace("audio.download",{name:a.download,size_bytes:state.blob.size},"ready");}); q('[data-action="clear"]').addEventListener("click",()=>clearAudio("delete")); qa('[data-action="copy-report"]').forEach((button)=>button.addEventListener("click",copyReport)); q('[data-action="clear-trace"]').addEventListener("click",()=>tracer.clear(state.phase)); q('[data-action="recognize"]').addEventListener("click",()=>{trace("stt.not-enabled",{stage:2},"warn");toast("Распознавание подключим следующим этапом.");});
  const audio=q('[data-r="preview"]'); audio.addEventListener("play",()=>{if(state.phase!=="PLAYING")setPhase("PLAYING","native-play");}); audio.addEventListener("pause",()=>{state.playhead=Number(audio.currentTime)||0;if(state.blob&&state.phase==="PLAYING")setPhase(state.undo.length?"EDITING":"RECORDED","preview-pause");trace("preview.pause",{at_ms:Math.round(state.playhead*1000)});redraw();}); audio.addEventListener("timeupdate",()=>{state.playhead=Number(audio.currentTime)||0;const range=selection();if(range&&!audio.paused&&state.playhead>=range.end){audio.pause();audio.currentTime=range.start;state.playhead=range.start;trace("preview.selection-end",{end_ms:Math.round(range.end*1000)});}updateClock();redraw();}); audio.addEventListener("ended",()=>{state.playhead=0;setPhase(state.undo.length?"EDITING":"RECORDED","preview-ended");trace("preview.ended",{});redraw();}); audio.addEventListener("seeking",()=>{state.playhead=Number(audio.currentTime)||0;trace("preview.seek",{position_ms:Math.round(state.playhead*1000)});});
  window.addEventListener("resize",()=>{if(state.buffer)redraw();});
  page._recorder={trace,report}; trace("recorder.mount",{media_recorder:typeof MediaRecorder!=="undefined",audio_context:Boolean(audioContext),get_user_media:Boolean(navigator.mediaDevices?.getUserMedia)},"ready"); showEmpty(true); renderSelection(); refreshControls(); traceRender();
}

export function mountRecorderPage() { injectStyles(); const page=buildPage(); if(!page._recorder)makeController(page); }
