import type { LocalModelSpec } from "./types";

export const localModelRegistry: LocalModelSpec[] = [
  {
    id: "MODEL-MINISTRAL-3B-INSTRUCT-Q4",
    displayName: "Ministral 3 3B Instruct Q4_K_M",
    kind: "llm",
    tier: "lite",
    provider: "huggingface",
    repoId: "mistralai/Ministral-3-3B-Instruct-2512-GGUF",
    format: "gguf",
    quantization: "Q4_K_M",
    approximateDownloadGb: 2.15,
    recommendedFor: ["routing", "classification", "light chat", "simple transforms"],
    agentIds: ["AG-002"],
    runtime: "llama.cpp",
    openAiCompatible: true,
    license: "Apache-2.0",
    enabledByDefault: true,
    notes: ["Fast local dispatcher.", "Use for cheap tasks before escalating."],
  },
  {
    id: "MODEL-MINISTRAL-8B-INSTRUCT-Q4",
    displayName: "Ministral 3 8B Instruct Q4_K_M",
    kind: "vision",
    tier: "standard",
    provider: "huggingface",
    repoId: "mistralai/Ministral-3-8B-Instruct-2512-GGUF",
    format: "gguf",
    quantization: "Q4_K_M",
    approximateDownloadGb: 5.2,
    recommendedFor: ["general chat", "creative writing", "persona", "scene", "vision"],
    agentIds: ["AG-004", "AG-005", "AG-006", "AG-007", "AG-008"],
    runtime: "llama.cpp",
    openAiCompatible: true,
    license: "Apache-2.0",
    enabledByDefault: true,
    notes: ["Primary local generalist.", "Vision encoder is available with mmproj."],
  },
  {
    id: "MODEL-MINISTRAL-14B-REASONING-Q4",
    displayName: "Ministral 3 14B Reasoning Q4_K_M",
    kind: "reasoning",
    tier: "standard",
    provider: "huggingface",
    repoId: "mistralai/Ministral-3-14B-Reasoning-2512-GGUF",
    format: "gguf",
    quantization: "Q4_K_M",
    approximateDownloadGb: 8.3,
    recommendedFor: ["prompt engineering", "quality critique", "reasoning", "research synthesis"],
    agentIds: ["AG-001", "AG-003", "AG-009", "AG-010"],
    runtime: "llama.cpp",
    openAiCompatible: true,
    license: "Apache-2.0",
    enabledByDefault: true,
    notes: ["Primary local reasoning model.", "Escalation target for difficult tasks."],
  },
  {
    id: "MODEL-QWEN3-EMBED-06B",
    displayName: "Qwen3 Embedding 0.6B",
    kind: "embedding",
    tier: "lite",
    provider: "huggingface",
    repoId: "Qwen/Qwen3-Embedding-0.6B",
    format: "safetensors",
    approximateDownloadGb: 1.3,
    recommendedFor: ["multilingual retrieval", "RAG", "code retrieval"],
    agentIds: ["AG-001"],
    runtime: "sentence-transformers",
    openAiCompatible: false,
    license: "Apache-2.0",
    enabledByDefault: true,
    notes: ["Default embedding model for local RAG."],
  },
  {
    id: "MODEL-QWEN3-RERANK-06B",
    displayName: "Qwen3 Reranker 0.6B",
    kind: "reranker",
    tier: "lite",
    provider: "huggingface",
    repoId: "Qwen/Qwen3-Reranker-0.6B",
    format: "safetensors",
    approximateDownloadGb: 1.21,
    recommendedFor: ["RAG reranking", "multilingual relevance scoring"],
    agentIds: ["AG-001", "AG-009"],
    runtime: "sentence-transformers",
    openAiCompatible: false,
    license: "Apache-2.0",
    enabledByDefault: true,
    notes: ["Rerank top-k after embedding retrieval."],
  },
  {
    id: "MODEL-QWEN3-EMBED-4B",
    displayName: "Qwen3 Embedding 4B",
    kind: "embedding",
    tier: "heavy",
    provider: "huggingface",
    repoId: "Qwen/Qwen3-Embedding-4B",
    format: "safetensors",
    recommendedFor: ["high-quality multilingual retrieval", "code retrieval"],
    agentIds: ["AG-001"],
    runtime: "sentence-transformers",
    openAiCompatible: false,
    license: "Apache-2.0",
    enabledByDefault: false,
    notes: ["Quality upgrade over 0.6B after benchmark."],
  },
  {
    id: "MODEL-QWEN3-CODER-30B-A3B",
    displayName: "Qwen3 Coder 30B A3B Instruct",
    kind: "coder",
    tier: "heavy",
    provider: "huggingface",
    repoId: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    format: "safetensors",
    recommendedFor: ["repository coding", "agentic coding", "large-context code review"],
    agentIds: ["AG-003", "AG-009"],
    runtime: "transformers",
    openAiCompatible: true,
    license: "Apache-2.0",
    enabledByDefault: false,
    notes: ["Optional heavy coder.", "30B total parameters, 3B active MoE."],
  },
];

export function modelsForAgent(agentId: string) {
  return localModelRegistry.filter((model) => model.agentIds.includes(agentId));
}

export function modelsForTier(tier: "lite" | "standard" | "heavy") {
  const order = { lite: 0, standard: 1, heavy: 2 } as const;
  return localModelRegistry.filter((model) => order[model.tier] <= order[tier]);
}
