import {mountVoice} from './voice.mjs';
import {profiles,channels,money,seedProfile,newSession,optionsFor,advance,metrics,seedPersonalHistory,summarizeSession} from './core.mjs';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',chat:'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2v-10a9.5 9.5 0 0 1 19-.5Z"/><path d="M7 8h9M7 12h6"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6M21 21v-3a6 6 0 0 0-3-5"/>',pipeline:'<rect x="3" y="4" width="5" height="16" rx="1"/><rect x="10" y="4" width="5" height="10" rx="1"/><rect x="17" y="4" width="4" height="13" rx="1"/>',box:'<path d="m12 3 9 5v9l-9 5-9-5V8l9-5Zm0 10 9-5M12 13 3 8m9 5v9M7 5.8l10 5.5"/>',spark:'<path d="m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3Z"/>',flow:'<rect x="9" y="2" width="6" height="5" rx="1"/><rect x="2" y="17" width="6" height="5" rx="1"/><rect x="16" y="17" width="6" height="5" rx="1"/><path d="M12 7v5M5 17v-5h14v5"/>',plug:'<path d="m8 3 0 5m8-5v5M6 8h12v3a6 6 0 0 1-12 0V8m6 9v5"/>',bag:'<rect x="4" y="7" width="16" height="14" rx="2"/><path d="M8 7V5a4 4 0 0 1 8 0v2"/>',heart:'<path d="M20 5a5 5 0 0 0-8 1 5 5 0 0 0-8 6l8 9 8-9a5 5 0 0 0 0-7Z"/><path d="M6 12h3l2-3 2 6 2-3h3"/>',activity:'<path d="M2 12h5l3-8 4 16 3-8h5"/>',tool:'<path d="M14 6a5 5 0 0 0-6 6L2 18l4 4 6-6a5 5 0 0 0 6-6l-4 3-3-3 3-4Z"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 11h18"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M3 15v6h18v-6"/>',phone:'<path d="m5 3 4 4-2 3a17 17 0 0 0 7 7l3-2 4 4-2 3C9 22 2 15 2 5l3-2Z"/>',mail:'<rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 5 10 8L22 5"/>',send:'<path d="m22 2-7 20-4-9-9-4L22 2Zm0 0L11 13"/>',check:'<path d="m4 12 5 5L20 6"/>',chart:'<path d="M3 3v18h18M7 15l4-5 4 3 6-8"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.spark}</svg>`;
const initials=s=>s.split(/\s+/).slice(0,2).map(s=>s[0]).join('');
const fmt=iso=>new Date(iso).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const storageKey='bookcraft.one.mvp.v2';
let db;try{db=JSON.parse(localStorage.getItem(storageKey));if(db?.version!==2||!db.profiles||!profiles[db.active])throw Error();for(const id of Object.keys(profiles)){const d=db.profiles[id];if(!d||!Array.isArray(d.records)||!Array.isArray(d.clients)||!Array.isArray(d.sessions)||!Array.isArray(d.history)||!d.settings||!d.stock)throw Error();}}catch{db={version:2,active:'sales',profiles:Object.fromEntries(Object.keys(profiles).map(id=>[id,seedProfile(id)]))};}
for(const id of Object.keys(profiles))seedPersonalHistory(id,db.profiles[id]);
let profileId=db.active,page='dashboard',period=30,selectedSession=null,chat=null,pending=null,toastTimer,search='',selectedHistory=null;
const data=()=>db.profiles[profileId],profile=()=>profiles[profileId];
function save(){try{localStorage.setItem(storageKey,JSON.stringify(db));}catch{toast('Хранилище браузера недоступно. Данные останутся только до закрытия страницы.');}}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4000);}
function download(filename,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportRecords(){const header=['ID','Клиент','Контакт','Позиция','Сумма','Статус','Канал'];const rows=[header,...metrics(data(),period).records.map(r=>[r.id,r.client,r.contact,r.item,r.amount,profile().stages[r.stage],r.channel])];const cell=v=>`"${String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')}"`;download(`bookcraft-${profileId}.csv`,'\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
const navItems=()=>[['dashboard','dashboard','Обзор'],['dialogs','chat','Диалоги'],['pipeline','pipeline',profile().entity],['personal','clock','Мои обращения'],['clients','users',profile().people],['catalog','box',profile().resource]];
const botItems=[['scenarios','flow','Сценарии бота'],['integrations','plug','Каналы и интеграции']];
const titles=()=>Object.fromEntries([...navItems(),...botItems].map(([id,_,title])=>[id,title]));
function renderShell(){
 document.documentElement.style.setProperty('--accent',profile().accent);
 $('#workspace-icon').innerHTML=icon(profile().icon);$('#workspace-name').textContent=profile().company;$('#crumb-profile').textContent=profile().short;$('#crumb-page').textContent=search?'Поиск':titles()[page];
 const nav=(items)=>items.map(([id,i,label])=>`<button class="nav-button ${page===id&&!search?'active':''}" data-page="${id}" title="${esc(label)}">${icon(i)}<span>${esc(label)}</span>${id==='dialogs'?`<b>${data().sessions.length}</b>`:''}${id==='scenarios'?'<span class="nav-dot"></span>':''}</button>`).join('');
 $('#nav').innerHTML=nav(navItems());$('#bot-nav').innerHTML=nav(botItems);$('#search-icon').innerHTML=icon('search');
 $('#profile-grid').innerHTML=Object.entries(profiles).map(([id,p])=>`<button class="profile-option ${id===profileId?'active':''}" data-profile="${id}" style="--profile-color:${p.accent}"><span>${icon(p.icon)}</span><strong>${p.name}</strong><p>${p.subtitle}</p><small>${id===profileId?'✓ Текущее пространство':'Открыть профиль →'}</small></button>`).join('');
}
function heading(title,description,actions=true){return `<div class="page-heading"><div><h1>${title}</h1><p>${description}</p></div>${actions?`<div class="heading-actions"><select class="period" id="period" aria-label="Период отчёта"><option value="7" ${period===7?'selected':''}>Последние 7 дней</option><option value="30" ${period===30?'selected':''}>Последние 30 дней</option></select><button class="primary" data-open-bot>${icon('spark')} Тестировать бота</button></div>`:''}</div>`;}
function profileStrip(){return `<div class="profile-strip">${Object.entries(profiles).map(([id,p])=>`<button class="profile-pill ${id===profileId?'active':''}" data-profile="${id}">${icon(p.icon)}${p.short}</button>`).join('')}</div>`;}
function recordTable(records,limit=Infinity){return `<div class="table-scroll"><table><thead><tr><th>${profile().people==='Пациенты'?'Пациент':'Клиент'}</th><th>${profile().entity}</th><th>Сумма</th><th>Статус</th><th>Канал</th><th></th></tr></thead><tbody>${records.slice(0,limit).map(r=>`<tr><td><div class="table-person"><span class="avatar">${esc(initials(r.client))}</span><div><strong>${esc(r.client)}</strong><small>${esc(r.id)}</small></div></div></td><td>${esc(r.item)}<small>${esc(r.slot)}</small></td><td><strong>${money(r.amount)}</strong></td><td><span class="tag ${['orange','blue','','green'][r.stage]}">${profile().stages[r.stage]}</span></td><td>${esc(r.channel)}</td><td><button class="text-button" data-record="${esc(r.id)}" aria-label="Открыть заявку ${esc(r.id)}">↗</button></td></tr>`).join('')}</tbody></table>${records.length?'':'<div class="empty">В этом периоде заявок нет.</div>'}</div>`;}
function dashboard(){
 const p=profile(),d=data(),m=metrics(d,period),now=Date.now(),bins=Array.from({length:7},(_,i)=>({start:now-period*86400000+(period/7)*86400000*i,count:0}));
 for(const r of m.records){let ix=Math.min(6,Math.max(0,Math.floor((Date.parse(r.created)-(now-period*86400000))/(period/7*86400000))));bins[ix].count++;}
 const max=Math.max(1,...bins.map(b=>b.count)),colors=['#9680cc','#b8a6dc','#d8c9e9','#e8dff2'];let deg=0;
 const gradient=m.byChannel.map((c,i)=>{const start=deg;deg+=m.records.length?c.count/m.records.length*360:90;return `${colors[i]} ${start}deg ${deg}deg`;}).join(',');
 const recent=[...m.records].sort((a,b)=>b.created.localeCompare(a.created));
 return heading('Ваш бизнес <span>под контролем</span>',`${p.company} · ${p.subtitle}`)+profileStrip()+`<div class="kpis">${[[p.entity,m.records.length,'bag','За выбранный период'],['Сумма заявок',money(m.sum),'chart','Не является оплаченной выручкой'],['Завершено',m.completed,'check',`${m.conversion}% от всех заявок периода`],['Требуют внимания',d.sessions.filter(s=>s.step==='human').length,'chat','Переданы специалисту']].map(([l,v,i,n])=>`<div class="kpi"><div class="kpi-top">${l}<span class="metric-icon">${icon(i)}</span></div><strong>${v}</strong><p><span>●</span>${n}</p></div>`).join('')}</div>
 <div class="dashboard-grid"><section class="card"><div class="card-head"><div><h2>Динамика заявок</h2><p>Все каналы · ${period} дней</p></div><span class="chart-legend"><i></i> Созданные заявки</span></div><div class="chart-area"><div class="bar-chart" role="img" aria-label="Количество заявок по семи интервалам: ${bins.map(b=>b.count).join(', ')}">${bins.map(b=>`<div class="bar-group"><div class="bar" style="height:${Math.max(b.count?8:0,b.count/max*95)}%" data-label="${b.count} заявок"></div></div>`).join('')}</div><div class="chart-labels">${bins.map(b=>`<span>${new Date(b.start).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'})}</span>`).join('')}</div></div><div class="chart-summary"><span><strong>${m.records.length}</strong> всего</span><span><strong>${m.completed}</strong> завершено</span><span><strong>${m.conversion}%</strong> доля завершённых</span></div></section>
 <section class="card bot-card"><div class="card-head"><div><h2>Универсальный бот</h2><p>Единое ядро · профиль «${p.short}»</p></div><span class="bot-status">Симулятор</span></div><div class="bot-core"><div class="secretary-card-row"><div class="secretary-portrait small-portrait" role="img" aria-label="Алина, виртуальный секретарь"></div><div><span class="secretary-name">Алина</span><span class="secretary-role">Ваш виртуальный секретарь</span></div></div><h3>На связи с вашими клиентами.</h3><p>${p.goal}. Сохраняет контекст и передаёт задачу вашей команде.</p><div class="flow-mini"><span>Сообщение</span>→<span>Сценарий</span>→<span>Действие</span></div><button data-open-bot>Попробовать диалог <span>↗</span></button></div></section>
 <section class="card"><div class="card-head"><div><h2>Откуда приходят клиенты</h2><p>Демонстрационное распределение заявок</p></div><button class="text-button" data-page="integrations">Все каналы ↗</button></div><div class="channel-body"><div class="donut" style="background:conic-gradient(${gradient})"><div class="donut-center"><strong>${m.records.length}</strong><span>заявок</span></div></div><div class="channel-list">${m.byChannel.map((c,i)=>`<div class="channel-row"><i style="background:${colors[i]}"></i>${c.name}<b>${c.count}</b><small>${m.records.length?Math.round(c.count/m.records.length*100):0}%</small></div>`).join('')}</div></div></section>
 <section class="card"><div class="card-head"><div><h2>Последние события</h2><p>Действия в вашем пространстве</p></div><button class="text-button" data-page="pipeline">Смотреть все ↗</button></div><div class="activity-list">${recent.slice(0,4).map(r=>`<div class="activity-row"><span class="avatar">${esc(initials(r.client))}</span><div><strong>${esc(r.client)}</strong><p>${esc(r.source==='bot'?'Бот создал заявку':p.stages[r.stage])} <span class="tiny-channel">· ${esc(r.channel)}</span></p></div><time>${new Date(r.created).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'})}</time></div>`).join('')}</div></section>
 <section class="card wide"><div class="card-head table-head"><div><h2>${p.entity}</h2><p>Последние заявки и их текущий статус</p></div><button class="text-button" data-page="pipeline">Открыть воронку →</button></div>${recordTable(recent,5)}<div class="table-foot">Показано ${Math.min(5,recent.length)} из ${recent.length} · Демо-данные, реальные каналы не подключены</div></section></div>`;
}
function pipeline(){const p=profile(),m=metrics(data(),period);return heading(p.entity,'Воронка процесса. Меняйте этап карточки — показатели обновятся автоматически.')+`<div class="toolbar"><span class="tag">${m.records.length} заявок</span><span class="tag">${money(m.sum)}</span><button id="export-csv" class="secondary">${icon('download')} Экспорт CSV</button><span class="muted">Данные только текущего профиля</span></div><div class="kanban">${p.stages.map((s,i)=>`<section class="kanban-column"><div class="kanban-title"><strong>${s}</strong><span>${m.byStage[i]}</span></div>${m.records.filter(r=>r.stage===i).sort((a,b)=>b.created.localeCompare(a.created)).map(r=>`<article class="deal"><strong>${esc(r.item)}</strong><p>${esc(r.client)}</p><div class="deal-value">${money(r.amount)}</div><div class="deal-bottom"><span>${esc(r.channel)}</span><button class="text-button" data-record="${r.id}">Открыть ↗</button></div><select data-stage="${r.id}" aria-label="Этап заявки ${r.id}">${p.stages.map((label,n)=>`<option value="${n}" ${r.stage===n?'selected':''}>${label}</option>`).join('')}</select></article>`).join('')}</section>`).join('')}</div>`;}
function clients(){const d=data();return heading(profile().people,'Единая карточка: контакт, заявки и история взаимодействий.')+`<section class="card"><div class="card-head table-head"><h2>${d.clients.length} контактов</h2><span class="muted">Контакты в примерах вымышлены</span></div><div class="table-scroll"><table><thead><tr><th>Имя</th><th>Контакт</th><th>Заявок</th><th>Сумма</th><th></th></tr></thead><tbody>${d.clients.map(c=>{const rs=d.records.filter(r=>r.clientId===c.id);return `<tr><td><div class="table-person"><span class="avatar">${esc(initials(c.name))}</span><strong>${esc(c.name)}</strong></div></td><td>${esc(c.contact)}</td><td>${rs.length}</td><td>${money(rs.reduce((n,r)=>n+r.amount,0))}</td><td><button class="text-button" data-client="${c.id}">История клиента ↗</button></td></tr>`;}).join('')}</tbody></table></div></section>`;}
function catalog(){const p=profile(),stock=p.catalog[0].stock!==undefined;return heading(p.resource,stock?'Каталог и доступные остатки. Подтверждённая заявка бота резервирует товар.':'Каталог услуг и примеры времени. Каждая запись требует согласования администратора.')+`<div class="resource-grid">${p.catalog.map(i=>`<section class="card resource"><div class="resource-icon">${icon(p.icon)}</div><h2>${i.name}</h2><p>${stock?'Товар для оформления заказа':'Услуга для записи через бота'}</p><div class="price">${money(i.price)}</div>${stock?`<div class="stock-bar"><span style="width:${Math.max(0,Math.min(100,data().stock[i.id]/i.stock*100))}%"></span></div><span class="tag green">Доступно: ${data().stock[i.id]} шт.</span><p>Тестовые остатки текущего профиля</p>`:`<div class="slots">${i.slots.map(s=>`<span class="tag">${s}</span>`).join('')}</div><p>Пример расписания, не живая доступность</p>`}<button class="primary" data-catalog-bot="${i.id}">Выбрать в диалоге ${icon('arrow')}</button></section>`).join('')}</div><div class="notice-line" style="margin-top:22px">${icon('box')} ${stock?'ERP и реальный склад ещё не подключены. Остатки сохраняются локально.':'Интеграция с календарём ещё не подключена. Бот создаёт заявку, а не бронирует реальный слот.'}</div>`;}
function scenarios(){const d=data(),p=profile();return heading('Сценарии бота','Общие шаги общения. Настройки и каталог меняются вместе с профилем бизнеса.')+`<div class="scenario-layout"><section class="card scenario-main"><h2 style="font-size:15px">${esc(d.settings.goal)}</h2><p class="muted">Профиль: ${p.name}</p><div class="scenario-flow">${[['Определить намерение','Новая заявка, история или помощь человека'],['Выбрать товар или услугу','Только варианты из каталога текущего бизнеса'],[p.catalog[0].stock!==undefined?'Проверить количество':'Выбрать время',p.catalog[0].stock!==undefined?'Проверка доступного остатка':'Заявка на время с подтверждением администратора'],['Уточнить контакт','Связать обращение с существующим клиентом'],['Получить подтверждение','Показать позицию, сумму и детали'],['Создать заявку в CRM','Сохранить диалог и назначить ответственного']].map(([t,s],i)=>`<div class="flow-step"><span class="number">${String(i+1).padStart(2,'0')}</span><div><strong>${t}</strong><p>${s}</p></div></div>`).join('')}</div></section><section class="card scenario-editor"><h2 style="font-size:15px">Настройки общения</h2><form id="scenario-form"><label for="greeting">Приветствие</label><textarea id="greeting" maxlength="1200" required>${esc(d.settings.greeting)}</textarea><label for="goal">Цель сценария</label><textarea id="goal" maxlength="400" required>${esc(d.settings.goal)}</textarea><button class="primary" type="submit">Сохранить настройки</button></form><div class="rules"><strong>Правила ядра</strong><br>Не создавать заявку без подтверждения.<br>Не выдумывать цены и остатки.<br>Позволять сменить выбор или обратиться к человеку.<br>Сохранять ввод при ошибке.<br>${p.id==='medical'||profileId==='medical'||profileId==='massage'?'Не давать медицинских рекомендаций.':'Сохранять контекст в истории клиента.'}</div><p class="muted">Настройки применятся к новому диалогу. Это сценарный движок; LLM пока не подключена.</p></section></div>`;}
const integrations=[['Telegram','send','Текст, голосовые сообщения, файлы.','Нужны токен бота, защищённый сервер и обработчик входящих событий.'],['Телефония','phone','Живой разговор и запись автоответчика.','Нужны провайдер телефонии, потоковое распознавание речи и синтез голоса.'],['Электронная почта','mail','Письма и вложения в общей истории.','Нужны подключение почтового ящика и правила обработки входящих писем.'],['Чат на сайте','chat','Виджет бота для посетителей сайта.','Сейчас доступен локальный симулятор. Для публикации нужен сервер и виджет.'],['LLM и распознавание','spark','Понимание свободной речи и аудио.','Локальный Whisper подключён к голосовому вводу. Для LLM нужен отдельный серверный адаптер.'],['CRM / ERP / календарь','plug','Заказы, остатки и расписание организации.','Нужны API системы, права доступа и соответствие полей данных.']];
function integrationPage(){return heading('Каналы и интеграции','Одна история общения независимо от точки входа.')+`<div class="notice-line">${icon('plug')} Телефония и почта пока не подключены. Состояние отдельного Telegram-бота проверяется ниже.</div><section class="card telegram-message"><h2>Настоящий Telegram-бот</h2><p>Принимает голосовые и аудиофайлы, распознаёт Whisper и отвечает по сценарию. Нужна локальная настройка отдельного бота.</p><button id="refresh-telegram">Проверить подключение и входящие</button><div id="telegram-inbox"></div></section><div class="integration-grid">${integrations.map(([n,i,t],ix)=>`<section class="card integration"><div class="integration-icon">${icon(i)}</div><h2>${n}</h2><p>${t}</p><span class="tag grey">${ix===0?'Настроить отдельно':ix===4?'Whisper локально · без LLM':'Не подключено'}</span><br><button data-integration="${ix}">Что нужно для подключения ↗</button></section>`).join('')}</div>`;}
const stepLabel=s=>({intent:'Начало',item:'Выбор',quantity:'Количество',slot:'Время',name:'Имя',contact:'Контакт',confirm:'Подтверждение',done:'Заявка создана',human:'Нужен специалист','history-contact':'Проверка контакта','history-result':'История'})[s]||s;
function dialogs(){const d=data(),s=d.sessions.find(s=>s.id===selectedSession)||d.sessions[0];if(s)selectedSession=s.id;return heading('Диалоги и обращения','Сообщение → сценарий → уточнение → действие. История сохраняется в текущем профиле.')+`<section class="card session-grid"><div class="session-list">${d.sessions.length?d.sessions.map(s=>`<button class="session-button ${s.id===selectedSession?'active':''}" data-session="${s.id}"><strong>${esc(s.name||'Посетитель')} <span class="tag">${esc(s.channel)}</span></strong><p>${esc(s.messages.filter(m=>m.role==='user').at(-1)?.text||'Новый диалог')}</p><span class="tag ${s.step==='human'?'orange':s.step==='done'?'green':'grey'}">${stepLabel(s.step)}</span></button>`).join(''):'<div class="empty"><span class="empty-icon">☏</span>Диалогов пока нет.<br>Запустите тест бота.</div>'}</div><div class="session-content">${s?`<div class="section-title"><strong>${esc(s.name||'Тестовый диалог')}</strong></div><p class="session-status">${fmt(s.created)} · ${esc(s.channel)} · ${stepLabel(s.step)} ${s.example?'· Учебный пример':''}</p><div class="transcript">${s.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':''}">${esc(m.text)}</div>`).join('')}</div><div class="toolbar" style="margin-top:20px"><button data-resume="${s.id}" class="primary">Открыть диалог</button><button data-analyze-session="${s.id}">Сохранить разбор</button>${s.recordId?`<button data-record="${s.recordId}">Заявка ↗</button>`:''}</div>`:'<div class="empty">Проверьте, как бот выбирает сценарий,<br>собирает данные и создаёт заявку.</div>'}</div></section><h2 class="section-heading">История анализов</h2><p class="muted">Последние три разбора диалога. Открытие не запускает повторную обработку.</p><div class="history-cards">${d.history.length?d.history.map(h=>`<button class="history-entry ${selectedHistory===h.id?'active':''}" data-history="${h.id}"><small>✓ Готово · ${fmt(h.created)}</small><strong>${esc(h.title)}</strong><p>Открыть сохранённый результат →</p></button>`).join(''):'<p class="muted">Сохраните разбор любого диалога — он появится здесь.</p>'}</div>`;}
function personal(){const d=data(),p=profile(),sessions=d.sessions.filter(s=>s.example||s.contact?.toLowerCase()==='viktor@example.test'),records=d.records.filter(r=>r.contact.toLowerCase()==='viktor@example.test');return heading('Мои обращения',`Виктор · ${p.company} · отдельная история текущего сервиса`)+`<div class="notice-line">${icon('clock')} Три учебных обращения: телефон, Telegram и email. Это примеры для проверки ДЗ, не ваши реальные записи или заказы.</div><div class="resource-grid">${sessions.map(s=>`<section class="card resource"><div class="resource-icon">${icon(s.channel==='Телефон'?'phone':s.channel==='Email'?'mail':'send')}</div><h2>${esc(p.catalog.find(i=>i.id===s.itemId)?.name||'Новое обращение')}</h2><p>${fmt(s.created)} · ${esc(s.channel)}</p><span class="tag ${s.step==='done'?'green':'orange'}">${stepLabel(s.step)}</span><p>${esc(s.name||'Виктор')} · ${esc(s.contact||'Контакт не указан')}</p><button class="primary" data-personal-session="${s.id}">Посмотреть разговор ↗</button><button data-analyze-session="${s.id}">Сохранить разбор в историю</button></section>`).join('')}</div><h2 class="section-heading">Заявки и записи</h2><section class="card">${recordTable(records)}</section><h2 class="section-heading">История анализов · ${d.history.length} / 3</h2><p class="muted">Нажмите карточку, чтобы открыть именно сохранённый результат.</p><div class="history-cards">${d.history.map(h=>`<button class="history-entry" data-history="${h.id}"><small>✓ Готово · ${fmt(h.created)}</small><strong>${esc(h.title)}</strong><p>Открыть результат →</p></button>`).join('')}</div>`;}
function searchPage(){const q=search.trim().toLowerCase(),d=data(),rs=d.records.filter(r=>[r.id,r.client,r.contact,r.item].join(' ').toLowerCase().includes(q));return heading('Поиск в пространстве',`Профиль «${profile().short}» · запрос: ${esc(search)}`,false)+`<section class="card">${recordTable(rs)}</section>`;}
function render(){renderShell();$('#page').innerHTML=search?searchPage():({dashboard,pipeline,clients,catalog,scenarios,personal,integrations:integrationPage,dialogs}[page]||dashboard)();bindPage();}
function navigate(target){if(!titles()[target])return;page=target;search='';$('#search').value='';history.replaceState(null,'',`#${page}`);render();window.scrollTo({top:0,behavior:'smooth'});}
function changeProfile(id){if(!profiles[id])return;window.dispatchEvent(new Event('crm:context-changed'));stopVoice();cancelPending();profileId=id;db.active=id;chat=null;selectedSession=null;selectedHistory=null;search='';$('#search').value='';save();$('#profile-dialog').close();$('#bot-dialog').close();render();}
function info(title,body){$('#info-title').textContent=title;$('#info-body').innerHTML=body;$('#info-dialog').showModal();}
function openRecord(id){const r=data().records.find(r=>r.id===id);if(!r)return;info(`Заявка ${r.id}`,`<div class="detail-kv"><div><small>Клиент</small>${esc(r.client)}<br>${esc(r.contact)}</div><div><small>Позиция и сумма</small>${esc(r.item)} × ${r.quantity}<br>${money(r.amount)}</div><div><small>Детали</small>${esc(r.slot)}<br>${esc(r.channel)}</div><div><small>Ответственный</small>${esc(r.owner)}<br>${profile().stages[r.stage]}</div></div><p class="info-note">${r.source==='bot'?'Создана в тестовом диалоге бота.':'Демонстрационная заявка.'} Реальная оплата и внешняя запись не выполнялись.</p><div class="actions"><button data-client="${r.clientId}">Вся история клиента</button></div>`);}
function openClient(id){const c=data().clients.find(c=>c.id===id);if(!c)return;const records=data().records.filter(r=>r.clientId===id);info(c.name,`<p class="info-note">${esc(c.contact)} · ${records.length} заявок · ${money(records.reduce((n,r)=>n+r.amount,0))}</p>${recordTable(records)}<p class="info-note">В демо клиент определяется по точному контакту. Для работы с реальными каналами нужна проверка личности и подтверждение связи контактов.</p>`);}
function persistChat(){const sessions=db.profiles[chat.profile].sessions,index=sessions.findIndex(s=>s.id===chat.id);if(index>=0)sessions[index]=structuredClone(chat);else sessions.unshift(structuredClone(chat));save();}
function openBot(existing=null,itemId=null){window.dispatchEvent(new Event('crm:context-changed'));stopVoice();cancelPending();chat=existing?structuredClone(existing):newSession(profileId,$('#chat-channel').value,data().settings.greeting);if(!existing){persistChat();if(itemId){chat=advance(chat,'new',data()).session;chat=advance(chat,itemId,data()).session;persistChat();}}$('#bot-subtitle').textContent=profile().company;$('#chat-channel').value=chat.channel;$('#chat-input').value='';$('#chat-status').textContent='';$('#simulate-failure').checked=false;renderChat();$('#bot-dialog').showModal();if(existing)$('#chat-input').focus();else ($('#mic-start')||$('#chat-input')).focus();render();}
function renderChat(){if(!chat)return;$('#chat-messages').innerHTML=chat.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':''}">${esc(m.text)}</div>`).join('');$('#chat-options').innerHTML=optionsFor(chat).map(o=>`<button data-chat-option="${esc(o.value)}" ${pending?'disabled':''}>${esc(o.label)}</button>`).join('');$('#chat-step').textContent=stepLabel(chat.step);$('#chat-channel').disabled=chat.messages.length>1||!!pending;$('#send-chat').disabled=!!pending;$('#chat-input').disabled=!!pending;$('#cancel-chat').hidden=!pending;$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;}
function cancelPending(){if(pending){clearTimeout(pending.timer);pending=null;$('#chat-status').textContent='Отменено. Сообщение сохранено в поле ввода.';renderChat();}}
function send(text){if(pending||!chat)return;const input=text.trim();if(!input){$('#chat-status').textContent='Введите сообщение или выберите вариант.';return;}const sessionId=chat.id,pid=profileId;$('#chat-input').value=input;$('#chat-status').textContent='Обрабатываю… Демонстрационная задержка.';const fail=$('#simulate-failure').checked;
 pending={timer:setTimeout(()=>{pending=null;if(!chat||chat.id!==sessionId||profileId!==pid)return;if(fail){$('#chat-status').textContent='Сервис недоступен (имитация). Текст сохранён. Снимите флажок и повторите.';renderChat();return;}
 const result=advance(chat,input,data());chat=result.session;
 if(result.record&&!data().records.some(r=>r.id===result.record.id)){if(result.client)data().clients.push(result.client);data().records.unshift(result.record);if(data().stock[result.record.itemId]!==undefined)data().stock[result.record.itemId]-=result.record.quantity;}
 persistChat();if($('#voice-enabled').checked)speak(chat.messages.filter(m=>m.role==='bot').at(-1)?.text);$('#chat-input').value='';$('#chat-status').textContent=result.record?'Заявка создана в CRM.':'';renderChat();render();if(result.record)toast('Бот создал заявку. Она появилась в воронке и карточке клиента.');
 },700)};renderChat();
}
function analyzeSession(id){const s=data().sessions.find(s=>s.id===id);if(!s)return;const summary=summarizeSession(s,data());const h={id:crypto.randomUUID(),title:`${s.name||'Диалог'} · ${s.channel}`,created:new Date().toISOString(),sessionId:s.id,text:summary};data().history=[h,...data().history].slice(0,3);save();render();toast('Разбор сохранён в историю');}
function bindPage(){if($('#refresh-telegram'))$('#refresh-telegram').onclick=refreshTelegram;if($('#period'))$('#period').onchange=e=>{period=Number(e.target.value);render();};if($('#export-csv'))$('#export-csv').onclick=exportRecords;if($('#scenario-form'))$('#scenario-form').onsubmit=e=>{e.preventDefault();const greeting=$('#greeting').value.trim(),goal=$('#goal').value.trim();if(!greeting||!goal){toast('Заполните приветствие и цель сценария');return;}data().settings={greeting,goal};save();toast('Настройки сохранены. Они применятся в новом диалоге.');render();};}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page)navigate(b.dataset.page);if(b.dataset.profile)changeProfile(b.dataset.profile);if(b.dataset.close){if(b.dataset.close==='bot-dialog'){window.dispatchEvent(new Event('crm:context-changed'));stopVoice();cancelPending();}$(`#${b.dataset.close}`).close();}if(b.hasAttribute('data-open-bot'))openBot();if(b.dataset.catalogBot)openBot(null,b.dataset.catalogBot);if(b.dataset.record)openRecord(b.dataset.record);if(b.dataset.client)openClient(b.dataset.client);if(b.hasAttribute('data-integration')){const [n,_,t,requirements]=integrations[Number(b.dataset.integration)];info(n,`<p class="info-note">${t}</p><p class="info-note">${requirements}</p><span class="tag grey">Не подключено</span><p class="info-note">Здесь показана точка расширения ядра. Для настройки реальной интеграции потребуется серверный модуль.</p>`);}if(b.dataset.chatOption)send(b.dataset.chatOption);if(b.dataset.personalSession){selectedSession=b.dataset.personalSession;navigate('dialogs');}if(b.dataset.session){selectedSession=b.dataset.session;render();}if(b.dataset.resume)openBot(data().sessions.find(s=>s.id===b.dataset.resume));if(b.dataset.analyzeSession)analyzeSession(b.dataset.analyzeSession);if(b.dataset.history){const h=data().history.find(h=>h.id===b.dataset.history);selectedHistory=h.id;info('Результат анализа · Готово',`<p class="info-note">${esc(h.title)} · ${fmt(h.created)}</p><pre class="result-text">${esc(h.text)}</pre><button data-download-history="${h.id}">Скачать TXT</button>`);}if(b.dataset.downloadHistory){const h=data().history.find(h=>h.id===b.dataset.downloadHistory);download('analysis.txt',h.text);}});
document.addEventListener('change',e=>{if(e.target.dataset.stage){const r=data().records.find(r=>r.id===e.target.dataset.stage);r.stage=Number(e.target.value);save();render();toast('Этап заявки обновлён');}});
$('#workspace').onclick=$('#show-profiles').onclick=()=>$('#profile-dialog').showModal();
$('#new-chat').onclick=()=>openBot();$('#chat-channel').onchange=e=>{if(chat&&chat.messages.length===1){chat.channel=e.target.value;persistChat();}};
$('#chat-form').onsubmit=e=>{e.preventDefault();send($('#chat-input').value);};$('#cancel-chat').onclick=cancelPending;$('#bot-dialog').addEventListener('cancel',()=>{window.dispatchEvent(new Event('crm:context-changed'));stopVoice();cancelPending();});
$('#search').oninput=e=>{search=e.target.value;render();};
$('#help').onclick=()=>info('BOOKCRAFT ONE · Универсальное ядро',`<p class="info-note">Шесть профилей бизнеса: продажи, клиника, спорткомплекс, автосервис, массаж и склад. Общий сценарный движок собирает данные, получает подтверждение и создаёт локальную заявку.</p><p class="info-note">Работают дашборд, воронка, каталог, история клиентов, тестовый диалог, настройки сценария и история трёх разборов. Данные сохраняются только в текущем браузере.</p><p class="info-note">Распознавание работает через локальный Whisper; Telegram требует отдельной настройки. LLM, телефония, реальная запись и многопользовательская база пока не подключены. Текущий движок демонстрирует шаги и переключение сценариев.</p><div class="actions"><button data-page="scenarios" data-close="info-dialog">Сценарии бота</button><a class="secondary" href="./inbox.html" target="_blank">Открыть предыдущую заготовку обращений ↗</a></div>`);
window.addEventListener('hashchange',()=>{const target=location.hash.slice(1);if(titles()[target]){page=target;render();}});
if(titles()[location.hash.slice(1)])page=location.hash.slice(1);save();render();

let voiceTimer,voiceGeneration=0;
function stopVoice(){voiceGeneration++;clearTimeout(voiceTimer);if('speechSynthesis' in window)window.speechSynthesis.cancel();document.querySelectorAll('.secretary-portrait').forEach(el=>el.classList.remove('speaking'));document.querySelector('.secretary-stage')?.classList.remove('speaking');}
function speak(text){
 stopVoice();if(!text)return;if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){$('#voice-status').textContent='В этом браузере озвучивание недоступно.';return;}
 const voices=window.speechSynthesis.getVoices(),ru=voices.filter(v=>/^ru/i.test(v.lang)),voice=ru.find(v=>/female|irina|ирина|svetlana|светлана|maria|мария/i.test(v.name))||ru.find(v=>v.localService)||ru[0];
 if(!voice){$('#voice-status').textContent='Русский голос не найден. Проверьте голоса Windows или откройте в Edge.';return;}
 const generation=voiceGeneration;const utterance=new SpeechSynthesisUtterance(text);utterance.lang='ru-RU';utterance.voice=voice;utterance.rate=.97;utterance.pitch=1.05;
 utterance.onstart=()=>{if(generation!==voiceGeneration)return;$('#voice-status').textContent=`Говорит · ${voice.name}`;document.querySelectorAll('.secretary-portrait').forEach(el=>el.classList.add('speaking'));document.querySelector('.secretary-stage').classList.add('speaking');};
 utterance.onend=()=>{if(generation!==voiceGeneration)return;stopVoice();$('#voice-status').textContent='Готова слушать · голос браузера';};utterance.onerror=()=>{if(generation!==voiceGeneration)return;stopVoice();$('#voice-status').textContent='Не удалось озвучить. Текст ответа доступен в диалоге.';};
 window.speechSynthesis.speak(utterance);voiceTimer=setTimeout(()=>{stopVoice();$('#voice-status').textContent='Озвучивание остановлено. Ответ доступен текстом.';},90000);
}
$('#voice-preview').onclick=()=>speak('Здравствуйте! Меня зовут Алина. Я ваш виртуальный секретарь. Помогу выбрать услугу, оформить заявку и передать вопрос нужному специалисту.');
$('#voice-enabled').onchange=e=>{if(e.target.checked)speak(chat?.messages.filter(m=>m.role==='bot').at(-1)?.text);else stopVoice();};
window.addEventListener('pagehide',stopVoice);

$('#clear-chat').onclick=()=>{cancelPending();$('#chat-input').value='';$('#chat-status').textContent='Ввод очищен. Диалоги и история анализов сохранены.';};

function phoneChannel(){if(!chat)return;if(chat.channel!=='Телефон'&&chat.messages.length>1)openBot();chat.channel='Телефон';$('#chat-channel').value='Телефон';persistChat();}
mountVoice({beforeRecord:()=>{stopVoice();cancelPending();phoneChannel();},onTranscript:text=>{phoneChannel();$('#chat-input').value=text.replace(/\s+/g,' ').trim();$('#chat-input').focus();}});

let telegramItems=[];
async function refreshTelegram(){
 const host=$('#telegram-inbox');host.textContent='Проверяю локальное подключение…';
 try{const statusResponse=await fetch('./api/telegram/status');if(!statusResponse.ok)throw Error('Подключение Telegram доступно в локальной версии через START_VOICE_CRM.cmd.');const status=await statusResponse.json();if(!status.configured||!status.restrictedChat){host.innerHTML='<p>Настройка ещё не выполнена. Создайте отдельного бота в @BotFather и запустите SETUP_TELEGRAM.cmd. Токен сохранится только локально.</p>';return;}
 const response=await fetch('./api/telegram/inbox');if(!response.ok)throw Error('Не удалось получить входящие.');telegramItems=await response.json();host.innerHTML=`<p>${status.enabled?'Бот запущен':'Бот остановлен'} · @${esc(status.username||'')} · только разрешённый чат</p>${status.error?`<p>${esc(status.error)}</p>`:''}${telegramItems.filter(i=>i.profile===profileId).map(i=>`<article class="telegram-message"><strong>${i.audio?'Голосовая запись':'Сообщение'} · ${fmt(i.created)}</strong><p>${esc(i.text)}</p><p>Алина: ${esc(i.reply)}</p><button data-import-telegram="${esc(i.id)}">Добавить в CRM и историю анализов</button></article>`).join('')||'<p>В этом профиле ещё нет входящих. Напишите боту /'+profileId+' и пришлите запись.</p>'}`;
 }catch(e){host.textContent=e.message;}
}
document.addEventListener('click',e=>{const button=e.target.closest('[data-import-telegram]');if(!button)return;const item=telegramItems.find(i=>i.id===button.dataset.importTelegram);if(!item||item.profile!==profileId)return;const d=data(),session=structuredClone(item.session);const ix=d.sessions.findIndex(s=>s.id===session.id);if(ix>=0)d.sessions[ix]=session;else d.sessions.unshift(session);if(item.record&&!d.records.some(r=>r.id===item.record.id)){const r=structuredClone(item.record),c=d.clients.find(c=>c.contact.toLowerCase()===r.contact.toLowerCase());if(c)r.clientId=c.id;else d.clients.push({id:r.clientId,name:r.client,contact:r.contact,company:'Telegram'});d.records.unshift(r);}if(!d.history.some(h=>h.id===item.id))d.history=[{id:item.id,title:'Telegram · '+(session.name||'Голосовое обращение'),created:item.created,sessionId:session.id,text:item.analysis},...d.history].slice(0,3);save();toast('Диалог и разбор добавлены в CRM');});
