const endpoints={ollama:'http://127.0.0.1:11434',local:'http://127.0.0.1:1234'};
let busy=false;
async function listModels(signal){const providers=await Promise.all(Object.entries(endpoints).map(async([provider,base])=>{try{const r=await fetch(base+(provider==='ollama'?'/api/tags':'/v1/models'),{signal:AbortSignal.any([signal,AbortSignal.timeout(3000)])});if(!r.ok)throw Error();const data=await r.json();return {provider,models:(provider==='ollama'?data.models:data.data).map(m=>({provider,id:m.name||m.id})),available:true};}catch{return {provider,models:[],available:false}}}));return {models:providers.flatMap(p=>p.models),providers};}
module.exports=async function labApi(req,res){const ctrl=new AbortController();res.on('close',()=>{if(!res.writableEnded)ctrl.abort()});const reply=(code,value)=>{if(!res.destroyed){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));}};
 if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`){reply(403,{error:'Запрос разрешён только из CRM.'});return;}
 if(req.url.split('?')[0]==='/api/lab/models'&&req.method==='GET'){reply(200,await listModels(ctrl.signal));return;}
 if(req.url!=='/api/lab/chat'||req.method!=='POST'){reply(404,{error:'Неизвестный запрос'});return;}
 let owned=false;try{let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>100000){reply(413,{error:'Сценарий слишком большой'});return;}}const body=JSON.parse(raw);const {provider,model,messages}=body;if(!endpoints[provider]||typeof model!=='string'||!Array.isArray(messages)||!messages.length||messages.length>40||messages.some(m=>!['system','user','assistant'].includes(m.role)||typeof m.content!=='string'||m.content.length>12000)){reply(400,{error:'Проверьте модель и сценарий'});return;}
 if(busy){reply(409,{error:'Полигон занят другим прогоном. Повторите позже.'});return;}busy=true;owned=true;
 const models=await listModels(ctrl.signal);if(!models.models.some(m=>m.provider===provider&&m.id===model)){reply(400,{error:'Модель больше не доступна. Обновите список.'});return;}
 if(body.knowledge==='clinic-demo-v1'){const {clinicSystemPrompt}=await import('./clinic-knowledge.mjs');messages.unshift({role:'system',content:clinicSystemPrompt()});}
 const started=performance.now(),signal=AbortSignal.any([ctrl.signal,AbortSignal.timeout(180000)]);const payload=provider==='ollama'?{model,messages,stream:false,options:{temperature:0,num_predict:256,seed:42}}:{model,messages,stream:false,temperature:0,max_tokens:256,seed:42};
 const response=await fetch(endpoints[provider]+(provider==='ollama'?'/api/chat':'/v1/chat/completions'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal});if(!response.ok)throw Error('Модель вернула ошибку '+response.status);const data=await response.json();const text=provider==='ollama'?data.message?.content:data.choices?.[0]?.message?.content;if(!text?.trim())throw Error('Модель не вернула текст. Возможно, лимит ушёл на рассуждения.');reply(200,{text,elapsedMs:Math.round(performance.now()-started),tokens:provider==='ollama'?data.eval_count??null:data.usage?.completion_tokens??null,tokensPerSecond:provider==='ollama'&&data.eval_duration>0?data.eval_count/(data.eval_duration/1e9):null,loadMs:provider==='ollama'?Math.round((data.load_duration||0)/1e6):null,finishReason:provider==='ollama'?data.done_reason:data.choices?.[0]?.finish_reason,model,provider});
 }catch(e){reply(e.name==='TimeoutError'?504:502,{error:e.name==='TimeoutError'?'Модель не ответила за 3 минуты.':e.message==='fetch failed'?'Локальный сервер недоступен.':e.message});}finally{if(owned)busy=false;}
};
