import {clinicKnowledge} from './clinic-knowledge.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let models=[],runs=[],current=null,controller=null,stopped=false;
try{runs=JSON.parse(localStorage.getItem('bookcraft.lab.runs')||'[]');if(!Array.isArray(runs))runs=[]}catch{}
$('#system').value='Ты Алина, секретарь клиники. Отвечай кратко по-русски. Приём терапевта стоит 2500 рублей. Свободное время: завтра 10:00 или 14:30. Для заявки спроси имя и телефон. Не подтверждай реальную запись: её согласует администратор. По просьбе клиента передай разговор оператору. Не давай медицинских рекомендаций.';
$('#steps').value='Хочу записаться к терапевту. Сколько стоит приём?\nМожно завтра утром?\nПозовите оператора.';$('#checks').value='2500|2 500\n10:00|10 утра\nоператор|администратор';
function save(){try{localStorage.setItem('bookcraft.lab.runs',JSON.stringify(runs.slice(0,10)))}catch{$('#status').textContent+=' Не удалось сохранить историю: экспортируйте JSON.'}}
function draw(){ $('#history').innerHTML=runs.map(r=>`<option value="${esc(r.id)}" ${r.id===(current||runs[0])?.id?'selected':''}>${esc(new Date(r.created).toLocaleString('ru-RU'))} · ${r.rows.length} ответов</option>`).join('');const rows=current?.rows||runs[0]?.rows||[],ok=rows.filter(r=>!r.error),mean=ok.length?ok.reduce((a,r)=>a+r.elapsedMs,0)/ok.length:0;$('#metrics').innerHTML=[['Ответов',ok.length],['Среднее время',ok.length?(mean/1000).toFixed(2)+' с':'—'],['Условия найдены',ok.filter(r=>r.pass===true).length],['Ошибки',rows.filter(r=>r.error).length]].map(([a,b])=>`<div class="kpi"><div class="kpi-top">${a}</div><strong>${b}</strong></div>`).join('');
 const names=[...new Set(rows.map(r=>r.provider+' / '+r.model))];$('#summary').innerHTML=names.map(name=>{const all=rows.filter(r=>r.provider+' / '+r.model===name),good=all.filter(r=>!r.error),times=good.map(r=>r.elapsedMs).sort((a,b)=>a-b),checked=all.filter(r=>r.pass!==null);return `<tr><td>${esc(name)}</td><td>${good.length}</td><td>${times.length?(times.reduce((a,b)=>a+b,0)/times.length/1000).toFixed(2)+' с':'—'}</td><td>${times.length?(times[Math.ceil(times.length*.95)-1]/1000).toFixed(2)+' с':'—'}</td><td>${checked.filter(r=>r.pass).length}/${checked.length}</td><td>${all.length-good.length}</td></tr>`}).join('');
 $('#results').innerHTML=rows.map(r=>`<article class="lab-answer"><strong>${esc(r.model)} · повтор ${r.repeat} · шаг ${r.step}</strong><p>Клиент: ${esc(r.prompt)}</p><pre>${esc(r.error||r.text)}</pre><p>${r.error?'Ошибка':`${(r.elapsedMs/1000).toFixed(2)} с · ${r.tokens??'—'} токенов · ${r.tokensPerSecond?.toFixed(1)??'—'} ток/с · загрузка ${r.loadMs===null?'—':r.loadMs+' мс'} · ${r.pass===null?'Без проверки':r.pass?'Условие найдено':'Условие не найдено'}${r.finishReason==='length'?' · ответ обрезан лимитом':''}`}</p></article>`).join('')||'<p class="muted">Запустите первый сценарий.</p>';
}
async function discover(){try{$('#reload').disabled=true;const r=await fetch('./api/lab/models');if(!r.ok)throw Error('Полигон доступен через локальный сервер CRM.');const d=await r.json();models=d.models;$('#models').innerHTML=models.map((m,i)=>`<label><input type="checkbox" value="${i}" ${m.id==='qwen2.5-coder:1.5b'||m.id==='llama3.2:1b'?'checked':''}>${esc(m.id)}<small>${m.provider==='ollama'?'Ollama':'Локальный сервер · 1234'}</small></label>`).join('')||'Модели не найдены. Запустите локальный сервер.';}catch(e){$('#models').textContent=e.message}finally{$('#reload').disabled=false}}
$('#reload').onclick=discover;$('#stop').onclick=()=>{stopped=true;controller?.abort();$('#status').textContent='Останавливаем прогон…'};
$('#run').onclick=async()=>{const chosen=[...$('#models').querySelectorAll('input:checked')].map(i=>models[Number(i.value)]),steps=$('#steps').value.split('\n').map(s=>s.trim()).filter(Boolean),checks=$('#checks').value.split('\n'),system=$('#system').value,repeats=Number($('#repeats').value);if(!chosen.length||!steps.length||steps.length>10||!Number.isInteger(repeats)||repeats<1||repeats>3||system.length>12000||steps.some(s=>s.length>12000)){$('#status').textContent='Выберите модели, задайте 1–10 реплик и 1–3 повтора.';return;}
 current={id:crypto.randomUUID(),created:new Date().toISOString(),system,steps,checks,models:chosen,repeats,temperature:0,maxTokens:256,knowledge:$('#use-clinic').checked?'clinic-demo-v1':null,knowledgeSnapshot:$('#use-clinic').checked?structuredClone(clinicKnowledge):null,rows:[],status:'running'};runs.unshift(current);runs=runs.slice(0,10);stopped=false;$('#history').disabled=true;$('#run').disabled=true;$('#reload').disabled=true;$('#stop').disabled=false;$('#progress').max=chosen.length*repeats*steps.length;$('#progress').value=0;save();draw();
 try{outer:for(const m of chosen){for(let repeat=1;repeat<=repeats;repeat++){const messages=[{role:'system',content:system}];for(let i=0;i<steps.length;i++){if(stopped)break outer;$('#status').textContent=`${m.id} · повтор ${repeat}/${repeats} · шаг ${i+1}/${steps.length}`;messages.push({role:'user',content:steps[i]});controller=new AbortController();let row={...m,model:m.id,repeat,step:i+1,prompt:steps[i],expected:checks[i]||'',pass:null};try{const r=await fetch('./api/lab/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:m.provider,model:m.id,messages,knowledge:current.knowledge}),signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка запроса');if(stopped)break outer;row={...row,...d};const alternatives=(checks[i]||'').split('|').map(s=>s.trim().toLocaleLowerCase()).filter(Boolean);row.pass=alternatives.length?alternatives.some(s=>d.text.toLocaleLowerCase().includes(s)):null;messages.push({role:'assistant',content:d.text});}catch(e){if(stopped||e.name==='AbortError')break outer;row.error=e.message;messages.pop();}current.rows.push(row);$('#progress').value++;save();draw();if(row.error)break;}}}current.status=stopped?'cancelled':'completed';$('#status').textContent=stopped?'Остановлено. Готовые ответы сохранены.':'Прогон завершён. Сравните ответы и проверки.';}finally{$('#history').disabled=false;$('#run').disabled=false;$('#reload').disabled=false;$('#stop').disabled=true;controller=null;save();}};
$('#history').onchange=()=>{current=runs.find(r=>r.id===$('#history').value);if(current){$('#system').value=current.system;$('#steps').value=current.steps.join('\n');$('#checks').value=current.checks.join('\n');$('#repeats').value=current.repeats;$('#use-clinic').checked=current.knowledge==='clinic-demo-v1';$('#status').textContent='Сохранённый прогон · '+current.status;draw();}};
$('#knowledge-preview').textContent=clinicKnowledge.title+'\n\n'+clinicKnowledge.services.map(s=>s.name+' — '+s.price+' ₽\n'+s.slots.join('; ')).join('\n\n')+'\n\nПравила\n'+clinicKnowledge.rules.join('\n')+'\n\nПримеры\n'+clinicKnowledge.examples.map(([q,a])=>'Клиент: '+q+'\nАлина: '+a).join('\n\n');
$('#clinic-template').onclick=()=>{$('#use-clinic').checked=true;$('#system').value='Соблюдай базу знаний. Короткие ответы, один вопрос за раз. Не выдумывай факты.';$('#steps').value=clinicKnowledge.test.steps.join('\n');$('#checks').value=clinicKnowledge.test.checks.join('\n');};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(runs,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bookcraft-model-runs.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};draw();discover();
