export function pcmWav(samples,rate=16000){
 const buffer=new ArrayBuffer(44+samples.length*2),v=new DataView(buffer);const str=(offset,s)=>[...s].forEach((c,i)=>v.setUint8(offset+i,c.charCodeAt(0)));
 str(0,'RIFF');v.setUint32(4,36+samples.length*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,samples.length*2,true);
 samples.forEach((n,i)=>v.setInt16(44+i*2,Math.max(-1,Math.min(1,n))*(n<0?32768:32767),true));return new Blob([buffer],{type:'audio/wav'});
}
export async function segmentWav(buffer,index){
 const offset=index*30,duration=Math.min(30,buffer.duration-offset),ctx=new OfflineAudioContext(1,Math.max(1,Math.round(duration*16000)),16000),input=ctx.createBuffer(1,Math.max(1,Math.round(duration*buffer.sampleRate)),buffer.sampleRate),samples=input.getChannelData(0);
 for(let ch=0;ch<buffer.numberOfChannels;ch++){const data=buffer.getChannelData(ch);for(let n=0;n<samples.length;n++)samples[n]+=(data[Math.round(offset*buffer.sampleRate)+n]||0)/buffer.numberOfChannels;}
 const source=ctx.createBufferSource();source.buffer=input;source.connect(ctx.destination);source.start();return pcmWav((await ctx.startRendering()).getChannelData(0));
}
export function mountVoice({onTranscript,beforeRecord}){
 const root=document.querySelector('#voice-panel');root.innerHTML=`<details open><summary>Диктофон · телефонное обращение</summary><div class="phone-recorder"><div class="recorder-heading"><span class="call-badge">ТЕЛЕФОН · ДЕМО</span><time id="record-time" aria-label="Длительность записи">00:00</time></div><div class="recorder-center"><button type="button" id="mic-start" aria-label="Диктовать телефонное обращение"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></svg></button><div><strong id="recorder-label">Диктуйте — Алина на связи</strong><p>Удерживайте кнопку, пока говорите.<br>Отпустите — Алина получит расшифровку.</p></div></div><div class="record-eq" aria-label="Уровень звука микрофона"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="recorder-bottom"><span>Запись → текст → ответ секретаря</span><button type="button" id="mic-stop" disabled>■ Стоп</button></div></div><div class="voice-actions"><label class="audio-upload">Загрузить запись<input id="audio-file" type="file" accept=".mp3,.wav,.m4a,.ogg,.webm,.oga" aria-label="Аудиозапись"></label></div><details class="recorder-examples"><summary>Попробовать на примере</summary><div class="voice-actions"><select id="demo-audio" aria-label="Учебная запись"><option value="01-therapist.wav">Терапевт · учебное аудио</option><option value="02-cardiologist.wav">Кардиолог · учебное аудио</option><option value="03-checkup.wav">Осмотр · учебное аудио</option></select><button type="button" id="load-demo-audio">Взять пример</button></div><small>Учебные записи озвучены синтезатором.</small></details><small>Файл до 25 МБ · запись до 2 минут</small><audio id="audio-preview" controls hidden></audio><div class="voice-actions"><button type="button" id="recognize-audio" disabled>Повторить</button><button type="button" id="cancel-audio" disabled>Отменить</button></div><progress id="audio-progress" max="100" value="0" aria-label="Прогресс распознавания"></progress><p id="audio-status" role="status">Запишите голос или выберите аудиофайл.</p><textarea hidden id="audio-transcript" rows="3" readonly placeholder="Здесь появится расшифровка — отправим её в диалог автоматически" aria-label="Расшифровка записи"></textarea><button type="button" id="send-transcript" hidden>Передать текст секретарю</button></details>`;
 const q=id=>root.querySelector('#'+id);
 let blob=null,url=null,stream=null,recorder=null,recordTimer=null,ticker=null,meterContext=null,meterFrame=null,controller=null,epoch=0,recording=false,requesting=false,recognizing=false,holding=false,failed=false;
 const status=text=>q('audio-status').textContent=text;
 const refresh=()=>{root.classList.toggle('is-recording',recording);root.classList.toggle('is-recognizing',recognizing);root.setAttribute('aria-busy',String(recognizing));q('recorder-label').textContent=recording?'Говорите. Отпустите, когда закончите':recognizing?'Расшифровываем ваше обращение':requesting?'Подключаем запись…':'Удерживайте микрофон и говорите';q('load-demo-audio').disabled=recording||requesting||recognizing;q('mic-start').disabled=recognizing;q('mic-start').setAttribute('aria-pressed',String(recording));q('mic-stop').disabled=!recording;q('audio-file').disabled=recording||requesting||recognizing;q('recognize-audio').hidden=!failed;q('cancel-audio').hidden=!(recognizing||requesting||recording);q('recognize-audio').disabled=!blob||recording||recognizing||requesting;q('cancel-audio').disabled=!(recognizing||requesting||recording);};
 const cleanup=()=>{clearTimeout(recordTimer);clearInterval(ticker);cancelAnimationFrame(meterFrame);meterContext?.close().catch(()=>{});meterContext=null;root.querySelectorAll('.record-eq i').forEach(bar=>bar.style.height='4px');stream?.getTracks().forEach(t=>t.stop());stream=null;};
 function startMeter(){try{meterContext=new AudioContext();const analyser=meterContext.createAnalyser();analyser.fftSize=256;meterContext.createMediaStreamSource(stream).connect(analyser);meterContext.resume().catch(()=>{});const values=new Uint8Array(analyser.frequencyBinCount),bars=[...root.querySelectorAll('.record-eq i')];const draw=()=>{analyser.getByteFrequencyData(values);bars.forEach((bar,i)=>{const value=values[2+i*3]||0;bar.style.height=(4+value/255*30)+'px';});meterFrame=requestAnimationFrame(draw);};draw();}catch{ /* Recording remains available without visualization. */ }}
 const select=(audio,name)=>{blob=audio;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(audio);q('audio-preview').src=url;q('audio-preview').hidden=false;q('audio-transcript').value='';q('audio-progress').value=0;status(`Получили: ${name}. Начинаем распознавание…`);refresh();};
 function cancel(){failed=!!blob;epoch++;holding=false;controller?.abort();controller=null;if(recorder?.state==='recording')recorder.stop();recording=false;requesting=false;recognizing=false;cleanup();q('audio-progress').value=0;status('Отменено. Полученный текст сохранён; можно повторить распознавание.');refresh();}
 async function recognize(){
  if(!blob||recognizing)return;const run=++epoch,source=blob;controller=new AbortController();const signal=controller.signal;recognizing=true;failed=false;q('audio-progress').removeAttribute('value');q('audio-transcript').value='';refresh();let ctx;
  try{status('Подготавливаем распознавание…');const health=await fetch('./api/stt/health',{signal});if(!health.ok)throw Error('Распознавание недоступно. Запустите START_VOICE_CRM.cmd и нажмите «Повторить».');const ready=await health.json();if(!ready.ready)throw Error('Распознавание ещё не готово. Повторите через несколько секунд.');ctx=new AudioContext();const audio=await ctx.decodeAudioData(await source.arrayBuffer());await ctx.close();ctx=null;if(run!==epoch)return;if(!audio.duration||audio.duration>600)throw Error('Запись должна быть не длиннее 10 минут. Сократите файл.');const count=Math.ceil(audio.duration/30),parts=[];
   for(let i=0;i<count;i++){status(`Расшифровываем · фрагмент ${i+1} из ${count}`);const chunk=await segmentWav(audio,i);if(run!==epoch)return;const form=new FormData();form.append('audio',chunk,'segment.wav');const response=await fetch('./api/stt/segment',{method:'POST',body:form,signal});const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(typeof result.detail==='string'?result.detail:'Не удалось распознать. Нажмите «Повторить».');if(typeof result.text!=='string')throw Error('Сервис вернул некорректный результат.');if(run!==epoch)return;parts.push(result.text);q('audio-transcript').value=parts.join('\n').trim();if(i+1<count)status(`Готово ${i+1} из ${count} фрагментов. Продолжаем…`);}
   q('audio-progress').value=100;const text=q('audio-transcript').value.trim();if(text){onTranscript(text,{automatic:true});status('Готово. Обращение добавлено в диалог — Алина отвечает.');}else status('Речь не обнаружена. Удерживайте микрофон дольше или выберите другую запись.');
  }catch(e){if(run===epoch){failed=true;q('audio-progress').value=0;status(e.name==='AbortError'?'Отменено. Текст сохранён.':e.message);}}finally{if(ctx)await ctx.close().catch(()=>{});if(run===epoch){recognizing=false;controller=null;refresh();}}
 }
 q('load-demo-audio').onclick=async()=>{beforeRecord();const run=++epoch;requesting=true;controller=new AbortController();refresh();status('Загружаем учебную запись…');try{const response=await fetch('./demo-audio/'+q('demo-audio').value,{signal:controller.signal});if(!response.ok)throw Error('Учебная запись не найдена.');const file=await response.blob();if(run===epoch){requesting=false;select(file,q('demo-audio').selectedOptions[0].textContent);await recognize();}}catch(e){if(run===epoch)status(e.name==='AbortError'?'Отменено.':e.message);}finally{if(run===epoch){requesting=false;refresh();}}};
 async function begin(){if(recording||requesting||recognizing)return;beforeRecord();holding=true;const run=++epoch;requesting=true;refresh();status('Разрешите микрофон. Удерживайте кнопку во время записи.');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Запись недоступна в этом браузере. Загрузите аудиофайл.');const acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(run!==epoch||!holding){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;const chunks=[],capture=new MediaRecorder(stream);recorder=capture;capture.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};capture.onerror=()=>{if(run!==epoch)return;cancel();status('Ошибка микрофона. Повторите запись или загрузите файл.');};capture.onstop=()=>{if(run!==epoch){acquired.getTracks().forEach(t=>t.stop());return;}cleanup();holding=false;recording=false;if(chunks.length){select(new Blob(chunks,{type:capture.mimeType||'audio/webm'}),'телефонное обращение');void recognize();}else{status('Запись слишком короткая. Удерживайте микрофон и говорите.');refresh();}};capture.start();recording=true;const started=Date.now();q('record-time').textContent='00:00';ticker=setInterval(()=>{const seconds=Math.floor((Date.now()-started)/1000);q('record-time').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');},250);startMeter();status('Записываем голос. Отпустите кнопку — текст появится в диалоге.');recordTimer=setTimeout(release,120000);}catch(e){if(run!==epoch)return;cleanup();holding=false;status(e.name==='NotAllowedError'?'Доступ к микрофону запрещён. Разрешите его в браузере или загрузите запись.':e.message);}finally{if(run===epoch){requesting=false;refresh();}}}
 function release(){holding=false;if(requesting){epoch++;requesting=false;status('Нажмите и удерживайте микрофон для записи.');refresh();}if(recorder?.state==='recording')recorder.stop();}
 const mic=q('mic-start');mic.onpointerdown=e=>{if(e.button!==0||recording||requesting||recognizing)return;e.preventDefault();mic.setPointerCapture?.(e.pointerId);void begin();};mic.onpointerup=release;mic.onpointercancel=()=>{if(holding)cancel();};mic.onlostpointercapture=()=>{if(holding)release();};mic.onkeydown=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();if(!e.repeat)void begin();}};mic.onkeyup=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();release();}};mic.onblur=()=>{if(holding)cancel();};q('mic-stop').onclick=release;
 q('audio-file').onchange=async()=>{const f=q('audio-file').files[0];if(!f)return;if(!/\.(mp3|wav|m4a|ogg|webm|oga)$/i.test(f.name)||!f.size||f.size>25*1024*1024){status('Нужен непустой аудиофайл MP3/WAV/M4A/OGG/WEBM до 25 МБ.');q('audio-file').value='';return;}beforeRecord();epoch++;select(f,f.name);q('audio-file').value='';await recognize();};
 q('cancel-audio').onclick=cancel;q('recognize-audio').onclick=recognize;
 q('send-transcript').onclick=()=>{const text=q('audio-transcript').value.trim();if(text)onTranscript(text,{automatic:true});else status('Сначала получите или введите расшифровку.');};
 window.addEventListener('blur',()=>{if(holding)cancel();});
 window.addEventListener('crm:context-changed',()=>{cancel();blob=null;if(url)URL.revokeObjectURL(url);url=null;q('audio-preview').removeAttribute('src');q('audio-preview').hidden=true;q('audio-transcript').value='';q('audio-file').value='';q('audio-progress').value=0;q('record-time').textContent='00:00';status('Удерживайте микрофон или загрузите аудиофайл.');refresh();});
 refresh();return {cancel};
}
