export function pcmWav(samples,rate=16000){
 const buffer=new ArrayBuffer(44+samples.length*2),v=new DataView(buffer);const str=(offset,s)=>[...s].forEach((c,i)=>v.setUint8(offset+i,c.charCodeAt(0)));
 str(0,'RIFF');v.setUint32(4,36+samples.length*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,samples.length*2,true);
 samples.forEach((n,i)=>v.setInt16(44+i*2,Math.max(-1,Math.min(1,n))*(n<0?32768:32767),true));return new Blob([buffer],{type:'audio/wav'});
}
export async function segmentWav(buffer,index){
 const offset=index*30,duration=Math.min(30,buffer.duration-offset),ctx=new OfflineAudioContext(1,Math.max(1,Math.round(duration*16000)),16000),input=ctx.createBuffer(1,Math.max(1,Math.round(duration*buffer.sampleRate)),buffer.sampleRate),samples=input.getChannelData(0);
 for(let ch=0;ch<buffer.numberOfChannels;ch++){const data=buffer.getChannelData(ch);for(let n=0;n<samples.length;n++)samples[n]+=(data[Math.round(offset*buffer.sampleRate)+n]||0)/buffer.numberOfChannels;}
 const source=ctx.createBufferSource();source.buffer=input;source.connect(ctx.destination);source.start();return pcmWav((await ctx.startRendering()).getChannelData(0));
}
export function mountVoice({onTranscript,beforeRecord}){
 const root=document.querySelector('#voice-panel');root.innerHTML=`<details open><summary>Диктофон · телефонное обращение</summary><div class="phone-recorder"><div class="recorder-heading"><span class="call-badge">ТЕЛЕФОН · ДЕМО</span><time id="record-time" aria-label="Длительность записи">00:00</time></div><div class="recorder-center"><button type="button" id="mic-start" aria-label="Диктовать телефонное обращение"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></svg></button><div><strong id="recorder-label">Диктуйте — Алина на связи</strong><p>Нажмите микрофон и произнесите обращение.<br>Сохраним его как звонок по телефону.</p></div></div><div class="recorder-bottom"><span>Запись → текст → ответ секретаря</span><button type="button" id="mic-stop" disabled>■ Стоп</button></div></div><p>Имитация телефонного звонка. Голос распознаётся по-настоящему, секретарь отвечает по сценарию.</p><div class="voice-actions"><label class="audio-upload">Загрузить запись<input id="audio-file" type="file" accept=".mp3,.wav,.m4a,.ogg,.webm,.oga" aria-label="Аудиозапись"></label></div><div class="voice-actions"><select id="demo-audio" aria-label="Учебная запись"><option value="01-therapist.wav">Терапевт · учебное аудио</option><option value="02-cardiologist.wav">Кардиолог · учебное аудио</option><option value="03-checkup.wav">Осмотр · учебное аудио</option></select><button type="button" id="load-demo-audio">Взять пример</button></div><small>Примеры озвучены синтезатором, распознавание выполняется настоящим Whisper.</small><br><small>До 25 МБ и 10 минут. Запись микрофона — до 2 минут.</small><audio id="audio-preview" controls hidden></audio><div class="voice-actions"><button type="button" id="recognize-audio" disabled>Распознать запись</button><button type="button" id="cancel-audio" disabled>Отменить распознавание</button></div><progress id="audio-progress" max="100" value="0" aria-label="Прогресс распознавания"></progress><p id="audio-status" role="status">Запишите голос или выберите аудиофайл.</p><textarea id="audio-transcript" rows="3" placeholder="Распознанный текст можно исправить перед отправкой" aria-label="Расшифровка записи"></textarea><button type="button" id="send-transcript">Передать текст секретарю</button></details>`;
 const q=id=>root.querySelector('#'+id);let blob=null,url=null,stream=null,recorder=null,recordTimer=null,ticker=null,recordStarted=0,controller=null,epoch=0,recording=false,requesting=false,recognizing=false,contextEpoch=0;
 const status=text=>q('audio-status').textContent=text;
 const refresh=()=>{root.classList.toggle('is-recording',recording);q('recorder-label').textContent=recording?'Идёт запись звонка':requesting?'Подключаем микрофон или запись…':'Диктуйте — Алина на связи';q('load-demo-audio').disabled=recording||requesting||recognizing;q('mic-start').disabled=recording||requesting||recognizing;q('mic-stop').disabled=!recording;q('audio-file').disabled=recording||requesting||recognizing;q('recognize-audio').disabled=!blob||recording||recognizing||requesting;q('cancel-audio').disabled=!recognizing;q('send-transcript').disabled=recording||recognizing||requesting;};
 const cleanup=()=>{clearTimeout(recordTimer);clearInterval(ticker);stream?.getTracks().forEach(t=>t.stop());stream=null;};
 const select=(audio,name)=>{blob=audio;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(audio);q('audio-preview').src=url;q('audio-preview').hidden=false;q('audio-transcript').value='';q('audio-progress').value=0;status(`Получили: ${name}. Нажмите «Распознать запись».`);refresh();};
 function cancel(){epoch++;controller?.abort();controller=null;recognizing=false;status('Распознавание отменено. Уже полученный текст сохранён.');refresh();}
 q('load-demo-audio').onclick=async()=>{const run=++epoch;requesting=true;refresh();status('Загружаю учебную запись…');try{const response=await fetch('./demo-audio/'+q('demo-audio').value);if(!response.ok)throw Error('Учебная запись не найдена.');const file=await response.blob();if(run===epoch)select(file,q('demo-audio').selectedOptions[0].textContent);}catch(e){if(run===epoch)status(e.message);}finally{if(run===epoch){requesting=false;refresh();}}};
 q('mic-start').onclick=async()=>{beforeRecord();const run=++epoch;requesting=true;refresh();status('Разрешите доступ к микрофону…');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Запись недоступна в этом браузере. Загрузите аудиофайл.');const acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(run!==epoch){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;const chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=()=>{if(run!==epoch)return;epoch++;recording=false;cleanup();status('Ошибка микрофона. Повторите запись или загрузите файл.');refresh();};recorder.onstop=()=>{if(run!==epoch){acquired.getTracks().forEach(t=>t.stop());return;}cleanup();recording=false;if(run===epoch&&chunks.length)select(new Blob(chunks,{type:recorder.mimeType||'audio/webm'}),'запись микрофона');refresh();};recorder.start();recording=true;recordStarted=Date.now();q('record-time').textContent='00:00';ticker=setInterval(()=>{const seconds=Math.floor((Date.now()-recordStarted)/1000);q('record-time').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');},250);status('Идёт запись. Произнесите обращение и нажмите «Стоп».');recordTimer=setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},120000);}catch(e){if(run!==epoch)return;cleanup();status(e.name==='NotAllowedError'?'Доступ к микрофону запрещён. Разрешите его в браузере или загрузите запись.':e.message);}finally{if(run===epoch){requesting=false;refresh();}}};
 q('mic-stop').onclick=()=>{if(recorder?.state==='recording')recorder.stop();};
 q('audio-file').onchange=()=>{const f=q('audio-file').files[0];if(!f)return;if(!/\.(mp3|wav|m4a|ogg|webm|oga)$/i.test(f.name)||!f.size||f.size>25*1024*1024){status('Нужен непустой аудиофайл MP3/WAV/M4A/OGG/WEBM до 25 МБ.');q('audio-file').value='';return;}epoch++;select(f,f.name);};
 q('cancel-audio').onclick=cancel;
 q('recognize-audio').onclick=async()=>{
  if(!blob||recognizing)return;const run=++epoch,source=blob;controller=new AbortController();const signal=controller.signal;recognizing=true;q('audio-progress').value=0;q('audio-transcript').value='';refresh();let ctx;
  try{status('Проверка локального Whisper…');const health=await fetch('./api/stt/health',{signal});if(!health.ok)throw Error('Локальный Whisper не запущен. Запустите START_VOICE_CRM.cmd на компьютере.');const ready=await health.json();if(!ready.ready)throw Error('Whisper или модель не настроены.');ctx=new AudioContext();const audio=await ctx.decodeAudioData(await source.arrayBuffer());await ctx.close();ctx=null;if(run!==epoch)return;if(!audio.duration||audio.duration>600)throw Error('Запись должна быть не длиннее 10 минут. Сократите файл.');const count=Math.ceil(audio.duration/30),parts=[];
   for(let i=0;i<count;i++){status(`Распознаю фрагмент ${i+1} из ${count} · Whisper ${ready.model}`);const chunk=await segmentWav(audio,i);if(run!==epoch)return;const form=new FormData();form.append('audio',chunk,'segment.wav');const response=await fetch('./api/stt/segment',{method:'POST',body:form,signal});const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(typeof result.detail==='string'?result.detail:'Не удалось распознать. Повторите попытку.');if(typeof result.text!=='string')throw Error('Сервис вернул некорректный результат.');if(run!==epoch)return;parts.push(result.text);q('audio-transcript').value=parts.join('\n').trim();q('audio-progress').value=Math.round(Math.min(audio.duration,(i+1)*30)/audio.duration*100);}
   status(q('audio-transcript').value?'Готово. Проверьте текст и передайте его секретарю.':'Речь не обнаружена. Попробуйте другую запись.');
  }catch(e){if(run===epoch)status(e.name==='AbortError'?'Отменено. Текст сохранён.':e.message);}finally{if(ctx)await ctx.close().catch(()=>{});if(run===epoch){recognizing=false;controller=null;refresh();}}
 };
 q('send-transcript').onclick=()=>{const text=q('audio-transcript').value.trim();if(!text){status('Сначала получите или введите расшифровку.');return;}onTranscript(text);status('Текст помещён в поле сообщения. Нажмите стрелку отправки, чтобы получить ответ Алины.');};
 window.addEventListener('crm:context-changed',()=>{contextEpoch++;cancel();requesting=false;epoch++;if(recorder?.state==='recording')recorder.stop();cleanup();recording=false;blob=null;if(url)URL.revokeObjectURL(url);url=null;q('audio-preview').removeAttribute('src');q('audio-preview').hidden=true;q('audio-transcript').value='';q('audio-file').value='';q('audio-progress').value=0;q('record-time').textContent='00:00';status('Запишите голос или выберите аудиофайл.');refresh();});
 refresh();return {cancel};
}
