'use client';
import {useState,useEffect} from 'react';
import {ArrowRight,ArrowLeft,Volume2,VolumeX,Mic,Square,Check,Download,ChevronDown,ChevronUp} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {interview,worlds,heroes,looks,pages} from './story-data';
import {useVoice} from './use-voice';
const greeting='Здравствуйте! Я Алина, цифровая ведущая «Диких идей». Помогу найти основу вашей истории. Сначала поговорим о замысле, затем выберем один из трёх миров и образы героев. После вашего согласования перейдём к сценарию первых двадцати страниц.';
export function Studio({active,onStart,onBack}:{active:boolean;onStart:()=>void;onBack:()=>void}){
 const [stage,setStage]=useState(0),[answers,setAnswers]=useState<string[]>([]),[draft,setDraft]=useState(''),[world,setWorld]=useState(''),[variants,setVariants]=useState<string[]>(['','','']),[names,setNames]=useState(heroes.map(h=>h.name)),[voiceOn,setVoiceOn]=useState(false),[minimized,setMinimized]=useState(false),[approved,setApproved]=useState(false),[downloaded,setDownloaded]=useState(false);
 useEffect(()=>{if(window.matchMedia('(max-width: 760px)').matches)setMinimized(true);},[]);
 const voice=useVoice(setDraft);const q=answers.length;const selectedWorld=worlds.find(w=>w.id===world);
 const line=!active?greeting:stage===0?(q<3?((q===1&&answers[0]==='Для читателей и продаж'?'Начнём с короткого выпуска и проверим интерес аудитории. ':q===1&&answers[0]==='Для себя или в подарок'?'Тогда сделаем историю личной и узнаваемой. ':'')+interview[q].speech):'Основа есть. Теперь посмотрим три визуальных направления для нашей истории. Вы сможете вернуться и изменить ответы.'):stage===1?'Перед вами три разных мира одной истории. Выберите атмосферу, в которой хотите встретить героев.':stage===2?'Для каждого героя выберите один из трёх образов. Имена можно изменить. Это концепты для согласования; перед выпуском мы приведём костюмы к выбранному миру.':stage===3?'Проверим выбор. Это основа для сценария, а не готовый комикс. Подтвердите мир и героев, чтобы открыть план первых двадцати страниц.':'Вот план первого выпуска. Оружие остаётся у отца, берет предстоит заслужить в академии. План нужно подробно расписать по кадрам и согласовать до производства рисунков.';
 useEffect(()=>{if(voiceOn)voice.speak(line);else voice.stop();return voice.stop;},[line,voiceOn,voice.speak,voice.stop]);
 const choose=(answer:string)=>{voice.stop();setAnswers([...answers,answer]);setDraft('');setApproved(false);};
 const go=(n:number)=>{voice.stop();setStage(n);window.scrollTo({top:0,behavior:'smooth'});};
 const exportBrief=()=>{const rename=(s:string)=>heroes.reduce((t,h,i)=>t.replaceAll(h.name,names[i]||h.name).replaceAll(h.name.split(' ')[0],(names[i]||h.name).split(' ')[0]),s);const result=['ДИКИЕ ИДЕИ — Пересечение трёх лун','Концепция согласована в прототипе. Производство не запущено.','',...answers.map((a,i)=>interview[i].title+' '+a),'Мир: '+selectedWorld?.name,...heroes.map((h,i)=>(names[i]||h.name)+' — '+looks[Number(variants[i])]),'','ПЛАН 20 СТРАНИЦ — требует покадрового сценария',...pages.map(([t,a,r],i)=>`${i+1}. ${t}\n${rename(a)}\n${rename(r)}`)].join('\n\n');const url=URL.createObjectURL(new Blob([result],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Дикие-идеи-концепция-и-20-страниц.txt';a.click();URL.revokeObjectURL(url);setDownloaded(true);};
 const rename=(s:string)=>heroes.reduce((t,h,i)=>t.replaceAll(h.name,names[i]||h.name).replaceAll(h.name.split(' ')[0],(names[i]||h.name).split(' ')[0]),s);
 return <>
 {active&&<main className="studio"><button className="back" onClick={()=>{voice.stop();setVoiceOn(false);onBack();}}><ArrowLeft size={16}/>На первую страницу</button><div className="journey" aria-label="Этапы создания">{['Знакомство','Три мира','Образы героев','Согласование','20 страниц'].map((s,i)=><span className={i===stage?'current':i<stage?'complete':''} key={s}>{i<stage?<Check size={14}/>:<b>0{i+1}</b>}{s}</span>)}</div><div className="studio-layout"><section className="studio-work glass"><p className="eyebrow">ПЕРЕСЕЧЕНИЕ ТРЁХ ЛУН · ПИЛОТ</p>
 {stage===0&&<><h1>Начнём с вашей идеи.</h1><p className="studio-lead">Алина задаст три вопроса. Отвечайте голосом, текстом или выбирайте готовый вариант.</p>{answers.map((a,i)=><div className="history" key={i}><p>{interview[i].title}</p><div><Check size={15}/>{a}</div></div>)}{q<3?<div className="question"><span className="label">ВОПРОС {q+1} ИЗ 3</span><h2>{interview[q].title}</h2><div className="choices">{interview[q].options.map(o=><Button variant="outline" className="choice" key={o} onClick={()=>choose(o)}>{o}<ArrowRight size={18}/></Button>)}</div><form className="voice-answer" onSubmit={e=>{e.preventDefault();if(draft.trim())choose(draft.trim());}}><label htmlFor="spoken-answer">Или ответьте своими словами</label><textarea id="spoken-answer" placeholder="Нажмите микрофон или напишите ответ…" value={draft} maxLength={1000} onChange={e=>setDraft(e.target.value)}/><div className="answer-actions"><Button variant="outline" className="outline" type="button" onClick={()=>{if(voice.listening)voice.stop();else voice.listen();}}>{voice.listening?<Square/>:<Mic/>}{voice.listening?'Остановить':'Ответить голосом'}</Button><Button className="primary" type="submit" disabled={!draft.trim()}>Подтвердить ответ <Check/></Button></div><p className="notice">Распознанный текст появится здесь. Проверьте его перед подтверждением. Распознавание может использовать сервис вашего браузера.</p></form></div>:<div className="question"><h2>От замысла — к атмосфере.</h2><p>В пилоте исследуем историю рейнджера по мотивам «Трёх мушкетёров». Ваши ответы сохранены в наброске для дальнейшей работы над сценарием.</p><Button className="primary" onClick={()=>go(1)}>Посмотреть три мира <ArrowRight/></Button></div>}{q>0&&<button className="back" onClick={()=>{setAnswers(answers.slice(0,-1));setDraft('');setApproved(false);}}>Изменить предыдущий ответ</button>}</>}
 {stage===1&&<><h1>В каком мире<br/>начнётся история?</h1><p className="studio-lead">Три направления. Одна приключенческая основа.</p><RadioGroup className="world-options" value={world} onValueChange={v=>{setWorld(String(v));setVariants(['','','']);setApproved(false);}} aria-label="Выберите мир">{worlds.map((w,i)=><label className={'visual-option '+(world===w.id?'selected':'')} key={w.id}><div className="world-picture" role="img" aria-label={w.name} style={{backgroundImage:'url(/worlds.png)',backgroundPosition:`${i*50}% center`}}/><div className="option-copy"><span className="label">{w.tag}</span><h2><RadioGroupItem value={w.id}/>{w.name}</h2><p>{w.description}</p></div></label>)}</RadioGroup><div className="stage-actions"><button className="back" onClick={()=>go(0)}><ArrowLeft size={16}/>К диалогу</button><Button className="primary" disabled={!world} onClick={()=>go(2)}>Выбрать героев <ArrowRight/></Button></div></>}
 {stage===2&&<><h1>Узнаваемые герои.<br/>Ваш выбор.</h1><p className="studio-lead">По три образа для Кая и двух его товарищей. Третий товарищ — Илан — остаётся в сюжете; его дизайн подготовим отдельно.</p><p className="concept-note">Мир: {selectedWorld?.name}. Образы — предварительные концепты. Костюмы адаптируем к миру перед производством страниц.</p>{heroes.map((h,col)=><section className="hero-choice" key={h.name}><div className="hero-choice-heading"><div><span className="label">{h.role}</span><label htmlFor={'name-'+col}>Имя героя</label><input id={'name-'+col} value={names[col]} maxLength={50} onChange={e=>{const n=[...names];n[col]=e.target.value;setNames(n);setApproved(false);}}/></div><p>{h.detail}</p></div><RadioGroup className="character-options" value={variants[col]} onValueChange={v=>{const n=[...variants];n[col]=String(v);setVariants(n);setApproved(false);}} aria-label={'Образ '+(names[col]||h.name)}>{looks.map((look,row)=><label key={look} className={'visual-option '+(variants[col]===String(row)?'selected':'')}><div className="character-picture" role="img" aria-label={`${h.name}: ${look}`} style={{backgroundImage:'url(/heroes.png)',backgroundPosition:`${col*50}% ${row*50}%`}}/><div className="look-name"><RadioGroupItem value={String(row)}/><span>{look}</span><span>0{row+1}</span></div></label>)}</RadioGroup></section>)}<div className="stage-actions"><button className="back" onClick={()=>go(1)}><ArrowLeft size={16}/>Изменить мир</button><Button className="primary" disabled={variants.some(v=>!v)||names.some(n=>!n.trim())} onClick={()=>go(3)}>Проверить концепцию <ArrowRight/></Button></div></>}
 {stage===3&&<><h1>Всё ли совпало<br/>с вашей идеей?</h1><p className="studio-lead">Перед сценарием фиксируем основу. Пока ничего не отправляем в производство.</p><div className="review-world"><div className="world-picture" style={{backgroundImage:'url(/worlds.png)',backgroundPosition:`${worlds.findIndex(w=>w.id===world)*50}% center`}}/><h2>{selectedWorld?.name}</h2></div><div className="review-heroes">{heroes.map((h,i)=><div key={h.name}><div className="character-picture" role="img" aria-label={names[i]} style={{backgroundImage:'url(/heroes.png)',backgroundPosition:`${i*50}% ${Number(variants[i])*50}%`}}/><h3>{names[i]}</h3><p>{looks[Number(variants[i])]}</p></div>)}</div>{answers.map((a,i)=><div className="brief" key={i}><span>{interview[i].title}</span><strong>{a}</strong></div>)}<p className="concept-note">История: сын рейнджера прибывает в академию. Оружие остаётся у отца. Для возвращения его силы герою предстоит найти храмы трёх лун. Берет выдаётся после испытаний.</p><div className="stage-actions"><button className="back" onClick={()=>go(2)}><ArrowLeft size={16}/>Изменить героев</button><Button className="primary" onClick={()=>{setApproved(true);go(4);}}>Согласовать и открыть план <Check/></Button></div></>}
 {stage===4&&approved&&<><p className="approval"><Check size={16}/>Концепция согласована в этой сессии</p><h1>Выпуск 01.<br/>Порог академии.</h1><p className="studio-lead">План первых 20 страниц. Это сценарная основа, ещё не нарисованный комикс.</p><div className="page-plan">{pages.map(([title,action,replica],i)=><article key={title}><span className="page-index">{String(i+1).padStart(2,'0')}</span><div><h2>{rename(title)}</h2><p>{rename(action)}</p><blockquote>{rename(replica)}</blockquote></div></article>)}</div><div className="production-note"><h2>Следующий этап — покадровый сценарий</h2><p>Уточняем действия и диалоги, согласуем две пробные страницы. После этого можно запускать остальные изображения. Генератор комикса пока не подключён.</p></div><div className="stage-actions"><button className="back" onClick={()=>go(3)}><ArrowLeft size={16}/>К концепции</button><Button className="primary" onClick={exportBrief}>{downloaded?<Check/>:<Download/>}{downloaded?'План скачан':'Скачать концепцию и план'}</Button></div></>}
 </section><aside className="studio-summary"><p className="eyebrow">ВАШ ПРОЕКТ</p><h2>История<br/>обретает форму.</h2><div className="brief"><span>Основа</span><strong>По мотивам «Трёх мушкетёров»</strong></div><div className="brief"><span>Мир</span><strong>{selectedWorld?.name||'Ещё выбираем'}</strong></div><div className="brief"><span>Образы героев</span><strong>{variants.filter(Boolean).length} из 3 выбраны</strong></div><div className="brief"><span>Первый выпуск</span><strong>20 страниц · план</strong></div><p>Выбор хранится до перезагрузки страницы. В финале скачайте набросок, чтобы сохранить его.</p></aside></div></main>}
 <section className={'alina-guide glass '+(active?'during-flow ':'')+(minimized?'minimized ':'')+(voice.speaking?'speaking':'')} aria-label="Алина — цифровая ведущая"><div className="guide-top"><img src="/alina.png" alt="Образ цифровой ведущей Алины"/><div><strong>Алина</strong><span>{voice.listening?'Слушаю…':voice.speaking?'Говорю…':'Помогу придумать историю'}</span></div><button className="guide-collapse" aria-label={minimized?'Развернуть Алину':'Свернуть Алину'} onClick={()=>setMinimized(!minimized)}>{minimized?<ChevronUp/>:<ChevronDown/>}</button></div>{!minimized&&<><p className="guide-line">{line}</p><div className="guide-controls"><Button variant="outline" className="outline" onClick={()=>{if(voiceOn){setVoiceOn(false);voice.stop();}else setVoiceOn(true);}}>{voiceOn?<VolumeX/>:<Volume2/>}{voiceOn?'Выключить голос':'Включить голос'}</Button>{voiceOn&&<button className="back" onClick={()=>voice.speak(line)} aria-label="Повторить реплику"><Volume2 size={17}/></button>}</div>{!active&&<Button className="primary" onClick={()=>{setMinimized(false);onStart();}}>Давайте познакомимся <ArrowRight/></Button>}<span className="guide-disclaimer">Цифровой образ · подготовленный диалог</span></>}{voice.error&&<p className="voice-error" role="status">{voice.error}</p>}</section>
 </>;
}

