import type { AgentSpec } from "./types";

export const agentRegistry: AgentSpec[] = [
  {
    id: "AG-001",
    name: "ALINA Analyst",
    role: "Research & evidence analyst",
    description: "Research, RAG, claims, sources, timelines and evidence packaging.",
    status: "active",
    capabilities: ["research", "rag"],
    promptIds: ["father.analyst.research"],
    toolIds: ["knowledge_search", "source_trace"],
    knowledgeScopes: ["research", "sources", "claims", "timelines"],
    accepts: ["ResearchRequest"],
    produces: ["ResearchPacket"],
    mayCallAgents: ["AG-009", "AG-010"],
    restrictions: ["Does not generate final media assets."],
    ownerDomain: "alina_analyst",
  },
  {
    id: "AG-002",
    name: "Content Director",
    role: "Content orchestration",
    description: "Turns a validated ContentBrief into an execution plan.",
    status: "active",
    capabilities: ["content_generation"],
    promptIds: ["father.content.director"],
    toolIds: ["brief_validator", "job_router"],
    knowledgeScopes: ["content_briefs", "generation_policy"],
    accepts: ["ContentBrief"],
    produces: ["ContentPlan"],
    mayCallAgents: ["AG-003", "AG-004", "AG-005", "AG-006", "AG-007", "AG-008", "AG-009"],
    restrictions: ["Cannot modify verified factual constraints."],
    ownerDomain: "content_generator",
  },
  {
    id: "AG-003",
    name: "Prompt Engineer",
    role: "Prompt lifecycle owner",
    description: "Designs, versions, evaluates and promotes prompts.",
    status: "active",
    capabilities: ["prompt_engineering"],
    promptIds: ["father.prompt.engineer"],
    toolIds: ["prompt_registry", "eval_runner"],
    knowledgeScopes: ["prompts", "evals", "provider_profiles"],
    accepts: ["PromptChangeRequest"],
    produces: ["PromptVersion", "EvalReport"],
    mayCallAgents: ["AG-009", "AG-010"],
    restrictions: ["Cannot bypass safety or factual constraints."],
    ownerDomain: "father",
  },
  {
    id: "AG-004",
    name: "Persona Director",
    role: "Persona consistency",
    description: "Maintains identity, age presets, wardrobe and continuity.",
    status: "active",
    capabilities: ["persona"],
    promptIds: ["father.persona.director"],
    toolIds: ["persona_registry"],
    knowledgeScopes: ["personas", "identity", "wardrobe"],
    accepts: ["PersonaTask"],
    produces: ["PersonaSpec"],
    mayCallAgents: ["AG-009"],
    restrictions: ["Cannot alter protected identity anchors without approval."],
    ownerDomain: "content_generator",
  },
  {
    id: "AG-005",
    name: "Scene Director",
    role: "Scene & storyboard planner",
    description: "Plans scenes, camera, emotion, pose, environment and continuity.",
    status: "active",
    capabilities: ["scene", "persona"],
    promptIds: ["father.scene.director"],
    toolIds: ["scene_registry", "storyboard_planner"],
    knowledgeScopes: ["scenes", "continuity", "camera"],
    accepts: ["ContentPlan", "PersonaSpec"],
    produces: ["SceneSpec[]"],
    mayCallAgents: ["AG-004", "AG-009"],
    restrictions: ["Cannot introduce unsupported factual events."],
    ownerDomain: "content_generator",
  },
  {
    id: "AG-006",
    name: "Newsletter Producer",
    role: "Newsletter generation",
    description: "Creates structured newsletter output from approved briefs.",
    status: "active",
    capabilities: ["newsletter", "content_generation"],
    promptIds: ["father.newsletter"],
    toolIds: ["openai_responses"],
    knowledgeScopes: ["newsletter_templates"],
    accepts: ["ContentBrief"],
    produces: ["NewsletterOutput"],
    mayCallAgents: ["AG-009"],
    restrictions: ["No unsupported claims."],
    ownerDomain: "content_generator",
  },
  {
    id: "AG-007",
    name: "Podcast Producer",
    role: "Podcast script & TTS",
    description: "Creates spoken scripts and routes approved text to TTS.",
    status: "active",
    capabilities: ["podcast", "content_generation"],
    promptIds: ["father.podcast"],
    toolIds: ["openai_responses", "openai_tts"],
    knowledgeScopes: ["podcast_templates", "voice_profiles"],
    accepts: ["ContentBrief"],
    produces: ["PodcastOutput", "AudioAsset"],
    mayCallAgents: ["AG-009"],
    restrictions: ["AI-generated voice must be disclosed."],
    ownerDomain: "content_generator",
  },
  {
    id: "AG-008",
    name: "Video Producer",
    role: "Avatar video production",
    description: "Runs avatar/voice selection, Video Agent jobs and polling.",
    status: "active",
    capabilities: ["video", "content_generation"],
    promptIds: ["father.video.producer"],
    toolIds: ["heygen_v3"],
    knowledgeScopes: ["provider_catalogs", "video_jobs"],
    accepts: ["ContentBrief", "SceneSpec[]"],
    produces: ["VideoJob", "VideoAsset"],
    mayCallAgents: ["AG-004", "AG-005", "AG-009"],
    restrictions: ["Provider secrets remain server-side."],
    ownerDomain: "content_generator",
  },
  {
    id: "AG-009",
    name: "QA Critic",
    role: "Quality evaluator",
    description: "Checks outputs against facts, brief, prompt contract and acceptance criteria.",
    status: "active",
    capabilities: ["qa"],
    promptIds: ["father.qa.critic"],
    toolIds: ["eval_runner"],
    knowledgeScopes: ["acceptance_criteria", "eval_cases"],
    accepts: ["GeneratedArtifact", "ResearchPacket", "ContentBrief"],
    produces: ["EvalReport"],
    mayCallAgents: ["AG-003"],
    restrictions: ["Does not silently rewrite production output."],
    ownerDomain: "shared",
  },
  {
    id: "AG-010",
    name: "Security Reviewer",
    role: "Security & policy gate",
    description: "Reviews secrets, provider boundaries, unsafe actions and auditability.",
    status: "active",
    capabilities: ["security", "qa"],
    promptIds: ["father.security.reviewer"],
    toolIds: ["policy_checker", "audit_log"],
    knowledgeScopes: ["security_policy", "provider_policy"],
    accepts: ["JobPlan", "ProviderConfig"],
    produces: ["SecurityDecision"],
    mayCallAgents: [],
    restrictions: ["Fail closed on secret leakage or unsafe provider configuration."],
    ownerDomain: "shared",
  },
];

export function getAgent(id: string) {
  return agentRegistry.find((agent) => agent.id === id);
}
