'use client';
import { useState, useCallback } from 'react';
import { Studio } from './studio';
import { AgentTools } from './agent-tools';
import { NeuralHud } from './neural-hud';
import { ArrowUpRight, ArrowRight, Sparkles, Layers3, Film, Orbit } from 'lucide-react';
import { Button } from '@/components/ui/button';
export default function Home(){
const [chat,setChat]=useState(false);
const begin=useCallback(()=>{setChat(true);window.scrollTo({top:0,behavior:'smooth'});},[]);
return <div className="shell"><NeuralHud/><AgentTools open={begin}/><header><a className="brand" href="#" onClick={e=>{e.preventDefault();setChat(false);}}><Orbit/>BOOK·CRAFT<span>●</span></a><nav aria-label="Основная навигация"><a href="#project" onClick={()=>setChat(false)}>Пилотный выпуск</a><a href="#process" onClick={()=>setChat(false)}>Как это работает</a></nav><Button variant="outline" className="outline" onClick={begin}>Обсудить идею <ArrowUpRight/></Button></header>
{!chat?<main><section className="hero"><div><p className="eyebrow"><i/>NEURAL STORY STUDIO / ДИКИЕ ИДЕИ</p><h1>У каждой идеи<br/>есть <em>свой мир.</em></h1><p className="description">Живая AI-студия: поговорите с Алиной, соберите мир и героев, а затем превратите замысел в структуру книги, комикса и короткого кино.</p><div className="actions"><Button className="primary" onClick={begin}>Создать свою историю <ArrowUpRight/></Button><a href="#project">Посмотреть пилот <ArrowRight size={17}/></a></div><p className="footnote"><Sparkles size={16}/>Голос → смысл → мир → герои → визуальный концепт.</p></div><a className="art" href="#project" aria-label="Пересечение трёх лун — пилотный выпуск"><img src="/academy-arrival.png" alt="Молодой рейнджер на пути к светящейся академии в далёком мире"/><div className="shade"/><span className="art-tag"><i/>DEMO / ВИЗУАЛЬНЫЕ КОНЦЕПТЫ ПОДГОТОВЛЕНЫ</span><div className="caption"><span>ПО МОТИВАМ «ТРЁХ МУШКЕТЁРОВ»</span><h2>Пересечение<br/>трёх лун</h2><p>Выпуск 01 / Порог академии</p></div><span className="round-arrow"><ArrowUpRight/></span></a></section>
<section id="process" className="steps">{[['01','Диалог с Алиной','Голосом или текстом формируем замысел'],['02','Живой мир','Орбита вариантов собирает атмосферу и героев'],['03','BOOK·CRAFT Studio','Концепция раскрывается в рабочую студию']].map(([n,t,d])=><div key={n}><span className="number">{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowRight size={18}/></div>)}</section>
<section id="project" className="project"><div className="section-heading"><div><p className="eyebrow">ВСЕЛЕННАЯ В РАЗРАБОТКЕ</p><h2>Большая история.<br/>Первый шаг.</h2></div><p>Один герой. Три храма.<br/>Обещание, которое изменит всё.</p></div><div className="cards"><article className="glass story"><span className="label">01 / ЗАВЯЗКА</span><h3>До берета —<br/>целая жизнь.</h3><p>Кай Арден едет в академию императорских рейнджеров. Отец обещал ему легендарное оружие из чужого храма. Но его угасшую силу можно вернуть только на трёх лунах.</p><p>Впереди — трое будущих товарищей, испытания и предложение спецслужбы, от которого трудно отказаться.</p><div className="tags"><span>Киберпанк</span><span>Приключения</span><span>По мотивам классики</span></div></article><article className="glass output"><Layers3 size={28}/><span className="label">ПЛАН ВЫПУСКА</span><h3>20 страниц</h3><p>Дорога героя и прибытие в академию. Согласованный сценарий, единый облик персонажей.</p><small>○ Подготовка истории</small></article><article className="glass output"><Film size={28}/><span className="label">ПЛАН ТИЗЕРА</span><h3>15–30 секунд</h3><p>Короткое знакомство с миром из утверждённых кадров комикса.</p><small>○ После согласования кадров</small></article></div></section>
<section className="glass cta"><div><p className="eyebrow">СЛЕДУЮЩАЯ ИСТОРИЯ — ВАША</p><h2>А что, если…</h2><p>Продолжите фразу. С этого всё и начинается.</p></div><Button className="primary" onClick={begin}>Обсудить с Алиной <ArrowUpRight/></Button></section></main>:null}<Studio active={chat} onStart={begin} onBack={()=>setChat(false)}/>
<footer><span>BOOK·CRAFT ●</span><p>Живая AI-студия историй.</p><span>Neural Studio · demo 2026</span></footer></div>;
}
