'use client';
import {useState,useEffect} from 'react';
import {OrbitStudio} from './orbit-studio';
import {ResearchLab} from './research-lab';
import {NarrativeLab} from './narrative-lab';
import {ArrowRight,ArrowLeft,Volume2,VolumeX,Check,Download,ChevronDown,ChevronUp} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {interview,worlds,heroes,looks,pages} from './story-data';
import {useVoice} from './use-voice';

const greeting='Я Алина. Помогаю доводить творческие идеи до стадии продакшена: книги, сценарии, комиксы, визуальные истории и цифровые проекты. Сначала поймём вашу идею, затем проверим её по исследованиям и сопоставимым проектам, соберём STORY DNA и только после этого перейдём к миру, героям и выпуску.';

export function Studio({active,onStart,onBack}:{active:boolean;onStart:()=>void;onBack:()=>void}){
 const [stage,setStage]=useState(0),[answers,setAnswers]=useState<string[]>([]),[draft,setDraft]=useState(''),[researchPack,setResearchPack]=useState<string[]>([]),[world,setWorld]=useState(''),[variants,setVariants]=useState<string[]>(['','','']),[names,setNames]=useState(heroes.map(h=>h.name)),[storyDna,setStoryDna]=useState<string[]>([]),[voiceOn,setVoiceOn]=useState(false),[minimized,setMinimized]=useState(false),[approved,setApproved]=useState(false),[downloaded,setDownloaded]=useState(false);
 useEffect(()=>{if(window.matchMedia('(max-width: 760px)').matches)setMinimized(true);},[]);
 const voice=useVoice(setDraft);const q=answers.length;const selectedWorld=worlds.find(w=>w.id===world);
 const line=!active?greeting:
  stage===0?(q<3?((q===1&&answers[0]==='Для читателей и продаж'?'Начнём с короткого выпуска и проверим интерес аудитории. ':q===1&&answers[0]==='Для себя или в подарок'?'Тогда сделаем историю личной и узнаваемой. ':'')+interview[q].speech):'Основа есть. Теперь я соберу вокруг неё исследовательский слой и покажу, на что можно опираться.'):
  stage===1?'Я разделяю факты, рыночные сигналы и гипотезы. Вы увидите источники, сопоставимые проекты и ограничения каждого вывода.':
  stage===2?'Исследование сохранено. Теперь я предлагаю драматургические механики, а решение остаётся за вами.':
  stage===3?'Перед вами три разных мира одной истории. Выберите атмосферу, в которой хотите встретить героев.':
  stage===4?'Для каждого героя выберите один из трёх образов. Имена можно изменить.':
  stage===5?'Проверим выбор. Подтвердите Research Pack, STORY DNA, мир и героев, чтобы открыть план первых двадцати страниц.':
  'Вот план первого выпуска. В демо визуальные концепты подготовлены заранее; дальше этот контур должен вести в полноценную BOOK·CRAFT Studio.';
 useEffect(()=>{if(voiceOn)voice.speak(line);else voice.stop();return voice.stop;},[line,voiceOn,voice.speak,voice.stop]);
 const choose=(answer:string)=>{voice.stop();setAnswers([...answers,answer]);setDraft('');setApproved(false);};
 const go=(n:number)=>{voice.stop();setStage(n);window.scrollTo({top:0,behavior:'smooth'});};
 const orbitGo=(n:number)=>{
  if(stage===0){go(n===1?1:n);return;}
  if(stage===3){if(n===0)go(2);else if(n===2)go(4);else go(n);return;}
  if(stage===4){if(n===1)go(3);else if(n===3)go(5);else go(n);return;}
  go(n);
 };
 const exportBrief=()=>{const rename=(s:string)=>heroes.reduce((t,h,i)=>t.replaceAll(h.name,names[i]||h.name).replaceAll(h.name.split(' ')[0],(names[i]||h.name).split(' ')[0]),s);const result=['ДИКИЕ ИДЕИ — Пересечение трёх лун','Концепция согласована в прототипе. Производство не запущено.','',...answers.map((a,i)=>interview[i].title+' '+a),'','RESEARCH PACK',...researchPack.map(x=>'• '+x),'','STORY DNA',...storyDna.map(x=>'• '+x),'','Мир: '+selectedWorld?.name,...heroes.map((h,i)=>(names[i]||h.name)+' — '+looks[Number(variants[i])]),'','ПЛАН 20 СТРАНИЦ — требует покадрового сценария',...pages.map(([t,a,r],i)=>`${i+1}. ${t}\n${rename(a)}\n${rename(r)}`)].join('\n\n');const url=URL.createObjectURL(new Blob([result],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Дикие-идеи-концепция-и-20-страниц.txt';a.click();URL.revokeObjectURL(url);setDownloaded(true);};
 const rename=(s:string)=>heroes.reduce((t,h,i)=>t.replaceAll(h.name,names[i]||h.name).replaceAll(h.name.split(' ')[0],(names[i]||h.name).split(' ')[0]),s);
 const orbitStage=stage===0?0:stage===3?1:2;
 const idea=answers.filter(Boolean).join(' · ');
 return <>
 {active&&<main className="studio"><button className="back" onClick={()=>{voice.stop();setVoiceOn(false);onBack();}}><ArrowLeft size={16}/>На первую страницу</button><div className="journey" aria-label="Этапы создания">{['Идея','Research','Story DNA','Мир','Герои','Согласование','20 страниц'].map((s,i)=><span className={i===stage?'current':i<stage?'complete':''} key={s}>{i<stage?<Check size={14}/>:<b>{String(i+1).padStart(2,'0')}</b>}{s}</span>)}</div>
 {stage===1?<ResearchLab idea={idea} onBack={()=>go(0)} onComplete={pack=>{setResearchPack(pack);go(2);}}/>:
 stage===2?<NarrativeLab onBack={()=>go(1)} onComplete={mods=>{setStoryDna(mods);go(3);}}/>:
 (stage===0||stage===3||stage===4)?<OrbitStudio stage={orbitStage} answers={answers} world={world} variants={variants} names={names} draft={draft} line={line} voiceOn={voiceOn} speaking={voice.speaking} listening={voice.listening} error={voice.error} setDraft={setDraft} choose={choose} go={orbitGo} backAnswer={()=>{setAnswers(answers.slice(0,-1));setDraft('');setApproved(false);}} selectWorld={v=>{setWorld(v);setVariants(['','','']);setApproved(false);}} selectHero={(i,v)=>{const n=[...variants];n[i]=v;setVariants(n);setApproved(false);}} setName={(i,v)=>{const n=[...names];n[i]=v;setNames(n);setApproved(false);}} toggleVoice={()=>{if(voiceOn){setVoiceOn(false);voice.stop();}else setVoiceOn(true);}} repeat={()=>voice.speak(line)} microphone={()=>voice.listening?voice.stop():voice.listen()}/>:
 <div className="studio-layout"><section className="studio-work glass"><p className="eyebrow">ПЕРЕСЕЧЕНИЕ ТРЁХ ЛУН · ПИЛОТ</p>
 {stage===5&&<><h1>Всё ли совпало<br/>с вашей идеей?</h1><p className="studio-lead">Перед сценарием фиксируем исследование, сюжетный геном, мир и персонажей. Ничего не отправляем в производство без вашего подтверждения.</p><div className="review-world"><div className="world-picture" style={{backgroundImage:'url(/worlds.png)',backgroundPosition:`${worlds.findIndex(w=>w.id===world)*50}% center`}}/><h2>{selectedWorld?.name}</h2></div><div className="review-heroes">{heroes.map((h,i)=><div key={h.name}><div className="character-picture" role="img" aria-label={names[i]} style={{backgroundImage:'url(/heroes.png)',backgroundPosition:`${i*50}% ${Number(variants[i])*50}%`}}/><h3>{names[i]}</h3><p>{looks[Number(variants[i])]}</p></div>)}</div><div className="brief"><span>RESEARCH PACK</span><strong>{researchPack.length?researchPack.join(' · '):'Не собран'}</strong></div><div className="brief"><span>STORY DNA</span><strong>{storyDna.length?storyDna.join(' · '):'Не выбрано'}</strong></div>{answers.map((a,i)=><div className="brief" key={i}><span>{interview[i].title}</span><strong>{a}</strong></div>)}<p className="concept-note">История: молодой герой из низов попадает в боевую академию. Семейное оружие деактивировано после смерти носителя; его добровольная привязка требует пройти три храма утерянных цивилизаций. Дед был героем, отец отказался от традиции, а спецслужбы давно следят за линией наследования.</p><div className="stage-actions"><button className="back" onClick={()=>go(4)}><ArrowLeft size={16}/>Изменить героев</button><Button className="primary" onClick={()=>{setApproved(true);go(6);}}>Согласовать и открыть план <Check/></Button></div></>}
 {stage===6&&approved&&<><p className="approval"><Check size={16}/>Концепция согласована в этой сессии</p><h1>Выпуск 01.<br/>Порог академии.</h1><p className="studio-lead">План первых 20 страниц. Это сценарная основа, ещё не нарисованный комикс.</p><div className="page-plan">{pages.map(([title,action,replica],i)=><article key={title}><span className="page-index">{String(i+1).padStart(2,'0')}</span><div><h2>{rename(title)}</h2><p>{rename(action)}</p><blockquote>{rename(replica)}</blockquote></div></article>)}</div><div className="production-note"><h2>Следующий этап — BOOK·CRAFT Studio</h2><p>Уточняем причинный граф, арки персонажей и покадровый сценарий. В демо изображения подготовлены заранее; в production этот слой подключается к генерационному и редакторскому контуру.</p></div><div className="stage-actions"><button className="back" onClick={()=>go(5)}><ArrowLeft size={16}/>К концепции</button><Button className="primary" onClick={exportBrief}>{downloaded?<Check/>:<Download/>}{downloaded?'План скачан':'Скачать проектный пакет'}</Button></div></>}
 </section><aside className="studio-summary"><p className="eyebrow">PROJECT MEMORY</p><h2>История<br/>обретает форму.</h2><div className="brief"><span>Research</span><strong>{researchPack.length} направления</strong></div><div className="brief"><span>Story DNA</span><strong>{storyDna.length} модулей</strong></div><div className="brief"><span>Мир</span><strong>{selectedWorld?.name||'Ещё выбираем'}</strong></div><div className="brief"><span>Образы героев</span><strong>{variants.filter(Boolean).length} из 3 выбраны</strong></div><div className="brief"><span>Первый выпуск</span><strong>20 страниц · план</strong></div><p>Подтверждённые решения сохраняются как отдельные слои проекта, а не теряются в истории чата.</p></aside></div>}
 </main>}
 {(!active||stage>=5)&&<section className={'alina-guide glass '+(active?'during-flow ':'')+(minimized?'minimized ':'')+(voice.speaking?'speaking':'')} aria-label="Алина — цифровая ведущая"><div className="guide-top"><img src="/alina.png" alt="Образ цифровой ведущей Алины"/><div><strong>Алина</strong><span>{voice.listening?'Слушаю…':voice.speaking?'Говорю…':'AI-продюсер проекта'}</span></div><button className="guide-collapse" aria-label={minimized?'Развернуть Алину':'Свернуть Алину'} onClick={()=>setMinimized(!minimized)}>{minimized?<ChevronUp/>:<ChevronDown/>}</button></div>{!minimized&&<><p className="guide-line">{line}</p><div className="guide-controls"><Button variant="outline" className="outline" onClick={()=>{if(voiceOn){setVoiceOn(false);voice.stop();}else setVoiceOn(true);}}>{voiceOn?<VolumeX/>:<Volume2/>}{voiceOn?'Выключить голос':'Включить голос'}</Button>{voiceOn&&<button className="back" onClick={()=>voice.speak(line)} aria-label="Повторить реплику"><Volume2 size={17}/></button>}</div>{!active&&<Button className="primary" onClick={()=>{setMinimized(false);onStart();}}>Давайте познакомимся <ArrowRight/></Button>}<span className="guide-disclaimer">Research-backed demo · решения подтверждает пользователь</span></>}{voice.error&&<p className="voice-error" role="status">{voice.error}</p>}</section>}
 </>;
}
