'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,BrainCircuit,Cable,Database,FileCode2,KeyRound,LockKeyhole,RefreshCw,Settings,ShieldCheck,UsersRound,X} from 'lucide-react';

type Role='admin'|'security';
type Tab='models'|'prompts'|'knowledge'|'database'|'access'|'operations';
type Model={id:string;provider:string;model:string;label:string;available:boolean;note:string;capabilities:string[]};
type ModelPolicy={enabled:boolean;security:'approved'|'review'|'blocked'};
type PromptPolicy={active:boolean;review:'approved'|'pending'|'blocked';version:number};
type KbPolicy={enabled:boolean;securityHold:boolean};
type ControlState={version:number;updatedAt:string|null;modelPolicies:Record<string,ModelPolicy>;promptPolicies:Record<string,PromptPolicy>;kbPolicies:Record<string,KbPolicy>;routeOverrides:Record<string,string>;database:{vectorIndexEnabled:boolean;backupEnabled:boolean;objectStorageEnabled:boolean}};
type AuditEvent={eventId:string;at:string;role:Role;action:string;target:string;reason:string;stateVersion:number};
type PromptVersion={version:number;body:string;review:'approved'|'pending'|'blocked';createdAt:string|null;createdBy:string;reason:string;source:'builtin'|'runtime'};
type PromptRegistryItem={id:string;task:string;source:string;status:string;editable:boolean;activeVersion:number;latestVersion:number;latestReview:string;versionCount:number;activeBody?:string;latestBody?:string;versions?:PromptVersion[];updatedAt?:string|null};
type Config={
 schemaVersion?:string;mode:string;warning:string;roles?:string[];
 auth:{adminConfigured:boolean;securityConfigured:boolean;tokenValuesExposed:boolean};
 routableTasks:string[];
 prompts:{id:string;task:string;source:string;status:string;editable:boolean;version:number;latestVersion?:number;versionCount?:number;reviewStatus:string;active?:boolean;latestReview?:string}[];
 promptRegistry?:PromptRegistryItem[];
 knowledgeBases:{id:string;label:string;path:string;kind:string;status:string}[];
 control:ControlState;
 database:{target:string;configured:boolean;connectionValueExposed:boolean;eventAuditConfigured:boolean;objectStorage:string};
 security:{secretsExposed:boolean;promptBodiesExposed:boolean;privilegedWritesEnabled:boolean;auditRequired:boolean;modelIntegrity:string;kbIntegrity:string};
 audit:AuditEvent[];
};

type MutationValue=unknown;
const tabs:{id:Tab;label:string;icon:typeof Settings}[]=[
 {id:'models',label:'Модели',icon:BrainCircuit},
 {id:'prompts',label:'Промты',icon:FileCode2},
 {id:'knowledge',label:'Базы знаний',icon:Cable},
 {id:'database',label:'База данных',icon:Database},
 {id:'access',label:'Доступ / RBAC',icon:UsersRound},
 {id:'operations',label:'Контроль',icon:Activity},
];

export function AdminSecurityConsole(){
 const [open,setOpen]=useState(false),[role,setRoleState]=useState<Role>('admin'),[tab,setTab]=useState<Tab>('models');
 const [models,setModels]=useState<Model[]>([]),[routes,setRoutes]=useState<Record<string,string[]>>({}),[config,setConfig]=useState<Config|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tokens,setTokens]=useState<Record<Role,string>>({admin:'',security:''}),[reason,setReason]=useState('Изменение через ALINA Control Center');
 const setRole=(next:Role)=>{setRoleState(next);setConfig(c=>c?{...c,promptRegistry:undefined,security:{...c.security,promptBodiesExposed:false}}:c);setNotice('');setError('');};
 const refresh=async()=>{
  setLoading(true);setError('');
  try{const [llm,adm]=await Promise.all([fetch('/api/llm').then(r=>r.json()),fetch('/api/admin/config').then(r=>r.json())]);setModels(Array.isArray(llm?.models)?llm.models:[]);setRoutes(llm?.routes&&typeof llm.routes==='object'?llm.routes:{});setConfig(adm);}catch(e){setError(e instanceof Error?e.message:'Не удалось получить конфигурацию.');}finally{setLoading(false);}
 };
 useEffect(()=>{if(open&&!config&&!loading)void refresh();},[open]);
 const online=useMemo(()=>models.filter(m=>m.available&&m.id!=='auto').length,[models]);
 const providers=useMemo(()=>Array.from(new Set(models.filter(m=>m.id!=='auto').map(m=>m.provider))),[models]);
 const roleConfigured=role==='admin'?Boolean(config?.auth?.adminConfigured):Boolean(config?.auth?.securityConfigured);
 const canWrite=Boolean(roleConfigured&&tokens[role].trim()&&reason.trim().length>=3&&!loading);
 const mutate=async(action:string,target:string,value:MutationValue)=>{
  if(!roleConfigured){setError(`Для роли ${role} не настроен серверный token.`);return;}
  if(!tokens[role].trim()){setError('Введите role token. Он хранится только в памяти этой вкладки.');return;}
  if(reason.trim().length<3){setError('Укажите причину изменения для audit log.');return;}
  setLoading(true);setError('');setNotice('');
  try{const r=await fetch('/api/admin/config',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${tokens[role].trim()}`},body:JSON.stringify({role,action,target,value,reason:reason.trim()})});const data=await r.json();if(!r.ok)throw new Error(data?.error||`Control API HTTP ${r.status}`);setNotice(`${action} → ${target} · state v${data?.control?.version??'?'}`);await refresh();}catch(e){setError(e instanceof Error?e.message:'Ошибка изменения конфигурации.');}finally{setLoading(false);}
 };
 const loadPromptBodies=async()=>{
  if(!roleConfigured||!tokens[role].trim()){setError('Для чтения и review системных промтов введите token выбранной роли.');return;}
  setLoading(true);setError('');
  try{const r=await fetch(`/api/admin/config?include_prompt_bodies=1&role=${role}`,{headers:{authorization:`Bearer ${tokens[role].trim()}`}});const data=await r.json();if(!r.ok)throw new Error(data?.error||`Prompt Registry HTTP ${r.status}`);setConfig(data);setNotice(`Prompt Registry открыт для роли ${role.toUpperCase()}.`);}catch(e){setError(e instanceof Error?e.message:'Не удалось открыть Prompt Registry.');}finally{setLoading(false);}
 };
 return <>
  <button className="system-gear" type="button" onClick={()=>setOpen(true)} aria-label="Открыть системные настройки"><Settings size={21}/><span>SYS</span></button>
  {open?<div className="system-console-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}>
   <aside className="system-console" aria-label="Центр управления ALINA">
    <header className="system-console-head system-sticky-top"><div><span className="system-kicker">ALINA CONTROL CENTER</span><h2>{role==='admin'?'Администратор':'ИБ / AI Security'}</h2><p>Модели, промты, базы знаний, данные, RBAC и аудит.</p></div><div className="system-head-actions"><button type="button" onClick={()=>void refresh()} title="Обновить"><RefreshCw size={17} className={loading?'spin':''}/></button><button type="button" onClick={()=>setOpen(false)} title="Закрыть"><X size={18}/></button></div></header>
    <div className="system-role-switch system-sticky-role" aria-label="Роль панели"><button className={role==='admin'?'active':''} type="button" onClick={()=>setRole('admin')}><Settings size={16}/> Администратор</button><button className={role==='security'?'active':''} type="button" onClick={()=>setRole('security')}><ShieldCheck size={16}/> ИБ / AI Security</button></div>
    <div className="system-console-body">
     <nav className="system-tabs" aria-label="Разделы настроек">{tabs.map(t=>{const I=t.icon;return <button key={t.id} className={tab===t.id?'active':''} type="button" onClick={()=>setTab(t.id)}><I size={17}/><span>{t.label}</span></button>;})}</nav>
     <section className="system-content">
      <div className={'system-preview-note '+(config?.mode==='controlled_writes'?'live':'')}><LockKeyhole size={15}/><span>{config?.warning||'Загрузка режима управления…'}</span></div>
      <div className="system-auth-card"><div><strong>{role==='admin'?'ADMIN TOKEN':'SECURITY TOKEN'}</strong><small>{roleConfigured?'серверная роль настроена':'серверная роль не настроена'}</small></div><input type="password" value={tokens[role]} onChange={e=>setTokens(v=>({...v,[role]:e.target.value}))} placeholder={roleConfigured?'Введите token роли':'Сначала задайте token в .env.local'} autoComplete="off"/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Причина изменения"/></div>
      {error?<div className="system-alert error">{error}</div>:null}{notice?<div className="system-preview-note live"><ShieldCheck size={15}/><span>{notice}</span></div>:null}
      {tab==='models'?<ModelsPanel models={models} routes={routes} online={online} providers={providers} role={role} config={config} canWrite={canWrite} mutate={mutate}/>:null}
      {tab==='prompts'?<PromptsPanel config={config} role={role} canWrite={canWrite} mutate={mutate} loadBodies={loadPromptBodies}/>:null}
      {tab==='knowledge'?<KnowledgePanel config={config} role={role} canWrite={canWrite} mutate={mutate}/>:null}
      {tab==='database'?<DatabasePanel config={config} role={role} canWrite={canWrite} mutate={mutate}/>:null}
      {tab==='access'?<AccessPanel config={config} role={role}/>:null}
      {tab==='operations'?<OperationsPanel config={config} models={models} role={role}/>:null}
     </section>
    </div>
   </aside>
  </div>:null}
 </>;
}

function ModelsPanel({models,routes,online,providers,role,config,canWrite,mutate}:{models:Model[];routes:Record<string,string[]>;online:number;providers:string[];role:Role;config:Config|null;canWrite:boolean;mutate:(a:string,t:string,v:MutationValue)=>Promise<void>}){
 const control=config?.control;const tasks=config?.routableTasks||['dialogue','synthesis','architecture','translation','kb_extract','kb_validate'];
 return <div className="system-stack"><div className="system-summary-grid"><Metric label="Доступно моделей" value={String(online)}/><Metric label="Провайдеров" value={String(providers.length)}/><Metric label="Control version" value={String(control?.version||1)}/></div>
  <div className="system-card"><div className="system-card-title"><BrainCircuit size={18}/><div><h3>Model Registry</h3><p>{role==='security'?'Контроль доверия и допуска моделей.':'Состояние моделей и эксплуатационный enable/disable.'}</p></div></div><div className="system-table">{models.filter(m=>m.id!=='auto').map(m=>{const p=control?.modelPolicies?.[m.id]||{enabled:true,security:'review' as const};return <div className="system-row system-row-actions" key={m.id}><div><strong>{m.label}</strong><small>{m.provider} · {m.model}</small></div><div className="system-tags">{m.capabilities?.slice(0,4).map(c=><span key={c}>{c}</span>)}</div><div className="system-action-cell">{role==='admin'?<button disabled={!canWrite} className={p.enabled?'mini ok':'mini off'} onClick={()=>void mutate('model.set_enabled',m.id,!p.enabled)}>{p.enabled?'ENABLED':'DISABLED'}</button>:<select disabled={!canWrite} value={p.security} onChange={e=>void mutate('model.set_security',m.id,e.target.value)}><option value="approved">APPROVED</option><option value="review">REVIEW</option><option value="blocked">BLOCKED</option></select>}<b className={m.available?'ok':'off'}>{m.available?'READY':'OFF'}</b></div></div>})}</div></div>
  <div className="system-card"><div className="system-card-title"><BrainCircuit size={18}/><div><h3>Routing by task</h3><p>{role==='admin'?'Можно закрепить любую разрешённую доступную модель первой в AUTO-chain.':'ИБ видит фактические override и может блокировать модель в Model Registry.'}</p></div></div>{tasks.map(task=>{const selected=control?.routeOverrides?.[task]||'';return <div className="system-row" key={task}><div><strong>{task}</strong><small>{selected||'AUTO · без закрепления'}</small></div><span className="system-state-label">{selected?'PINNED':'AUTO'}</span><div className="system-action-cell">{role==='admin'?<select disabled={!canWrite} value={selected} onChange={e=>void mutate('route.set_override',task,e.target.value)}><option value="">AUTO / provider order</option>{models.filter(m=>m.id!=='auto'&&m.available&&m.capabilities?.includes(task)).map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select>:<strong>{selected||'AUTO'}</strong>}</div></div>})}</div>
  <div className="system-card"><h3>Effective routing by task</h3><div className="system-routes">{Object.entries(routes).map(([task,chain])=><div key={task}><span>{task}</span><code>{chain.join(' → ')||'нет разрешённой модели'}</code></div>)}</div><p className="system-muted">Фактический порядок уже учитывает Admin override и AI Security policy. Недоступная или заблокированная закреплённая модель автоматически не ломает fallback-chain.</p></div>
 </div>;
}

function PromptsPanel({config,role,canWrite,mutate,loadBodies}:{config:Config|null;role:Role;canWrite:boolean;mutate:(a:string,t:string,v:MutationValue)=>Promise<void>;loadBodies:()=>Promise<void>}){
 const registry=config?.promptRegistry||[];const editable=registry.filter(p=>p.editable);const [selected,setSelected]=useState('');const [draft,setDraft]=useState('');
 const current=registry.find(p=>p.id===selected)||editable[0]||registry[0];
 useEffect(()=>{if(registry.length&&!selected)setSelected((editable[0]||registry[0]).id);},[registry.length,selected]);
 useEffect(()=>{if(current)setDraft(role==='admin'?(current.activeBody||''):(current.latestBody||current.activeBody||''));},[current?.id,current?.activeVersion,current?.latestVersion,role]);
 const reload=async()=>{await loadBodies();};
 const createDraft=async()=>{if(!current)return;await mutate('prompt.create_draft',current.id,{body:draft});await reload();};
 const review=async(version:number,state:'approved'|'blocked')=>{if(!current)return;await mutate('prompt.review_version',current.id,{version,review:state});await reload();};
 const activate=async(version:number)=>{if(!current)return;await mutate('prompt.activate_version',current.id,version);await reload();};
 return <div className="system-stack"><div className="system-card"><div className="system-card-title"><FileCode2 size={18}/><div><h3>Prompt Registry</h3><p>{role==='security'?'Security review и блокировка prompt policy.':'Активация/деактивация промтов и versioned content workflow.'}</p></div></div>{config?.prompts?.map(p=>{const state=config.control?.promptPolicies?.[p.id]||{active:p.status==='active',review:p.reviewStatus as 'approved'|'pending'|'blocked',version:p.version};return <div className="system-row system-row-actions" key={p.id}><div><strong>{p.id}</strong><small>{p.task} · {p.source} · active v{p.version} · versions {p.versionCount||1}</small></div><span className="system-state-label">{state.review.toUpperCase()}</span><div className="system-action-cell">{role==='admin'?<button disabled={!canWrite} className={state.active?'mini ok':'mini off'} onClick={()=>void mutate('prompt.set_active',p.id,!state.active)}>{state.active?'ACTIVE':'INACTIVE'}</button>:<select disabled={!canWrite} value={state.review} onChange={e=>void mutate('prompt.set_review',p.id,e.target.value)}><option value="approved">APPROVED</option><option value="pending">PENDING</option><option value="blocked">BLOCKED</option></select>}</div></div>})||<p className="system-muted">Загрузка каталога…</p>}</div>
  <div className="system-card prompt-editor-card"><div className="system-card-title"><KeyRound size={18}/><div><h3>Versioned Prompt Content</h3><p>Тело промта доступно только после авторизации роли. Admin создаёт draft; ИБ проверяет; Admin активирует только approved-версию.</p></div></div>{!config?.security?.promptBodiesExposed?<button className="prompt-open" disabled={!canWrite} onClick={()=>void loadBodies()}>Открыть защищённый Prompt Registry</button>:current?<><div className="prompt-toolbar"><select value={current.id} onChange={e=>setSelected(e.target.value)}>{registry.map(p=><option key={p.id} value={p.id}>{p.id} · active v{p.activeVersion}</option>)}</select><span>latest v{current.latestVersion} · {current.latestReview}</span></div><textarea className="prompt-body-editor" value={draft} readOnly={role!=='admin'} onChange={e=>setDraft(e.target.value)} spellCheck={false}/><div className="prompt-meta-line"><span>source: {current.source}</span><span>active v{current.activeVersion}</span><span>{current.versionCount} version(s)</span></div>{role==='admin'?<button className="prompt-primary" disabled={!canWrite||!current.editable||draft.trim().length<20} onClick={()=>void createDraft()}>Создать новую DRAFT-версию</button>:null}<div className="prompt-version-list">{(current.versions||[]).slice().reverse().map(v=><div key={v.version} className="prompt-version-row"><div><strong>v{v.version} · {v.review.toUpperCase()}</strong><small>{v.source} · {v.createdAt||'baseline'} · {v.reason}</small></div><div className="system-action-cell">{role==='security'&&v.source==='runtime'&&v.review==='pending'?<><button className="mini ok" disabled={!canWrite} onClick={()=>void review(v.version,'approved')}>APPROVE</button><button className="mini warn" disabled={!canWrite} onClick={()=>void review(v.version,'blocked')}>BLOCK</button></>:null}{role==='admin'&&v.review==='approved'&&v.version!==current.activeVersion?<button className="mini ok" disabled={!canWrite} onClick={()=>void activate(v.version)}>ACTIVATE</button>:null}{v.version===current.activeVersion?<span className="system-state-label">ACTIVE</span>:null}</div></div>)}</div></>:<p className="system-muted">Нет доступных prompt records.</p>}</div>
 </div>;
}

function KnowledgePanel({config,role,canWrite,mutate}:{config:Config|null;role:Role;canWrite:boolean;mutate:(a:string,t:string,v:MutationValue)=>Promise<void>}){return <div className="system-stack"><div className="system-card"><div className="system-card-title"><Cable size={18}/><div><h3>Knowledge Base Connections</h3><p>{role==='security'?'Security hold поверх тех же canonical KB.':'Включение KB без создания физических копий.'}</p></div></div>{config?.knowledgeBases?.map(k=>{const state=config.control?.kbPolicies?.[k.id]||{enabled:k.status==='configured',securityHold:false};return <div className="system-row system-row-actions" key={k.id}><div><strong>{k.label}</strong><small>{k.id} · {k.path}</small></div><span className="system-state-label">{state.securityHold?'SECURITY HOLD':k.status.toUpperCase()}</span><div className="system-action-cell">{role==='admin'?<button disabled={!canWrite} className={state.enabled?'mini ok':'mini off'} onClick={()=>void mutate('kb.set_enabled',k.id,!state.enabled)}>{state.enabled?'CONNECTED':'DISCONNECTED'}</button>:<button disabled={!canWrite} className={state.securityHold?'mini warn':'mini ok'} onClick={()=>void mutate('kb.set_hold',k.id,!state.securityHold)}>{state.securityHold?'HOLD':'RELEASED'}</button>}</div></div>})||<p className="system-muted">Загрузка подключений…</p>}</div><div className="system-card"><h3>Наследование без дублей</h3><code className="system-code">FOUNDATION → ROLE PROFILE → DOMAIN / TECH → PROJECT / TASK</code><p className="system-muted">Профили агентов ссылаются на canonical ID. DISCONNECTED или SECURITY HOLD блокирует объявленное использование KB на сервере, не изменяя сами знания.</p></div></div>}
function DatabasePanel({config,role,canWrite,mutate}:{config:Config|null;role:Role;canWrite:boolean;mutate:(a:string,t:string,v:MutationValue)=>Promise<void>}){const db=config?.database,flags=config?.control?.database;return <div className="system-stack"><div className="system-summary-grid"><Metric label="PostgreSQL" value={db?.configured?'CONFIGURED':'NOT SET'} tone={db?.configured?'ok':'warn'}/><Metric label="Audit DB" value={db?.eventAuditConfigured?'CONFIGURED':'LOCAL JSONL'} tone={db?.eventAuditConfigured?'ok':'warn'}/><Metric label="Secrets" value="SERVER ONLY" tone="ok"/></div><div className="system-card"><div className="system-card-title"><Database size={18}/><div><h3>Data Layer</h3><p>{role==='security'?'Контроль доступа и разделения данных.':'Runtime flags без хранения connection string в UI.'}</p></div></div><div className="system-kv"><span>Целевая БД</span><strong>{db?.target||'PostgreSQL + pgvector'}</strong><span>Connection string</span><strong>не раскрывается UI</strong><span>Object Storage</span><strong>{db?.objectStorage||'MinIO/S3 — planned'}</strong></div></div>{role==='admin'?<div className="system-card"><h3>Runtime flags</h3><div className="system-toggle-list"><Toggle label="pgvector index" value={Boolean(flags?.vectorIndexEnabled)} disabled={!canWrite} onChange={v=>void mutate('database.set_flag','database',{key:'vectorIndexEnabled',enabled:v})}/><Toggle label="backup policy" value={Boolean(flags?.backupEnabled)} disabled={!canWrite} onChange={v=>void mutate('database.set_flag','database',{key:'backupEnabled',enabled:v})}/><Toggle label="object storage" value={Boolean(flags?.objectStorageEnabled)} disabled={!canWrite} onChange={v=>void mutate('database.set_flag','database',{key:'objectStorageEnabled',enabled:v})}/></div><p className="system-muted">Реальные URL/пароли задаются только server-side через `.env.local` или secret store.</p></div>:<div className="system-card"><h3>ИБ view</h3><p className="system-muted">Connection strings и credentials не раскрываются. ИБ получает только audit/security metadata.</p></div>}</div>}
function AccessPanel({config,role}:{config:Config|null;role:Role}){return <div className="system-stack"><div className="system-summary-grid"><Metric label="Admin RBAC" value={config?.auth?.adminConfigured?'READY':'NOT SET'} tone={config?.auth?.adminConfigured?'ok':'warn'}/><Metric label="IB RBAC" value={config?.auth?.securityConfigured?'READY':'NOT SET'} tone={config?.auth?.securityConfigured?'ok':'warn'}/><Metric label="Текущая роль" value={role==='admin'?'ADMIN':'SECURITY'}/></div><div className="system-card"><div className="system-card-title"><UsersRound size={18}/><div><h3>Role Based Access Control — P0</h3><p>Привилегированные операции проверяются на сервере раздельными role tokens.</p></div></div><div className="system-kv"><span>Роли</span><strong>{config?.roles?.join(' · ')||'ADMINISTRATOR · IB_AI_SECURITY'}</strong><span>Token values exposed</span><strong>{config?.auth?.tokenValuesExposed?'YES':'NO'}</strong><span>Audit required</span><strong>{config?.security?.auditRequired?'YES':'NO'}</strong><span>Схема</span><strong>{config?.schemaVersion||'alina-admin-config-v4'}</strong></div></div><div className="system-card"><h3>Separation of duties</h3><code className="system-code">ADMIN → runtime / routing / prompt drafts + activation\nIB → approve / block / security hold\nREVIEWER → knowledge approval (отдельный контур)</code><p className="system-muted">Индивидуальные users/OIDC пока не имитируются. Этот P0 — реальная серверная авторизация двух независимых привилегированных ролей.</p></div></div>}
function OperationsPanel({config,models,role}:{config:Config|null;models:Model[];role:Role}){const sec=config?.security;return <div className="system-stack"><div className="system-card"><div className="system-card-title">{role==='security'?<ShieldCheck size={18}/>:<Activity size={18}/>}<div><h3>{role==='security'?'Security Control':'Operations Control'}</h3><p>{role==='security'?'AI/KB security, secrets и audit.':'Техническое состояние control plane.'}</p></div></div><div className="system-kv"><span>Privileged writes</span><strong>{sec?.privilegedWritesEnabled?'CONTROLLED':'LOCKED'}</strong><span>Secrets exposed</span><strong>{sec?.secretsExposed?'YES':'NO'}</strong><span>Prompt bodies exposed</span><strong>{sec?.promptBodiesExposed?'AUTHORIZED SESSION':'NO'}</strong><span>Audit required</span><strong>{sec?.auditRequired?'YES':'NO'}</strong><span>Control version</span><strong>{config?.control?.version||1}</strong><span>Updated</span><strong>{config?.control?.updatedAt||'never'}</strong></div></div><div className="system-card"><div className="system-card-title"><KeyRound size={18}/><div><h3>Audit Ledger</h3><p>Последние привилегированные изменения; token values, connection strings и prompt bodies не записываются.</p></div></div><div className="system-audit-list">{config?.audit?.length?config.audit.map(e=><div key={e.eventId}><strong>{e.action}</strong><span>{e.role} · {e.target}</span><small>{e.at} · v{e.stateVersion} · {e.reason}</small></div>):<p className="system-muted">Событий пока нет.</p>}</div><p className="system-muted">Текущий каталог моделей: {models.length} записей.</p></div></div>}
function Toggle({label,value,disabled,onChange}:{label:string;value:boolean;disabled:boolean;onChange:(v:boolean)=>void}){return <button disabled={disabled} className={'system-toggle '+(value?'on':'')} type="button" onClick={()=>onChange(!value)}><span>{label}</span><b>{value?'ON':'OFF'}</b></button>}
function Metric({label,value,tone=''}:{label:string;value:string;tone?:string}){return <div className={'system-metric '+tone}><span>{label}</span><strong>{value}</strong></div>}
