'use client';
import { useState,useRef,useCallback,useEffect } from 'react';
type Recognition = {lang:string;interimResults:boolean;continuous:boolean;onresult:((e:{results:{[key:number]:{isFinal:boolean;[key:number]:{transcript:string}};length:number};resultIndex:number})=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;abort:()=>void};
type VoiceWindow=Window & {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
export function useVoice(onTranscript:(text:string)=>void){
 const [speaking,setSpeaking]=useState(false),[listening,setListening]=useState(false),[error,setError]=useState('');
 const recognition=useRef<Recognition|null>(null);const transcriptHandler=useRef(onTranscript);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const epoch=useRef(0);
 useEffect(()=>{transcriptHandler.current=onTranscript;},[onTranscript]);
 const stop=useCallback(()=>{epoch.current++;window.speechSynthesis?.cancel();setSpeaking(false);if(recognition.current){recognition.current.onend=null;recognition.current.abort();}recognition.current=null;setListening(false);if(timer.current)clearTimeout(timer.current);},[]);
 useEffect(()=>()=>{epoch.current++;window.speechSynthesis?.cancel();recognition.current?.abort();if(timer.current)clearTimeout(timer.current);},[]);
 const speak=useCallback((text:string)=>{stop();setError('');if(!('speechSynthesis' in window)){setError('Озвучка недоступна в этом браузере. Текст Алины остаётся на экране.');return;}const token=epoch.current;const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';u.rate=.96;const voices=window.speechSynthesis.getVoices();const ru=voices.filter(v=>v.lang.toLowerCase().startsWith('ru'));u.voice=ru.find(v=>/female|irina|svetlana|maria|alena/i.test(v.name))||ru[0]||null;u.onstart=()=>{if(token===epoch.current)setSpeaking(true);};u.onend=()=>{if(token===epoch.current)setSpeaking(false);};u.onerror=e=>{if(token!==epoch.current)return;setSpeaking(false);if(e.error!=='canceled'&&e.error!=='interrupted')setError('Не удалось включить голос. Проверьте звук или продолжите по тексту.');};window.speechSynthesis.speak(u);},[stop]);
 const listen=useCallback(()=>{stop();setError('');const w=window as VoiceWindow;const C=w.SpeechRecognition||w.webkitSpeechRecognition;if(!C){setError('Этот браузер не поддерживает распознавание речи. Откройте сайт в Chrome или введите ответ текстом.');return;}const r=new C();recognition.current=r;r.lang='ru-RU';r.interimResults=false;r.continuous=false;let received=false;r.onresult=e=>{const parts=[];for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)parts.push(e.results[i][0].transcript);if(parts.length){received=true;transcriptHandler.current(parts.join(' ').slice(0,1000));}};r.onerror=e=>{received=true;const messages:Record<string,string>={'not-allowed':'Доступ к микрофону не разрешён. Разрешите его в браузере или ответьте текстом.','audio-capture':'Микрофон не найден. Подключите его или ответьте текстом.','network':'Сервис распознавания недоступен. Попробуйте ещё раз или ответьте текстом.','no-speech':'Речь не обнаружена. Попробуйте ещё раз.'};if(e.error!=='aborted')setError(messages[e.error]||'Не удалось распознать речь. Можно ответить текстом.');};r.onend=()=>{setListening(false);if(timer.current)clearTimeout(timer.current);if(!received)setError('Речь не распознана. Повторите или введите ответ.');};try{r.start();setListening(true);timer.current=setTimeout(()=>r.abort(),25000);}catch{setListening(false);setError('Не удалось включить микрофон. Попробуйте снова.');}},[stop]);
 return {speaking,listening,error,speak,listen,stop};
}

