import {mountVoice} from './voice.mjs';
import {clinicKnowledge} from './clinic-knowledge.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let models=[],runs=[],current=null,controller=null,stopped=false;let audioSource=null;
try{runs=JSON.parse(localStorage.getItem('bookcraft.lab.runs')||'[]');if(!Array.isArray(runs))runs=[]}catch{}
$('#system').value='Ты Алина, секретарь клиники. Отвечай кратко по-русски. Приём терапевта стоит 2500 рублей. Свободное время: завтра 10:00 или 14:30. Для заявки спроси имя и телефон. Не подтверждай реальную запись: её согласует администратор. По просьбе клиента передай разговор оператору. Не давай медицинских рекомендаций.';
$('#steps').value='Хочу записаться к терапевту. Сколько стоит приём?\nМожно завтра утром?\nПозовите оператора.';$('#checks').value='2500|2 500\n10:00|10 утра\nоператор|администратор';
function save(){try{localStorage.setItem('bookcraft.lab.runs',JSON.stringify(runs.slice(0,10)))}catch{$('#status').textContent+=' Не удалось сохранить историю: экспортируйте JSON.'}}
function draw(){ $('#history').innerHTML=runs.map(r=>`<option value="${esc(r.id)}" ${r.id===(current||runs[0])?.id?'selected':''}>${esc(new Date(r.created).toLocaleString('ru-RU'))} · ${r.rows.length} ответов</option>`).join('');const rows=current?.rows||runs[0]?.rows||[],ok=rows.filter(r=>!r.error),mean=ok.length?ok.reduce((a,r)=>a+r.elapsedMs,0)/ok.length:0;$('#metrics').innerHTML=[['Ответов',ok.length],['Среднее время',ok.length?(mean/1000).toFixed(2)+' с':'—'],['Условия найдены',ok.filter(r=>r.pass===true).length],['Ошибки',rows.filter(r=>r.error).length]].map(([a,b])=>`<div class="kpi"><div class="kpi-top">${a}</div><strong>${b}</strong></div>`).join('');
 const names=[...new Set(rows.map(r=>r.provider+' / '+r.model))];$('#summary').innerHTML=names.map(name=>{const all=rows.filter(r=>r.provider+' / '+r.model===name),good=all.filter(r=>!r.error),times=good.map(r=>r.elapsedMs).sort((a,b)=>a-b),checked=all.filter(r=>r.pass!==null);return `<tr><td>${esc(name)}</td><td>${good.length}</td><td>${times.length?(times.reduce((a,b)=>a+b,0)/times.length/1000).toFixed(2)+' с':'—'}</td><td>${times.length?(times[Math.ceil(times.length*.95)-1]/1000).toFixed(2)+' с':'—'}</td><td>${checked.filter(r=>r.pass).length}/${checked.length}</td><td>${all.length-good.length}</td></tr>`}).join('');
 $('#results').innerHTML=rows.map(r=>`<article class="lab-answer"><strong>${esc(r.model)} · повтор ${r.repeat} · шаг ${r.step}</strong><p>Клиент: ${esc(r.prompt)}</p><pre>${esc(r.error||r.text)}</pre><p>${r.error?'Ошибка':`${(r.elapsedMs/1000).toFixed(2)} с · ${r.tokens??'—'} токенов · ${r.tokensPerSecond?.toFixed(1)??'—'} ток/с · загрузка ${r.loadMs===null?'—':r.loadMs+' мс'} · ${r.pass===null?'Без проверки':r.pass?'Условие найдено':'Условие не найдено'}${r.finishReason==='length'?' · ответ обрезан лимитом':''}`}</p></article>`).join('')||'<p class="muted">Запустите первый сценарий.</p>';
}
const key=m=>m.provider+'::'+m.id;let selection={mode:'single',ids:['ollama::qwen2.5:3b']};try{const stored=JSON.parse(localStorage.getItem('bookcraft.lab.selection'));if(stored&&['single','compare'].includes(stored.mode)&&Array.isArray(stored.ids))selection=stored;}catch{}
function selected(){return models.filter(m=>selection.ids.includes(key(m))).slice(0,selection.mode==='single'?1:models.length);}
function selectionChanged(){try{localStorage.setItem('bookcraft.lab.selection',JSON.stringify(selection));}catch{}$('#selected-models').textContent='Следующий запуск: '+(selected().map(m=>m.id).join(', ')||'выберите модель');}
function renderModels(){const ids=models.map(key);selection.ids=selection.ids.filter(id=>ids.includes(id));if(!selection.ids.length&&models.length)selection.ids=[ids.includes('ollama::qwen2.5:3b')?'ollama::qwen2.5:3b':ids[0]];$('#model-mode').value=selection.mode;$('#single-model').innerHTML=models.map(m=>`<option value="${esc(key(m))}">${esc(m.id)} · ${esc(m.provider)}</option>`).join('');$('#single-model').value=selection.ids[0]||'';$('#single-label').hidden=selection.mode!=='single';$('#models').hidden=selection.mode==='single';$('#models').innerHTML=models.map(m=>`<label><input type="checkbox" value="${esc(key(m))}" ${selection.ids.includes(key(m))?'checked':''}>${esc(m.id)}<small>${esc(m.provider)}</small></label>`).join('');selectionChanged();}
$('#single-model').onchange=e=>{selection.ids=[e.target.value];selectionChanged();};$('#models').onchange=()=>{selection.ids=[...$('#models').querySelectorAll('input:checked')].map(i=>i.value);selectionChanged();};$('#model-mode').onchange=e=>{selection.mode=e.target.value;if(selection.mode==='single')selection.ids=selection.ids.slice(0,1);renderModels();};
async function discover(){try{$('#reload').disabled=true;const r=await fetch('./api/lab/models');if(!r.ok)throw Error('Полигон доступен через локальный сервер CRM.');const d=await r.json();models=d.models;renderModels();if(!models.length)$('#selected-models').textContent='Модели не найдены. Запустите локальный сервер.';}catch(e){$('#selected-models').textContent=e.message}finally{$('#reload').disabled=false}}
$('#reload').onclick=discover;$('#stop').onclick=()=>{stopped=true;controller?.abort();$('#status').textContent='Останавливаем прогон…'};
$('#run').onclick=async()=>{const chosen=selected(),steps=$('#steps').value.split('\n').map(s=>s.trim()).filter(Boolean),checks=$('#checks').value.split('\n'),system=$('#system').value,repeats=Number($('#repeats').value);if(!chosen.length||!steps.length||steps.length>10||!Number.isInteger(repeats)||repeats<1||repeats>3||system.length>12000||steps.some(s=>s.length>12000)){$('#status').textContent='Выберите модели, задайте 1–10 реплик и 1–3 повтора.';return;}
 current={id:crypto.randomUUID(),created:new Date().toISOString(),source:audioSource?.transcript?.replace(/\s+/g,' ').trim()===steps.join(' ')?structuredClone(audioSource):null,system,steps,checks,models:chosen,repeats,temperature:0,maxTokens:256,knowledge:$('#use-clinic').checked?'clinic-demo-v1':null,knowledgeSnapshot:$('#use-clinic').checked?structuredClone(clinicKnowledge):null,rows:[],status:'running'};runs.unshift(current);runs=runs.slice(0,10);stopped=false;document.querySelectorAll('#model-mode,#single-model,#models input').forEach(el=>el.disabled=true);$('#audio-bench-controls').disabled=true;$('#history').disabled=true;$('#run').disabled=true;$('#reload').disabled=true;$('#stop').disabled=false;$('#progress').max=chosen.length*repeats*steps.length;$('#progress').value=0;save();draw();
 try{outer:for(const m of chosen){for(let repeat=1;repeat<=repeats;repeat++){const messages=[{role:'system',content:system}];for(let i=0;i<steps.length;i++){if(stopped)break outer;$('#status').textContent=`${m.id} · повтор ${repeat}/${repeats} · шаг ${i+1}/${steps.length}`;messages.push({role:'user',content:steps[i]});controller=new AbortController();let row={...m,model:m.id,repeat,step:i+1,prompt:steps[i],expected:checks[i]||'',pass:null};try{const r=await fetch('./api/lab/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:m.provider,model:m.id,messages,knowledge:current.knowledge}),signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка запроса');if(stopped)break outer;row={...row,...d};const alternatives=(checks[i]||'').split('|').map(s=>s.trim().toLocaleLowerCase()).filter(Boolean);row.pass=alternatives.length?alternatives.some(s=>d.text.toLocaleLowerCase().includes(s)):null;messages.push({role:'assistant',content:d.text});}catch(e){if(stopped||e.name==='AbortError')break outer;row.error=e.message;messages.pop();}current.rows.push(row);$('#progress').value++;save();draw();if(row.error)break;}}}current.status=stopped?'cancelled':'completed';$('#status').textContent=stopped?'Остановлено. Готовые ответы сохранены.':'Прогон завершён. Сравните ответы и проверки.';}finally{document.querySelectorAll('#model-mode,#single-model,#models input').forEach(el=>el.disabled=false);$('#audio-bench-controls').disabled=false;$('#history').disabled=false;$('#run').disabled=false;$('#reload').disabled=false;$('#stop').disabled=true;controller=null;save();}};
$('#history').onchange=()=>{current=runs.find(r=>r.id===$('#history').value);if(current){$('#system').value=current.system;$('#steps').value=current.steps.join('\n');$('#checks').value=current.checks.join('\n');$('#repeats').value=current.repeats;$('#use-clinic').checked=current.knowledge==='clinic-demo-v1';$('#status').textContent='Сохранённый прогон · '+current.status;draw();}};
$('#knowledge-preview').textContent=clinicKnowledge.title+'\n\n'+clinicKnowledge.services.map(s=>s.name+' — '+s.price+' ₽\n'+s.slots.join('; ')).join('\n\n')+'\n\nПравила\n'+clinicKnowledge.rules.join('\n')+'\n\nПримеры\n'+clinicKnowledge.examples.map(([q,a])=>'Клиент: '+q+'\nАлина: '+a).join('\n\n');
$('#clinic-template').onclick=()=>{$('#use-clinic').checked=true;$('#system').value='Соблюдай базу знаний. Короткие ответы, один вопрос за раз. Не выдумывай факты.';$('#steps').value=clinicKnowledge.test.steps.join('\n');$('#checks').value=clinicKnowledge.test.checks.join('\n');};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(runs,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bookcraft-model-runs.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};draw();discover();

mountVoice({beforeRecord:()=>{window.speechSynthesis?.cancel();$('#audio-bench-status').textContent='Запишите фразу. После распознавания сравнение начнётся автоматически.';},onAudio:(blob,name)=>{audioSource={name,bytes:blob.size,reference:$('#spoken-reference').value,created:new Date().toISOString()};},onTranscript:async(text,meta)=>{
 if($('#run').disabled){$('#audio-bench-status').textContent='Уже идёт прогон. Дождитесь завершения или остановите его.';return;}
 const reference=audioSource?.reference||$('#spoken-reference').value;audioSource={...audioSource,reference,transcript:text,sttModel:meta.sttModel,sttElapsedMs:meta.elapsedMs};
 $('#audio-comparison').textContent='Вы произнесли: '+reference+'\nWhisper ('+(meta.sttModel||'модель не указана')+'): '+text;
 if(!models.length)await discover();if(!models.length){$('#audio-bench-status').textContent='Текст получен, но LLM недоступны. Запустите сервер моделей и повторите прогон.';return;}
 selection={mode:'compare',ids:models.map(key)};renderModels();$('#steps').value=text.replace(/\s+/g,' ').trim();$('#checks').value='';$('#repeats').value='1';$('#use-clinic').checked=true;$('#system').value='Ты секретарь поликлиники. Следуй базе знаний. Если обращение непонятно, уточни его. Не угадывай врача по бессмысленному тексту.';
 $('#audio-bench-status').textContent='Расшифровка готова. Сравниваем '+models.length+' моделей; источник можно прослушать и сохранить выше.';
 await $('#run').onclick();$('#audio-bench-status').textContent=stopped?'Прогон остановлен. Готовые ответы сохранены.':'Готово: сравните расшифровку и ответы ниже. Модели с ошибкой отмечены отдельно.';
}});
